# Setup {-}

This section describes the setup procedure.

## Authentication {-}

The data are stored in an account on <https://kf.kobotoolbox.org>. 
The login credentials for that account are shared among the PLAY Project staff. 
To access the site's API programmatically, an API key was downloaded and added to the local `~/.Renviron` file.

<!-- https://bookdown.org/yihui/bookdown/html.html#callout-blocks -->
<!--Available blocks are: .rmdnote, .rmdcaution, .rmdimportant, .rmdtip, and .rmdwarning -->
::: {.rmdimportant}
The KoBoToolBox API key is **not** synched to GitHub.
:::


## Set-up {-}

To test whether the local system has the API key installed, we run the command `Sys.getenv("KOBO_API_KEY")`. 

### Check KoBo API Key{-}

```{r check-api-key}
kb_api <- Sys.getenv("KOBO_API_KEY")
if ((length(kb_api) != 1) || (!is.character(kb_api))) {
  stop("'KOBO_API_KEY' not installed in .Renviron")
} else {
  message("'KOBO_API_KEY' installed.")
}
```

### Install dependencies {-}

We now use the [`renv`](https://cran.r-project.org/web/packages/renv/index.html) package to manage package dependencies.

### Load/source helper functions {-}

Most of the work is contained in `R/functions.R`.
This is sourced when we run `tar_make()` from the `{targets}` package.

::: {.rmdimportant}
We run `targets::tar_make()` manually for the time being.

None of the outputs are synced to GitHub.
:::