<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Home visit | PLAY Project: Surveys</title>
<meta name="author" content="Rick Gilmore">
<meta name="generator" content="bookdown 0.29 with bs4_book()">
<meta property="og:title" content="Home visit | PLAY Project: Surveys">
<meta property="og:type" content="book">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="Home visit | PLAY Project: Surveys">
<!-- JS --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/6.4.6/fuse.js" integrity="sha512-zv6Ywkjyktsohkbp9bb45V6tEMoWhzFzXis+LrMehmJZZSys19Yxf1dopHx7WzIKxr5tK2dVcYmaCk2uqdjF4A==" crossorigin="anonymous"></script><script src="https://kit.fontawesome.com/6ecbd6c532.js" crossorigin="anonymous"></script><script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="libs/bootstrap-4.6.0/bootstrap.min.css" rel="stylesheet">
<script src="libs/bootstrap-4.6.0/bootstrap.bundle.min.js"></script><script src="libs/bs3compat-0.4.0/transition.js"></script><script src="libs/bs3compat-0.4.0/tabs.js"></script><script src="libs/bs3compat-0.4.0/bs3compat.js"></script><link href="libs/bs4_book-1.0.0/bs4_book.css" rel="stylesheet">
<script src="libs/bs4_book-1.0.0/bs4_book.js"></script><script src="libs/kePrint-0.0.1/kePrint.js"></script><link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet">
<script src="https://cdnjs.cloudflare.com/ajax/libs/autocomplete.js/0.38.0/autocomplete.jquery.min.js" integrity="sha512-GU9ayf+66Xx2TmpxqJpliWbT5PiGYxpaG8rfnBEk1LL8l1KGkRShhngwdXK1UgqhAzWpZHSiYPc09/NwDQIGyg==" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/mark.min.js" integrity="sha512-5CYOlHXGh6QpOFA/TeTylKLWfB3ftPsde7AnmhuitiTX4K5SqCLBeKro6sPS8ilsz1Q4NRx3v8Ko2IBiszzdww==" crossorigin="anonymous"></script><!-- CSS --><style type="text/css">
    
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  </style>
<link rel="stylesheet" href="include/css/style.css">
<meta name="description" content="Protocol Details about the data collection protocol for the home visit can be found on the [PLAY Project website]((https://www.play-project.org/collection.html#Home_Visit).  Download data Data...">
<meta property="og:description" content="Protocol Details about the data collection protocol for the home visit can be found on the [PLAY Project website]((https://www.play-project.org/collection.html#Home_Visit).  Download data Data...">
<meta name="twitter:description" content="Protocol Details about the data collection protocol for the home visit can be found on the [PLAY Project website]((https://www.play-project.org/collection.html#Home_Visit).  Download data Data...">
</head>
<body data-spy="scroll" data-target="#toc">

<div class="container-fluid">
<div class="row">
  <header class="col-sm-12 col-lg-3 sidebar sidebar-book"><a class="sr-only sr-only-focusable" href="#content">Skip to main content</a>

    <div class="d-flex align-items-start justify-content-between">
      <h1>
        <a href="index.html" title="">PLAY Project: Surveys</a>
      </h1>
      <button class="btn btn-outline-primary d-lg-none ml-2 mt-1" type="button" data-toggle="collapse" data-target="#main-nav" aria-expanded="true" aria-controls="main-nav"><i class="fas fa-bars"></i><span class="sr-only">Show table of contents</span></button>
    </div>

    <div id="main-nav" class="collapse-lg">
      <form role="search">
        <input id="search" class="form-control" type="search" placeholder="Search" aria-label="Search">
</form>

      <nav aria-label="Table of contents"><h2>Table of contents</h2>
        <ul class="book-toc list-unstyled">
<li><a class="" href="index.html">About</a></li>
<li><a class="" href="setup.html">Setup</a></li>
<li><a class="" href="screening-call.html">Screening call</a></li>
<li><a class="active" href="home-visit.html">Home visit</a></li>
<li><a class="" href="data-dictionary.html">Data dictionary</a></li>
<li><a class="" href="visualizations.html">Visualizations</a></li>
</ul>

        <div class="book-extra">
          <p><a id="book-repo" href="https://github.com/PLAY-behaviorome/KoBoToolbox">View book source <i class="fab fa-github"></i></a></p>
        </div>
      </nav>
</div>
  </header><main class="col-sm-12 col-md-9 col-lg-7" id="content"><div id="home-visit" class="section level1 unnumbered">
<h1>Home visit<a class="anchor" aria-label="anchor" href="#home-visit"><i class="fas fa-link"></i></a>
</h1>
<div id="protocol" class="section level2 unnumbered">
<h2>Protocol<a class="anchor" aria-label="anchor" href="#protocol"><i class="fas fa-link"></i></a>
</h2>
<p>Details about the data collection protocol for the home visit can be found on the [PLAY Project website]((<a href="https://www.play-project.org/collection.html#Home_Visit" class="uri">https://www.play-project.org/collection.html#Home_Visit</a>).</p>
</div>
<div id="download-data" class="section level2 unnumbered">
<h2>Download data<a class="anchor" aria-label="anchor" href="#download-data"><i class="fas fa-link"></i></a>
</h2>
<p>Data files for each of the language by age-group conditions are stored on KoBoToolbox (KBT).</p>
<p>Store all of the data files on KBT in <code>kb_df</code>.</p>
<pre><code>tar_target(kb_df, list_kobo_data()),</code></pre>
<div class="sourceCode" id="cb24"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://docs.ropensci.org/targets/">targets</a></span><span class="op">)</span></span>
<span><span class="fu">targets</span><span class="fu">::</span><span class="fu"><a href="https://docs.ropensci.org/targets/reference/tar_load.html">tar_load</a></span><span class="op">(</span><span class="va">kb_df</span><span class="op">)</span></span>
<span><span class="va">kb_df</span></span></code></pre></div>
<pre><code>##         id              id_string
## 1   411456 a58ZhjX6M8WXtzLGvBaEaG
## 2   920365 a6r99tj8RaULvzTM7MuWpi
## 3   740625 a8HyzdxnVjK53dt4fX3Vup
## 4  1129568 a9n2DWjJw3ayJmkijsAm7h
## 5   331453 aae4wz2tpkSnAkea2PAzin
## 6   363465 abYGMsrMvkGsnA4xm9kqC9
## 7   363431 acCBJaRqBkSMPYdvaaWCSu
## 8   334099 ad3NtS6TDPuKTUKCAyCuby
## 9   363349 aEMERWLYQAdhaMKMt5QkD7
## 10  307736 aeMJQLo56HWyVHkKX9oaJD
## 11  334134 agChfbnGHc6fiUdfYUaZ2z
## 12  346565 aGD5Q64T5zTQtakQaS8x55
## 13  359546 aGLEqT7eRBhuPgizCQBeqA
## 14  740631 ahYJ7XRUcit8gbFYwaxnAV
## 15  361981 aJNWkgeX7c9jEFiNAgJspn
## 16  738593 aJPU78BR3NfU9rm4LzRVLt
## 17 1151489 aLqdPLTCZb8jvFkDxcFwzy
## 18  920339 aLxPNje5yoeZijafFoVz5z
## 19  738513 aM2ob4BdwFucdjjcUNTwms
## 20 1136694 aMteoHisncRUStdyZfsjMB
## 21  275882 anqhvxKtQieo7gc9uPqJ3y
## 22  740623 aoLcmmN8KWG4N6A3XpUiRT
## 23  740628 aRJW7SwKsVyZu8b4FighiM
## 24  363466 asv7tL6CEYjiW2XCkLxhcX
## 25  411469 aswcEAtxj24u9MfuBmS9AW
## 26  740630 aThMD6zuEFjtTfptwcpZPg
## 27  411388 aTyGBYk6HvRXmki9ksb29p
## 28  740624 aUeYzPfq6WED4dDF28VT9D
## 29  363381 aWd7wujF5d5HYaYMhT4jBZ
## 30  740626 awMnFDna5kWR3LXKyGmFMd
## 31  331848 axYbEbLcJxzUNFbqMVySjJ
## 32  740629 axyJSgLRDeSk3BHB6cJmYk
## 33  408149 ayhCy68ZTaDGc7tuGthQpJ
## 34  740627 aYokcZAjTZ9JCyVXz4R5rh
##                                                                      title
## 1              PLAY Home Questionaires - 12 Bilingual English (2020-03-04)
## 2                                                 NYU_Pilot DLL-ES_Level_2
## 3                                        PLAY_HomeQuestionaires_12_English
## 4                                        Clone of NYU_Pilot DLL-ES_Level_1
## 5                                    PLAY Home Questionnaires (24 English)
## 6             PLAY Home Questionnaires - 24 Bilingual English (2020-03-04)
## 7                       PLAY Home Questionnaires - 12 English (2020-03-04)
## 8                        PLAY Home Questionnaires (12 Bilingual - English)
## 9                       PLAY Home Questionnaires - 18 English (2020-03-04)
## 10                                   PLAY Home Questionnaires (18 English)
## 11                                PLAY Demographic Questionnaire (Spanish)
## 12                                                   PLAY Post-Visit Notes
## 13                                          PLAY Demographic Questionnaire
## 14                             PLAY_HomeQuestionaires_24_Bilingual_English
## 15                                                   PLAY Post-Visit Notes
## 16                                                DLL-ES_Level_2 (English)
## 17 Clone of Clone of PLAY_HomeQuestionnaires_18_English - NO AUTO METADATA
## 18                                                NYU_Pilot DLL-ES_Level_1
## 19                                               DLL-ES_Level_1_2021_07_30
## 20             Clone of PLAY_HomeQuestionnaires_18_English - NO AUTO TODAY
## 21                                          PLAY Demographic Questionnaire
## 22                             PLAY_HomeQuestionaires_12_Bilingual_English
## 23                                      PLAY_HomeQuestionnaires_18_English
## 24            PLAY Home Questionnaires - 18 Bilingual English (2020-03-04)
## 25            PLAY Home Questionnaires - 12 Bilingual Spanish (2020-03-04)
## 26                             PLAY_HomeQuestionaires_24_Bilingual_Spanish
## 27            PLAY Home Questionnaires - 18 Bilingual Spanish (2020-03-04)
## 28                             PLAY_HomeQuestionaires_12_Bilingual_Spanish
## 29                      PLAY Home Questionnaires - 24 English (2020-03-04)
## 30                             PLAY_HomeQuestionaires_18_Bilingual_English
## 31                                   PLAY Home Questionnaires (12 English)
## 32                                      PLAY_HomeQuestionnaires_24_English
## 33            PLAY Home Questionnaires - 24 Bilingual Spanish (2020-03-04)
## 34                             PLAY_HomeQuestionaires_18_Bilingual_Spanish
##                                                                description
## 1            PLAY Home Questionaires - 12 Bilingual (English) (2020-03-04)
## 2                                                 NYU_Pilot DLL-ES_Level_2
## 3                             PLAY_HomeQuestionaires_12_English-2021-07-29
## 4                                        Clone of NYU_Pilot DLL-ES_Level_1
## 5                                    PLAY Home Questionnaires (24 English)
## 6             PLAY Home Questionnaires - 24 Bilingual English (2019-11-20)
## 7                       PLAY Home Questionnaires - 12 English (2019-11-20)
## 8                        PLAY Home Questionnaires (12 Bilingual - English)
## 9                       PLAY Home Questionnaires - 18 English (2018-11-20)
## 10                                   PLAY Home Questionnaires (18 English)
## 11                                PLAY Demographic Questionnaire (Spanish)
## 12                                              PLAY Cleanup Checklists v2
## 13                                           New Demographic Questionnaire
## 14                  PLAY_HomeQuestionaires_24_Bilingual_English-2021-07-30
## 15                                      PLAY Post-Visit Notes (2019-11-18)
## 16                                          DLL-ES_Level_2_KBTB_2021_07_28
## 17 Clone of Clone of PLAY_HomeQuestionnaires_18_English - NO AUTO METADATA
## 18                                                NYU_Pilot DLL-ES_Level_1
## 19                                               DLL-ES_Level_1_2021_07_28
## 20                             Clone of PLAY_HomeQuestionnaires_18_English
## 21                                                PLAY Phone Questionnaire
## 22                  PLAY_HomeQuestionaires_12_Bilingual_English-2021-07-29
## 23                           PLAY_HomeQuestionnaires_18_English-2021-07-29
## 24            PLAY Home Questionnaires - 18 Bilingual English (2019-11-20)
## 25            PLAY Home Questionnaires - 12 Bilingual Spanish (2020-03-04)
## 26                  PLAY_HomeQuestionaires_24_Bilingual_Spanish-2021-07-30
## 27            PLAY Home Questionnaires - 18 Bilingual Spanish (2020-03-04)
## 28                  PLAY_HomeQuestionaires_12_Bilingual_Spanish-2021-07-29
## 29                      PLAY Home Questionnaires - 24 English (2019-11-20)
## 30                  PLAY_HomeQuestionaires_18_Bilingual_English-2021-07-29
## 31                                   PLAY Home Questionnaires (12 English)
## 32                           PLAY_HomeQuestionnaires_24_English-2021-07-30
## 33            PLAY Home Questionnaires - 24 Bilingual Spanish (2020-02-27)
## 34                  PLAY_HomeQuestionaires_18_Bilingual_Spanish-2021-07-29
##                                               url
## 1   https://kc.kobotoolbox.org/api/v1/data/411456
## 2   https://kc.kobotoolbox.org/api/v1/data/920365
## 3   https://kc.kobotoolbox.org/api/v1/data/740625
## 4  https://kc.kobotoolbox.org/api/v1/data/1129568
## 5   https://kc.kobotoolbox.org/api/v1/data/331453
## 6   https://kc.kobotoolbox.org/api/v1/data/363465
## 7   https://kc.kobotoolbox.org/api/v1/data/363431
## 8   https://kc.kobotoolbox.org/api/v1/data/334099
## 9   https://kc.kobotoolbox.org/api/v1/data/363349
## 10  https://kc.kobotoolbox.org/api/v1/data/307736
## 11  https://kc.kobotoolbox.org/api/v1/data/334134
## 12  https://kc.kobotoolbox.org/api/v1/data/346565
## 13  https://kc.kobotoolbox.org/api/v1/data/359546
## 14  https://kc.kobotoolbox.org/api/v1/data/740631
## 15  https://kc.kobotoolbox.org/api/v1/data/361981
## 16  https://kc.kobotoolbox.org/api/v1/data/738593
## 17 https://kc.kobotoolbox.org/api/v1/data/1151489
## 18  https://kc.kobotoolbox.org/api/v1/data/920339
## 19  https://kc.kobotoolbox.org/api/v1/data/738513
## 20 https://kc.kobotoolbox.org/api/v1/data/1136694
## 21  https://kc.kobotoolbox.org/api/v1/data/275882
## 22  https://kc.kobotoolbox.org/api/v1/data/740623
## 23  https://kc.kobotoolbox.org/api/v1/data/740628
## 24  https://kc.kobotoolbox.org/api/v1/data/363466
## 25  https://kc.kobotoolbox.org/api/v1/data/411469
## 26  https://kc.kobotoolbox.org/api/v1/data/740630
## 27  https://kc.kobotoolbox.org/api/v1/data/411388
## 28  https://kc.kobotoolbox.org/api/v1/data/740624
## 29  https://kc.kobotoolbox.org/api/v1/data/363381
## 30  https://kc.kobotoolbox.org/api/v1/data/740626
## 31  https://kc.kobotoolbox.org/api/v1/data/331848
## 32  https://kc.kobotoolbox.org/api/v1/data/740629
## 33  https://kc.kobotoolbox.org/api/v1/data/408149
## 34  https://kc.kobotoolbox.org/api/v1/data/740627</code></pre>
<p>List data forms specific to the home visit by filtering the files with names that contain “Home”.</p>
<pre><code>tar_target(kb_home, dplyr::filter(kb_df, stringr::str_detect(title, "Home")))</code></pre>
<div class="sourceCode" id="cb27"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu">targets</span><span class="fu">::</span><span class="fu"><a href="https://docs.ropensci.org/targets/reference/tar_load.html">tar_load</a></span><span class="op">(</span><span class="va">kb_home</span><span class="op">)</span></span>
<span><span class="va">kb_home</span></span></code></pre></div>
<pre><code>##         id              id_string
## 1   411456 a58ZhjX6M8WXtzLGvBaEaG
## 2   740625 a8HyzdxnVjK53dt4fX3Vup
## 3   331453 aae4wz2tpkSnAkea2PAzin
## 4   363465 abYGMsrMvkGsnA4xm9kqC9
## 5   363431 acCBJaRqBkSMPYdvaaWCSu
## 6   334099 ad3NtS6TDPuKTUKCAyCuby
## 7   363349 aEMERWLYQAdhaMKMt5QkD7
## 8   307736 aeMJQLo56HWyVHkKX9oaJD
## 9   740631 ahYJ7XRUcit8gbFYwaxnAV
## 10 1151489 aLqdPLTCZb8jvFkDxcFwzy
## 11 1136694 aMteoHisncRUStdyZfsjMB
## 12  740623 aoLcmmN8KWG4N6A3XpUiRT
## 13  740628 aRJW7SwKsVyZu8b4FighiM
## 14  363466 asv7tL6CEYjiW2XCkLxhcX
## 15  411469 aswcEAtxj24u9MfuBmS9AW
## 16  740630 aThMD6zuEFjtTfptwcpZPg
## 17  411388 aTyGBYk6HvRXmki9ksb29p
## 18  740624 aUeYzPfq6WED4dDF28VT9D
## 19  363381 aWd7wujF5d5HYaYMhT4jBZ
## 20  740626 awMnFDna5kWR3LXKyGmFMd
## 21  331848 axYbEbLcJxzUNFbqMVySjJ
## 22  740629 axyJSgLRDeSk3BHB6cJmYk
## 23  408149 ayhCy68ZTaDGc7tuGthQpJ
## 24  740627 aYokcZAjTZ9JCyVXz4R5rh
##                                                                      title
## 1              PLAY Home Questionaires - 12 Bilingual English (2020-03-04)
## 2                                        PLAY_HomeQuestionaires_12_English
## 3                                    PLAY Home Questionnaires (24 English)
## 4             PLAY Home Questionnaires - 24 Bilingual English (2020-03-04)
## 5                       PLAY Home Questionnaires - 12 English (2020-03-04)
## 6                        PLAY Home Questionnaires (12 Bilingual - English)
## 7                       PLAY Home Questionnaires - 18 English (2020-03-04)
## 8                                    PLAY Home Questionnaires (18 English)
## 9                              PLAY_HomeQuestionaires_24_Bilingual_English
## 10 Clone of Clone of PLAY_HomeQuestionnaires_18_English - NO AUTO METADATA
## 11             Clone of PLAY_HomeQuestionnaires_18_English - NO AUTO TODAY
## 12                             PLAY_HomeQuestionaires_12_Bilingual_English
## 13                                      PLAY_HomeQuestionnaires_18_English
## 14            PLAY Home Questionnaires - 18 Bilingual English (2020-03-04)
## 15            PLAY Home Questionnaires - 12 Bilingual Spanish (2020-03-04)
## 16                             PLAY_HomeQuestionaires_24_Bilingual_Spanish
## 17            PLAY Home Questionnaires - 18 Bilingual Spanish (2020-03-04)
## 18                             PLAY_HomeQuestionaires_12_Bilingual_Spanish
## 19                      PLAY Home Questionnaires - 24 English (2020-03-04)
## 20                             PLAY_HomeQuestionaires_18_Bilingual_English
## 21                                   PLAY Home Questionnaires (12 English)
## 22                                      PLAY_HomeQuestionnaires_24_English
## 23            PLAY Home Questionnaires - 24 Bilingual Spanish (2020-03-04)
## 24                             PLAY_HomeQuestionaires_18_Bilingual_Spanish
##                                                                description
## 1            PLAY Home Questionaires - 12 Bilingual (English) (2020-03-04)
## 2                             PLAY_HomeQuestionaires_12_English-2021-07-29
## 3                                    PLAY Home Questionnaires (24 English)
## 4             PLAY Home Questionnaires - 24 Bilingual English (2019-11-20)
## 5                       PLAY Home Questionnaires - 12 English (2019-11-20)
## 6                        PLAY Home Questionnaires (12 Bilingual - English)
## 7                       PLAY Home Questionnaires - 18 English (2018-11-20)
## 8                                    PLAY Home Questionnaires (18 English)
## 9                   PLAY_HomeQuestionaires_24_Bilingual_English-2021-07-30
## 10 Clone of Clone of PLAY_HomeQuestionnaires_18_English - NO AUTO METADATA
## 11                             Clone of PLAY_HomeQuestionnaires_18_English
## 12                  PLAY_HomeQuestionaires_12_Bilingual_English-2021-07-29
## 13                           PLAY_HomeQuestionnaires_18_English-2021-07-29
## 14            PLAY Home Questionnaires - 18 Bilingual English (2019-11-20)
## 15            PLAY Home Questionnaires - 12 Bilingual Spanish (2020-03-04)
## 16                  PLAY_HomeQuestionaires_24_Bilingual_Spanish-2021-07-30
## 17            PLAY Home Questionnaires - 18 Bilingual Spanish (2020-03-04)
## 18                  PLAY_HomeQuestionaires_12_Bilingual_Spanish-2021-07-29
## 19                      PLAY Home Questionnaires - 24 English (2019-11-20)
## 20                  PLAY_HomeQuestionaires_18_Bilingual_English-2021-07-29
## 21                                   PLAY Home Questionnaires (12 English)
## 22                           PLAY_HomeQuestionnaires_24_English-2021-07-30
## 23            PLAY Home Questionnaires - 24 Bilingual Spanish (2020-02-27)
## 24                  PLAY_HomeQuestionaires_18_Bilingual_Spanish-2021-07-29
##                                               url
## 1   https://kc.kobotoolbox.org/api/v1/data/411456
## 2   https://kc.kobotoolbox.org/api/v1/data/740625
## 3   https://kc.kobotoolbox.org/api/v1/data/331453
## 4   https://kc.kobotoolbox.org/api/v1/data/363465
## 5   https://kc.kobotoolbox.org/api/v1/data/363431
## 6   https://kc.kobotoolbox.org/api/v1/data/334099
## 7   https://kc.kobotoolbox.org/api/v1/data/363349
## 8   https://kc.kobotoolbox.org/api/v1/data/307736
## 9   https://kc.kobotoolbox.org/api/v1/data/740631
## 10 https://kc.kobotoolbox.org/api/v1/data/1151489
## 11 https://kc.kobotoolbox.org/api/v1/data/1136694
## 12  https://kc.kobotoolbox.org/api/v1/data/740623
## 13  https://kc.kobotoolbox.org/api/v1/data/740628
## 14  https://kc.kobotoolbox.org/api/v1/data/363466
## 15  https://kc.kobotoolbox.org/api/v1/data/411469
## 16  https://kc.kobotoolbox.org/api/v1/data/740630
## 17  https://kc.kobotoolbox.org/api/v1/data/411388
## 18  https://kc.kobotoolbox.org/api/v1/data/740624
## 19  https://kc.kobotoolbox.org/api/v1/data/363381
## 20  https://kc.kobotoolbox.org/api/v1/data/740626
## 21  https://kc.kobotoolbox.org/api/v1/data/331848
## 22  https://kc.kobotoolbox.org/api/v1/data/740629
## 23  https://kc.kobotoolbox.org/api/v1/data/408149
## 24  https://kc.kobotoolbox.org/api/v1/data/740627</code></pre>
<div id="save-selected-raw-files-to-local-directory-1" class="section level3 unnumbered">
<h3>Save selected raw files to local directory<a class="anchor" aria-label="anchor" href="#save-selected-raw-files-to-local-directory-1"><i class="fas fa-link"></i></a>
</h3>
<p>Prepare to retrieve all home visit files.</p>
<div class="sourceCode" id="cb29"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">n_files</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/dim.html">dim</a></span><span class="op">(</span><span class="va">kb_home</span><span class="op">)</span><span class="op">[</span><span class="fl">1</span><span class="op">]</span></span></code></pre></div>
<p>There are <span class="math inline">\(n=\)</span> 24 home visit data files.</p>
<pre><code>tar_target(home_visit_dir_xlsx, "data/xlsx/home_visit"),
tar_target(home_visit_dir_csv, "data/csv/home_visit"),
tar_target(home_visit_downloads, retrieve_kobo_xlsx(kb_home, home_visit_dir_xlsx))</code></pre>
</div>
<div id="normalize-file-names" class="section level3 unnumbered">
<h3>Normalize file names<a class="anchor" aria-label="anchor" href="#normalize-file-names"><i class="fas fa-link"></i></a>
</h3>
<p>Some of the form names are inconsistent, so we normalize them to fit the following pattern:</p>
<p><code>&lt;form_id&gt;_PLAY_HomeQuestionnaires_&lt;age_group&gt;_&lt;lang_group&gt;.xlsx</code></p>
<pre><code>tar_target(home_visit_renamed, rename_home_xlsx(home_visit_dir_xlsx, home_visit_dir_xlsx))</code></pre>
</div>
<div id="save-xlsx-as-csv" class="section level3 unnumbered">
<h3>Save xlsx as csv<a class="anchor" aria-label="anchor" href="#save-xlsx-as-csv"><i class="fas fa-link"></i></a>
</h3>
<pre><code>tar_target(home_visit_xlsx_to_csv, load_xlsx_save_many_csvs(home_visit_dir_xlsx, home_visit_dir_csv, "Home"))</code></pre>
</div>
<div id="split-mb-cdi-from-other-questions" class="section level3 unnumbered">
<h3>Split MB-CDI from other questions<a class="anchor" aria-label="anchor" href="#split-mb-cdi-from-other-questions"><i class="fas fa-link"></i></a>
</h3>
<p>Next we import a CSV for a given form year, age group, and language group, and create two new CSV files: one with the MB-CDI data and one with all of the other survey questions.</p>
<p>By default, the document presumes that we want to convert <strong>all</strong> of the CSV files</p>
<p>Extract the ‘non-mbcdi’ questions first and add ‘non_mbcdi’ to the filename.</p>
<pre><code>tar_target(home_visit_csvs, list.files(home_visit_dir_csv, '^[0-9]+_PLAY.*\\csv', full.names = TRUE))

tar_target(home_visit_non_mbcdi, purrr::map(
    home_visit_csvs,
    open_split_save,
    csv_save_dir = home_visit_dir_csv,
    these_questions = 'non_mbcdi'
  ))</code></pre>
<p>Extracting the MB-CDI data has nearly the same function call, but the <code>these_questions</code> parameter is set to ‘mbcdi’.</p>
<pre><code>tar_target(home_visit_mbcdi, purrr::map(
    home_visit_csvs,
    open_split_save,
    csv_save_dir = home_visit_dir_csv,
    these_questions = 'mbcdi'
  ))</code></pre>
</div>
</div>
<div id="clean-data" class="section level2 unnumbered">
<h2>Clean data<a class="anchor" aria-label="anchor" href="#clean-data"><i class="fas fa-link"></i></a>
</h2>
<div id="remove-identifiers" class="section level3 unnumbered">
<h3>Remove identifiers<a class="anchor" aria-label="anchor" href="#remove-identifiers"><i class="fas fa-link"></i></a>
</h3>
<p>The function <code>remove_identifiers()</code> in <code>R/kobo_export</code> detects the presence of names, addresses, phone numbers, email, and dates in the field names for an input file and removes these fields.
It also modifies the file name by appending <code>_deidentified</code>.</p>
<p>The <code>remove_identifiers()</code> function detects these fields:</p>
<div class="sourceCode" id="cb35"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/source.html">source</a></span><span class="op">(</span><span class="st">"~/rrr/KoBoToolbox/R/functions.R"</span>, echo <span class="op">=</span> <span class="cn">FALSE</span>, print.eval <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span>
<span><span class="va">remove_identifiers</span></span></code></pre></div>
<pre><code>## function(df) {
##   contains_name &lt;- stringr::str_detect(names(df), 'name')
##   contains_address &lt;- stringr::str_detect(names(df), 'address')
##   contains_phone &lt;- stringr::str_detect(names(df), 'phone')
##   contains_email &lt;- stringr::str_detect(names(df), 'email')
##   contains_birthdate &lt;- stringr::str_detect(names(df), 'birthdate')
##   contains_first &lt;- stringr::str_detect(names(df), 'first[12]?')
##   contains_last &lt;- stringr::str_detect(names(df), 'last[12]?')
##   contains_city &lt;- stringr::str_detect(names(df), 'city')
##   contains_year &lt;- stringr::str_detect(names(df), 'year[12]?')
##   contains_month &lt;- stringr::str_detect(names(df), 'month[12]?')
##   contains_day &lt;- stringr::str_detect(names(df), '/day[12]?$')
##   
##   identifiable_data &lt;- contains_name | contains_address |
##     contains_phone |
##     contains_email | contains_birthdate | contains_first |
##     contains_last |
##     contains_city | contains_year | contains_month | contains_day
##   
##   identifiable_cols &lt;- (1:length(names(df)))[identifiable_data]
##   
##   df_deidentified &lt;- df %&gt;%
##     dplyr::select(.,-all_of(identifiable_cols))
##   
##   df_deidentified
## }</code></pre>
<p>The <strong>non-MBCDI file</strong> contains the identifiers, so that is the target of this removal process.</p>
<div class="rmdnote">
<p>Note that we have added <code>data</code> to <code>.gitignore</code> in <code>protocol/</code>, the root directory for the HTML protocol, so <em>none</em> of the data files should be made available via git or GitHub. This also means that there is <strong>no version control</strong> being done on raw data files themselves.</p>
</div>
<pre><code>tar_target(home_visit_non_mbcdi_csvs, list.files(home_visit_dir_csv, '^[0-9]+_non_mbcdi.*\\csv', full.names = TRUE)),

tar_target(home_visit_remove_identifiers, purrr::map(
    home_visit_non_mbcdi_csvs,
    open_deidentify_save,
    csv_save_dir = home_visit_dir_csv,
    these_questions = 'non_mbcdi'
  ))</code></pre>
</div>
</div>
<div id="quality-assurance-qa-reviews" class="section level2 unnumbered">
<h2>Quality assurance (QA) reviews<a class="anchor" aria-label="anchor" href="#quality-assurance-qa-reviews"><i class="fas fa-link"></i></a>
</h2>
<div id="mb-cdi-files" class="section level3 unnumbered">
<h3>MB-CDI files<a class="anchor" aria-label="anchor" href="#mb-cdi-files"><i class="fas fa-link"></i></a>
</h3>
</div>
<div id="non-mb-cdi-files" class="section level3 unnumbered">
<h3>Non-MB-CDI files<a class="anchor" aria-label="anchor" href="#non-mb-cdi-files"><i class="fas fa-link"></i></a>
</h3>
<p>Create a helper function to create a data set with summary information about the data files.</p>
<div class="sourceCode" id="cb38"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">summarize_non_mbcdi_qs</span> <span class="op">&lt;-</span> <span class="kw">function</span><span class="op">(</span><span class="va">fn</span><span class="op">)</span> <span class="op">{</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/base/stopifnot.html">stopifnot</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/character.html">is.character</a></span><span class="op">(</span><span class="va">fn</span><span class="op">)</span><span class="op">)</span></span>
<span>  </span>
<span>  <span class="kw">if</span> <span class="op">(</span><span class="op">!</span><span class="fu"><a href="https://rdrr.io/r/base/files.html">file.exists</a></span><span class="op">(</span><span class="va">fn</span><span class="op">)</span><span class="op">)</span> <span class="op">{</span></span>
<span>    <span class="kw"><a href="https://rdrr.io/r/base/stop.html">stop</a></span><span class="op">(</span><span class="st">'File not found `'</span>, <span class="va">fn</span>, <span class="st">'`'</span><span class="op">)</span></span>
<span>  <span class="op">}</span> <span class="kw">else</span> <span class="op">{</span></span>
<span>    <span class="va">df</span> <span class="op">&lt;-</span> <span class="fu">readr</span><span class="fu">::</span><span class="fu"><a href="https://readr.tidyverse.org/reference/read_delim.html">read_csv</a></span><span class="op">(</span><span class="va">fn</span>, show_col_types <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span>
<span>    <span class="kw">if</span> <span class="op">(</span><span class="op">!</span><span class="fu"><a href="https://rdrr.io/r/base/as.data.frame.html">is.data.frame</a></span><span class="op">(</span><span class="va">df</span><span class="op">)</span><span class="op">)</span> <span class="op">{</span></span>
<span>      <span class="kw"><a href="https://rdrr.io/r/base/stop.html">stop</a></span><span class="op">(</span><span class="st">'Error reading data frame'</span><span class="op">)</span></span>
<span>    <span class="op">}</span> <span class="kw">else</span> <span class="op">{</span></span>
<span>      <span class="va">out_df</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://tibble.tidyverse.org/reference/tibble.html">tibble</a></span><span class="op">(</span>file_name <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/basename.html">basename</a></span><span class="op">(</span><span class="va">fn</span><span class="op">)</span>, n_rows <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/dim.html">dim</a></span><span class="op">(</span><span class="va">df</span><span class="op">)</span><span class="op">[</span><span class="fl">1</span><span class="op">]</span>, n_vars <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/dim.html">dim</a></span><span class="op">(</span><span class="va">df</span><span class="op">)</span><span class="op">[</span><span class="fl">2</span><span class="op">]</span><span class="op">)</span></span>
<span>      <span class="fu">dplyr</span><span class="fu">::</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/arrange.html">arrange</a></span><span class="op">(</span><span class="va">out_df</span>, <span class="va">file_name</span><span class="op">)</span></span>
<span>    <span class="op">}</span></span>
<span>  <span class="op">}</span></span>
<span><span class="op">}</span></span></code></pre></div>
<p>Select the de-identified CSVs to examine.</p>
<div class="sourceCode" id="cb39"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu">targets</span><span class="fu">::</span><span class="fu"><a href="https://docs.ropensci.org/targets/reference/tar_load.html">tar_load</a></span><span class="op">(</span><span class="va">home_visit_dir_csv</span><span class="op">)</span></span>
<span><span class="va">fl</span> <span class="op">&lt;-</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/base/list.files.html">list.files</a></span><span class="op">(</span></span>
<span>    <span class="fu"><a href="https://rdrr.io/r/base/file.path.html">file.path</a></span><span class="op">(</span><span class="va">home_visit_dir_csv</span><span class="op">)</span>,</span>
<span>    <span class="st">'^[0-9]+_non_mbcdi_[12|18|24].*deidentified'</span>,</span>
<span>    full.names <span class="op">=</span> <span class="cn">TRUE</span></span>
<span>  <span class="op">)</span></span>
<span></span>
<span><span class="va">PLAY_forms</span> <span class="op">&lt;-</span> <span class="fu">purrr</span><span class="fu">::</span><span class="fu"><a href="https://purrr.tidyverse.org/reference/map.html">map_df</a></span><span class="op">(</span><span class="va">fl</span>, <span class="va">summarize_non_mbcdi_qs</span><span class="op">)</span></span>
<span></span>
<span><span class="va">PLAY_forms</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu">knitr</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/knitr/man/kable.html">kable</a></span><span class="op">(</span><span class="va">.</span>, format <span class="op">=</span> <span class="st">'html'</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu">kableExtra</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/kableExtra/man/kable_classic.html">kable_classic</a></span><span class="op">(</span><span class="op">)</span></span></code></pre></div>
<div class="inline-table"><table class=" lightable-classic" style='font-family: "Arial Narrow", "Source Sans Pro", sans-serif; margin-left: auto; margin-right: auto;'>
<thead><tr>
<th style="text-align:left;">
file_name
</th>
<th style="text-align:right;">
n_rows
</th>
<th style="text-align:right;">
n_vars
</th>
</tr></thead>
<tbody>
<tr>
<td style="text-align:left;">
113669_non_mbcdi_18_english_deidentified.csv
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
288
</td>
</tr>
<tr>
<td style="text-align:left;">
1136694_non_mbcdi_18_english_deidentified.csv
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
288
</td>
</tr>
<tr>
<td style="text-align:left;">
115148_non_mbcdi_18_english_deidentified.csv
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
286
</td>
</tr>
<tr>
<td style="text-align:left;">
1151489_non_mbcdi_18_english_deidentified.csv
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
286
</td>
</tr>
<tr>
<td style="text-align:left;">
307736_non_mbcdi_18_english_deidentified.csv
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
274
</td>
</tr>
<tr>
<td style="text-align:left;">
331453_non_mbcdi_24_english_deidentified.csv
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
274
</td>
</tr>
<tr>
<td style="text-align:left;">
331848_non_mbcdi_12_english_deidentified.csv
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
267
</td>
</tr>
<tr>
<td style="text-align:left;">
334099_non_mbcdi_12_bilingual_english_deidentified.csv
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
267
</td>
</tr>
<tr>
<td style="text-align:left;">
363349_non_mbcdi_18_english_deidentified.csv
</td>
<td style="text-align:right;">
9
</td>
<td style="text-align:right;">
280
</td>
</tr>
<tr>
<td style="text-align:left;">
363381_non_mbcdi_24_english_deidentified.csv
</td>
<td style="text-align:right;">
8
</td>
<td style="text-align:right;">
280
</td>
</tr>
<tr>
<td style="text-align:left;">
363431_non_mbcdi_12_english_deidentified.csv
</td>
<td style="text-align:right;">
10
</td>
<td style="text-align:right;">
281
</td>
</tr>
<tr>
<td style="text-align:left;">
363465_non_mbcdi_24_bilingual_english_deidentified.csv
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
280
</td>
</tr>
<tr>
<td style="text-align:left;">
363466_non_mbcdi_18_bilingual_english_deidentified.csv
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
280
</td>
</tr>
<tr>
<td style="text-align:left;">
408149_non_mbcdi_24_bilingual_spanish_deidentified.csv
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
280
</td>
</tr>
<tr>
<td style="text-align:left;">
411388_non_mbcdi_18_bilingual_spanish_deidentified.csv
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
280
</td>
</tr>
<tr>
<td style="text-align:left;">
411456_non_mbcdi_12_bilingual_english_deidentified.csv
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
280
</td>
</tr>
<tr>
<td style="text-align:left;">
411469_non_mbcdi_12_bilingual_spanish_deidentified.csv
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
280
</td>
</tr>
<tr>
<td style="text-align:left;">
740623_non_mbcdi_12_bilingual_english_deidentified.csv
</td>
<td style="text-align:right;">
6
</td>
<td style="text-align:right;">
288
</td>
</tr>
<tr>
<td style="text-align:left;">
740624_non_mbcdi_12_bilingual_spanish_deidentified.csv
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
288
</td>
</tr>
<tr>
<td style="text-align:left;">
740625_non_mbcdi_12_english_deidentified.csv
</td>
<td style="text-align:right;">
41
</td>
<td style="text-align:right;">
288
</td>
</tr>
<tr>
<td style="text-align:left;">
740626_non_mbcdi_18_bilingual_english_deidentified.csv
</td>
<td style="text-align:right;">
9
</td>
<td style="text-align:right;">
287
</td>
</tr>
<tr>
<td style="text-align:left;">
740627_non_mbcdi_18_bilingual_spanish_deidentified.csv
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
287
</td>
</tr>
<tr>
<td style="text-align:left;">
740628_non_mbcdi_18_english_deidentified.csv
</td>
<td style="text-align:right;">
45
</td>
<td style="text-align:right;">
288
</td>
</tr>
<tr>
<td style="text-align:left;">
740629_non_mbcdi_24_english_deidentified.csv
</td>
<td style="text-align:right;">
39
</td>
<td style="text-align:right;">
287
</td>
</tr>
<tr>
<td style="text-align:left;">
740630_non_mbcdi_24_bilingual_spanish_deidentified.csv
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
287
</td>
</tr>
<tr>
<td style="text-align:left;">
740631_non_mbcdi_24_bilingual_english_deidentified.csv
</td>
<td style="text-align:right;">
12
</td>
<td style="text-align:right;">
287
</td>
</tr>
</tbody>
</table></div>
<p>The later forms (with higher form numbers–the leading integers in the file names) are the newer ones.
These generally have the largest number of entries and have similar numbers of columns–either 287 or 288.
Accordingly, we focus our cleaning efforts here first.</p>
<p>We start with the data files that have <span class="math inline">\(n=288\)</span> columns.</p>
<div class="sourceCode" id="cb40"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">df740623</span> <span class="op">&lt;-</span> <span class="fu">readr</span><span class="fu">::</span><span class="fu"><a href="https://readr.tidyverse.org/reference/read_delim.html">read_csv</a></span><span class="op">(</span><span class="st">"data/csv/home_visit/740623_non_mbcdi_12_bilingual_english_deidentified.csv"</span>, show_col_types <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span>
<span></span>
<span><span class="va">df740624</span> <span class="op">&lt;-</span> <span class="fu">readr</span><span class="fu">::</span><span class="fu"><a href="https://readr.tidyverse.org/reference/read_delim.html">read_csv</a></span><span class="op">(</span><span class="st">"data/csv/home_visit/740624_non_mbcdi_12_bilingual_spanish_deidentified.csv"</span>, show_col_types <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">df740623</span><span class="op">)</span> <span class="op">==</span> <span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">df740624</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<pre><code>## [1] 288</code></pre>
<div class="sourceCode" id="cb42"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">df740625</span> <span class="op">&lt;-</span> <span class="fu">readr</span><span class="fu">::</span><span class="fu"><a href="https://readr.tidyverse.org/reference/read_delim.html">read_csv</a></span><span class="op">(</span><span class="st">"data/csv/home_visit/740625_non_mbcdi_12_english_deidentified.csv"</span>, show_col_types <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">df740623</span><span class="op">)</span> <span class="op">==</span> <span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">df740625</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<pre><code>## [1] 288</code></pre>
<div class="sourceCode" id="cb44"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">df740628</span> <span class="op">&lt;-</span> <span class="fu">readr</span><span class="fu">::</span><span class="fu"><a href="https://readr.tidyverse.org/reference/read_delim.html">read_csv</a></span><span class="op">(</span><span class="st">"data/csv/home_visit/740628_non_mbcdi_18_english_deidentified.csv"</span>, show_col_types <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">df740623</span><span class="op">)</span> <span class="op">==</span> <span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">df740628</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<pre><code>## [1] 288</code></pre>
<p>So, four of the most recent data files with <span class="math inline">\(n=288\)</span> columns can be aggregated without modification.</p>
<p>Let’s turn to the more recent files with <span class="math inline">\(n=287\)</span> columns.</p>
<div class="sourceCode" id="cb46"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">df740626</span> <span class="op">&lt;-</span> <span class="fu">readr</span><span class="fu">::</span><span class="fu"><a href="https://readr.tidyverse.org/reference/read_delim.html">read_csv</a></span><span class="op">(</span><span class="st">"data/csv/home_visit/740626_non_mbcdi_18_bilingual_english_deidentified.csv"</span>, show_col_types <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span>
<span></span>
<span><span class="va">df740627</span> <span class="op">&lt;-</span> <span class="fu">readr</span><span class="fu">::</span><span class="fu"><a href="https://readr.tidyverse.org/reference/read_delim.html">read_csv</a></span><span class="op">(</span><span class="st">"data/csv/home_visit/740627_non_mbcdi_18_bilingual_spanish_deidentified.csv"</span>, show_col_types <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">df740626</span><span class="op">)</span> <span class="op">==</span> <span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">df740627</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<pre><code>## [1] 100</code></pre>
<p>Where does the misalignment arise?</p>
<div class="sourceCode" id="cb48"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">df740626</span><span class="op">)</span> <span class="op">==</span> <span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">df740627</span><span class="op">)</span></span></code></pre></div>
<pre><code>##   [1]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
##  [16]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
##  [31]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
##  [46]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
##  [61]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
##  [76]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
##  [91]  TRUE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
## [106] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
## [121] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
## [136] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
## [151] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
## [166] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
## [181] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
## [196] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
## [211] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
## [226] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
## [241] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
## [256] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
## [271] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
## [286]  TRUE  TRUE</code></pre>
<p>The misalignment arises somewhere near column 92.</p>
<div class="sourceCode" id="cb50"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">df740629</span> <span class="op">&lt;-</span> <span class="fu">readr</span><span class="fu">::</span><span class="fu"><a href="https://readr.tidyverse.org/reference/read_delim.html">read_csv</a></span><span class="op">(</span><span class="st">"data/csv/home_visit/740629_non_mbcdi_24_english_deidentified.csv"</span>, show_col_types <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">df740626</span><span class="op">)</span> <span class="op">==</span> <span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">df740629</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<pre><code>## [1] 287</code></pre>
<p>So, <code>df740626</code> and <code>df740629</code> are aligned and can be merged.</p>
<div class="sourceCode" id="cb52"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">df740630</span> <span class="op">&lt;-</span> <span class="fu">readr</span><span class="fu">::</span><span class="fu"><a href="https://readr.tidyverse.org/reference/read_delim.html">read_csv</a></span><span class="op">(</span><span class="st">"data/csv/home_visit/740630_non_mbcdi_24_bilingual_spanish_deidentified.csv"</span>, show_col_types <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">df740626</span><span class="op">)</span> <span class="op">==</span> <span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">df740630</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<pre><code>## [1] 100</code></pre>
<div class="sourceCode" id="cb54"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">df740626</span><span class="op">)</span> <span class="op">==</span> <span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">df740630</span><span class="op">)</span></span></code></pre></div>
<pre><code>##   [1]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
##  [16]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
##  [31]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
##  [46]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
##  [61]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
##  [76]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
##  [91]  TRUE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
## [106] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
## [121] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
## [136] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
## [151] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
## [166] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
## [181] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
## [196] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
## [211] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
## [226] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
## [241] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
## [256] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
## [271] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
## [286]  TRUE  TRUE</code></pre>
<p>These files also fall out of alignment near column 92.</p>
<div class="sourceCode" id="cb56"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">df740631</span> <span class="op">&lt;-</span> <span class="fu">readr</span><span class="fu">::</span><span class="fu"><a href="https://readr.tidyverse.org/reference/read_delim.html">read_csv</a></span><span class="op">(</span><span class="st">"data/csv/home_visit/740631_non_mbcdi_24_bilingual_english_deidentified.csv"</span>, show_col_types <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">df740626</span><span class="op">)</span> <span class="op">==</span> <span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">df740631</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<pre><code>## [1] 100</code></pre>
<div class="sourceCode" id="cb58"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">df740626</span><span class="op">)</span> <span class="op">==</span> <span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">df740631</span><span class="op">)</span></span></code></pre></div>
<pre><code>##   [1]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
##  [16]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
##  [31]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
##  [46]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
##  [61]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
##  [76]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
##  [91]  TRUE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
## [106] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
## [121] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
## [136] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
## [151] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
## [166] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
## [181] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
## [196] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
## [211] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
## [226] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
## [241] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
## [256] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
## [271] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
## [286]  TRUE  TRUE</code></pre>
<p>And these files fall out of alignment near column 92.</p>
<p>Let’s see if <code>df740627</code>, <code>df740630</code>, and <code>df740631</code> are aligned with one another.</p>
<div class="sourceCode" id="cb60"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">df740627</span><span class="op">)</span> <span class="op">==</span> <span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">df740630</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<pre><code>## [1] 287</code></pre>
<div class="sourceCode" id="cb62"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">df740627</span><span class="op">)</span> <span class="op">==</span> <span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">df740631</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<pre><code>## [1] 287</code></pre>
<p>Yes, they are. So, these three can be merged.
We do that first, then address the discrepancies between aggregates.</p>
</div>
</div>
<div id="make-aggregate-files" class="section level2 unnumbered">
<h2>Make aggregate files<a class="anchor" aria-label="anchor" href="#make-aggregate-files"><i class="fas fa-link"></i></a>
</h2>
<div id="non-mb-cdi-files-with-n288-columns" class="section level3" number="0.0.1">
<h3>
<span class="header-section-number">0.0.1</span> non-MB-CDI files with <span class="math inline">\(n=288\)</span> columns<a class="anchor" aria-label="anchor" href="#non-mb-cdi-files-with-n288-columns"><i class="fas fa-link"></i></a>
</h3>
<pre><code>tar_target(files_w_288_cols, list.files(home_visit_dir_csv, 
  "2[3458]_non_mbcdi.*_deidentified", full.names = TRUE)),

tar_target(df_merge_288_cols, make_aggregate_data_file(files_with_288_cols))</code></pre>
</div>
<div id="non-mb-cdi-files-with-n287-columns" class="section level3" number="0.0.2">
<h3>
<span class="header-section-number">0.0.2</span> non-MB-CDI files with <span class="math inline">\(n=287\)</span> columns<a class="anchor" aria-label="anchor" href="#non-mb-cdi-files-with-n287-columns"><i class="fas fa-link"></i></a>
</h3>
<pre><code>tar_target(files_w_287_cols_1, 
  list.files(home_visit_dir_csv, "2[69]_non_mbcdi.*_deidentified", full.names = TRUE)),
tar_target(df_merge_287_cols_1, make_aggregate_data_file(files_w_287_cols_1)),

tar_target(files_w_287_cols_2, 
  list.files(home_visit_dir_csv, list.files(home_visit_dir_csv, "(740627|740630|740631)_non.*_deidentified", full.names = TRUE)),
tar_target(df_merge_288_cols_2, make_aggregate_data_file(files_w_287_cols_2))</code></pre>
</div>
<div id="examine-groups-with-n287-cols" class="section level3" number="0.0.3">
<h3>
<span class="header-section-number">0.0.3</span> Examine groups with <span class="math inline">\(n=287\)</span> cols<a class="anchor" aria-label="anchor" href="#examine-groups-with-n287-cols"><i class="fas fa-link"></i></a>
</h3>
<p>We focus on the starting column where the column names diverge, column 92.</p>
<div class="sourceCode" id="cb66"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://docs.ropensci.org/targets/reference/tar_load.html">tar_load</a></span><span class="op">(</span><span class="va">df_merge_287_cols_1</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://docs.ropensci.org/targets/reference/tar_load.html">tar_load</a></span><span class="op">(</span><span class="va">df_merge_287_cols_2</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">df_merge_287_cols_1</span><span class="op">)</span><span class="op">[</span><span class="fl">92</span><span class="op">]</span></span></code></pre></div>
<pre><code>## [1] "group_combinedquestionnaires.group_homevisitquestionnaires.group_health.group_feeding_nutrition.instructions_feeding"</code></pre>
<div class="sourceCode" id="cb68"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">df_merge_287_cols_2</span><span class="op">)</span><span class="op">[</span><span class="fl">92</span><span class="op">]</span></span></code></pre></div>
<pre><code>## [1] "group_combinedquestionnaires.group_homevisitquestionnaires.group_locomotor_milestones.group_health.group_feeding_nutrition.instructions_feeding"</code></pre>
<p>There is an erroneous <code>group_locomotor_milestones.</code> in the <code>df_merge_287_cols_2</code> column name.</p>
<p>A bit of sleuthing determines that this <code>group_locomotor_milestones.</code> label is characteristic of columns 92 to 182.</p>
<div class="sourceCode" id="cb70"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">df_merge_287_cols_2</span><span class="op">)</span><span class="op">[</span><span class="fl">92</span><span class="op">:</span><span class="fl">287</span><span class="op">]</span> <span class="op">|&gt;</span> <span class="fu">stringr</span><span class="fu">::</span><span class="fu"><a href="https://stringr.tidyverse.org/reference/str_detect.html">str_detect</a></span><span class="op">(</span>pattern <span class="op">=</span> <span class="st">"group_locomotor_milestones"</span><span class="op">)</span></span></code></pre></div>
<pre><code>##   [1]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
##  [16]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
##  [31]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
##  [46]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
##  [61]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
##  [76]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
##  [91]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
## [106]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
## [121]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
## [136]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
## [151]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
## [166]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
## [181]  TRUE  TRUE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
## [196] FALSE</code></pre>
<p>The following should fix this.</p>
<div class="sourceCode" id="cb72"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">old_names</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">df_merge_287_cols_2</span><span class="op">)</span></span>
<span><span class="va">new_names</span> <span class="op">&lt;-</span> <span class="va">old_names</span></span>
<span><span class="va">new_names</span><span class="op">[</span><span class="fl">92</span><span class="op">:</span><span class="fl">113</span><span class="op">]</span> <span class="op">&lt;-</span> <span class="fu">stringr</span><span class="fu">::</span><span class="fu"><a href="https://stringr.tidyverse.org/reference/str_remove.html">str_remove</a></span><span class="op">(</span><span class="va">new_names</span><span class="op">[</span><span class="fl">92</span><span class="op">:</span><span class="fl">113</span><span class="op">]</span>, <span class="st">"group_locomotor_milestones\\."</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">df_merge_287_cols_2</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="va">new_names</span></span></code></pre></div>
<div class="sourceCode" id="cb73"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">df_merge_287_cols_2</span><span class="op">)</span> <span class="op">==</span> <span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">df_merge_287_cols_1</span><span class="op">)</span></span></code></pre></div>
<pre><code>##   [1]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
##  [16]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
##  [31]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
##  [46]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
##  [61]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
##  [76]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
##  [91]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
## [106]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
## [121] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
## [136] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
## [151] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
## [166] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
## [181] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
## [196] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
## [211] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
## [226] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
## [241] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
## [256] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
## [271] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
## [286]  TRUE  TRUE</code></pre>
<p>We have a second problem with columns from 114 to 278.</p>
<p>One of the problems has to do with column 114. There is a question ending <code>doctor_told_you</code> in <code>names(df_merge_287_cols_1)</code> but not in <code>names(df_merge_287_cols_2)</code>.</p>
<div class="sourceCode" id="cb75"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">df_merge_287_cols_1</span><span class="op">)</span> <span class="op">|&gt;</span> <span class="fu">stringr</span><span class="fu">::</span><span class="fu"><a href="https://stringr.tidyverse.org/reference/str_detect.html">str_detect</a></span><span class="op">(</span>pattern <span class="op">=</span> <span class="st">"doctor_told_you"</span><span class="op">)</span> <span class="op">|&gt;</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="op">)</span></span></code></pre></div>
<pre><code>## [1] 1</code></pre>
<div class="sourceCode" id="cb77"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">df_merge_287_cols_2</span><span class="op">)</span> <span class="op">|&gt;</span> <span class="fu">stringr</span><span class="fu">::</span><span class="fu"><a href="https://stringr.tidyverse.org/reference/str_detect.html">str_detect</a></span><span class="op">(</span>pattern <span class="op">=</span> <span class="st">"doctor_told_you"</span><span class="op">)</span> <span class="op">|&gt;</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="op">)</span></span></code></pre></div>
<pre><code>## [1] 0</code></pre>
<p>Deleting this question would create additional misalignments and further problems.
We cannot proceed without further discussion with our team.</p>
</div>
</div>
<div id="merge-with-databrary-info" class="section level2 unnumbered">
<h2>Merge with Databrary info<a class="anchor" aria-label="anchor" href="#merge-with-databrary-info"><i class="fas fa-link"></i></a>
</h2>
</div>
<div id="clean-and-prepare-for-export" class="section level2 unnumbered">
<h2>Clean and prepare for export<a class="anchor" aria-label="anchor" href="#clean-and-prepare-for-export"><i class="fas fa-link"></i></a>
</h2>

</div>
</div>
  <div class="chapter-nav">
<div class="prev"><a href="screening-call.html">Screening call</a></div>
<div class="next"><a href="data-dictionary.html">Data dictionary</a></div>
</div></main><div class="col-md-3 col-lg-2 d-none d-md-block sidebar sidebar-chapter">
    <nav id="toc" data-toggle="toc" aria-label="On this page"><h2>On this page</h2>
      <ul class="nav navbar-nav">
<li><a class="nav-link" href="#home-visit">Home visit</a></li>
<li><a class="nav-link" href="#protocol">Protocol</a></li>
<li>
<a class="nav-link" href="#download-data">Download data</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#save-selected-raw-files-to-local-directory-1">Save selected raw files to local directory</a></li>
<li><a class="nav-link" href="#normalize-file-names">Normalize file names</a></li>
<li><a class="nav-link" href="#save-xlsx-as-csv">Save xlsx as csv</a></li>
<li><a class="nav-link" href="#split-mb-cdi-from-other-questions">Split MB-CDI from other questions</a></li>
</ul>
</li>
<li>
<a class="nav-link" href="#clean-data">Clean data</a><ul class="nav navbar-nav"><li><a class="nav-link" href="#remove-identifiers">Remove identifiers</a></li></ul>
</li>
<li>
<a class="nav-link" href="#quality-assurance-qa-reviews">Quality assurance (QA) reviews</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#mb-cdi-files">MB-CDI files</a></li>
<li><a class="nav-link" href="#non-mb-cdi-files">Non-MB-CDI files</a></li>
</ul>
</li>
<li>
<a class="nav-link" href="#make-aggregate-files">Make aggregate files</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#non-mb-cdi-files-with-n288-columns"><span class="header-section-number">0.0.1</span> non-MB-CDI files with \(n=288\) columns</a></li>
<li><a class="nav-link" href="#non-mb-cdi-files-with-n287-columns"><span class="header-section-number">0.0.2</span> non-MB-CDI files with \(n=287\) columns</a></li>
<li><a class="nav-link" href="#examine-groups-with-n287-cols"><span class="header-section-number">0.0.3</span> Examine groups with \(n=287\) cols</a></li>
</ul>
</li>
<li><a class="nav-link" href="#merge-with-databrary-info">Merge with Databrary info</a></li>
<li><a class="nav-link" href="#clean-and-prepare-for-export">Clean and prepare for export</a></li>
</ul>

      <div class="book-extra">
        <ul class="list-unstyled">
<li><a id="book-source" href="https://github.com/PLAY-behaviorome/KoBoToolbox/blob/master/03-home-visit.Rmd">View source <i class="fab fa-github"></i></a></li>
          <li><a id="book-edit" href="https://github.com/PLAY-behaviorome/KoBoToolbox/edit/master/03-home-visit.Rmd">Edit this page <i class="fab fa-github"></i></a></li>
        </ul>
</div>
    </nav>
</div>

</div>
</div> <!-- .container -->

<footer class="bg-primary text-light mt-5"><div class="container"><div class="row">

  <div class="col-12 col-md-6 mt-3">
    <p>"<strong>PLAY Project: Surveys</strong>" was written by Rick Gilmore. It was last built on 2022-12-14.</p>
  </div>

  <div class="col-12 col-md-6 mt-3">
    <p>This book was built by the <a class="text-light" href="https://bookdown.org">bookdown</a> R package.</p>
  </div>

</div></div>
</footer><!-- dynamically load mathjax for compatibility with self-contained --><script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script><script type="text/x-mathjax-config">const popovers = document.querySelectorAll('a.footnote-ref[data-toggle="popover"]');
for (let popover of popovers) {
  const div = document.createElement('div');
  div.setAttribute('style', 'position: absolute; top: 0, left:0; width:0, height:0, overflow: hidden; visibility: hidden;');
  div.innerHTML = popover.getAttribute('data-content');

  var has_math = div.querySelector("span.math");
  if (has_math) {
    document.body.appendChild(div);
    MathJax.Hub.Queue(["Typeset", MathJax.Hub, div]);
    MathJax.Hub.Queue(function() {
      popover.setAttribute('data-content', div.innerHTML);
      document.body.removeChild(div);
    })
  }
}
</script>
</body>
</html>
