<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>MB-CDI | PLAY Project: Surveys</title>
<meta name="author" content="Rick Gilmore">
<meta name="description" content="0.2 Purpose This page documents the cleaning and merging procedures related to the MB-CDI data. The home visit workflow strips these files into their own set of CSVs under...">
<meta name="generator" content="bookdown 0.34 with bs4_book()">
<meta property="og:title" content="MB-CDI | PLAY Project: Surveys">
<meta property="og:type" content="book">
<meta property="og:description" content="0.2 Purpose This page documents the cleaning and merging procedures related to the MB-CDI data. The home visit workflow strips these files into their own set of CSVs under...">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="MB-CDI | PLAY Project: Surveys">
<meta name="twitter:description" content="0.2 Purpose This page documents the cleaning and merging procedures related to the MB-CDI data. The home visit workflow strips these files into their own set of CSVs under...">
<!-- JS --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/6.4.6/fuse.js" integrity="sha512-zv6Ywkjyktsohkbp9bb45V6tEMoWhzFzXis+LrMehmJZZSys19Yxf1dopHx7WzIKxr5tK2dVcYmaCk2uqdjF4A==" crossorigin="anonymous"></script><script src="https://kit.fontawesome.com/6ecbd6c532.js" crossorigin="anonymous"></script><script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="libs/bootstrap-4.6.0/bootstrap.min.css" rel="stylesheet">
<script src="libs/bootstrap-4.6.0/bootstrap.bundle.min.js"></script><script src="libs/bs3compat-0.4.2/transition.js"></script><script src="libs/bs3compat-0.4.2/tabs.js"></script><script src="libs/bs3compat-0.4.2/bs3compat.js"></script><link href="libs/bs4_book-1.0.0/bs4_book.css" rel="stylesheet">
<script src="libs/bs4_book-1.0.0/bs4_book.js"></script><script src="libs/kePrint-0.0.1/kePrint.js"></script><link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet">
<script src="https://cdnjs.cloudflare.com/ajax/libs/autocomplete.js/0.38.0/autocomplete.jquery.min.js" integrity="sha512-GU9ayf+66Xx2TmpxqJpliWbT5PiGYxpaG8rfnBEk1LL8l1KGkRShhngwdXK1UgqhAzWpZHSiYPc09/NwDQIGyg==" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/mark.min.js" integrity="sha512-5CYOlHXGh6QpOFA/TeTylKLWfB3ftPsde7AnmhuitiTX4K5SqCLBeKro6sPS8ilsz1Q4NRx3v8Ko2IBiszzdww==" crossorigin="anonymous"></script><!-- CSS --><style type="text/css">
    
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  </style>
<link rel="stylesheet" href="include/css/style.css">
</head>
<body data-spy="scroll" data-target="#toc">

<div class="container-fluid">
<div class="row">
  <header class="col-sm-12 col-lg-3 sidebar sidebar-book"><a class="sr-only sr-only-focusable" href="#content">Skip to main content</a>

    <div class="d-flex align-items-start justify-content-between">
      <h1>
        <a href="index.html" title="">PLAY Project: Surveys</a>
      </h1>
      <button class="btn btn-outline-primary d-lg-none ml-2 mt-1" type="button" data-toggle="collapse" data-target="#main-nav" aria-expanded="true" aria-controls="main-nav"><i class="fas fa-bars"></i><span class="sr-only">Show table of contents</span></button>
    </div>

    <div id="main-nav" class="collapse-lg">
      <form role="search">
        <input id="search" class="form-control" type="search" placeholder="Search" aria-label="Search">
</form>

      <nav aria-label="Table of contents"><h2>Table of contents</h2>
        <ul class="book-toc list-unstyled">
<li><a class="" href="index.html">About</a></li>
<li class="book-part">Tools and Processes</li>
<li><a class="" href="setup.html">Setup</a></li>
<li class="book-part">Data Wrangling</li>
<li><a class="" href="screening-call.html">Screening call</a></li>
<li><a class="" href="home-visit.html">Home visit</a></li>
<li><a class="" href="qa-for-merging.html">QA for merging</a></li>
<li><a class="active" href="mb-cdi.html">MB-CDI</a></li>
<li><a class="" href="post-visit-notes.html">Post-visit notes</a></li>
<li><a class="" href="data-dictionary.html">Data dictionary</a></li>
<li class="book-part">Data Visualization</li>
<li><a class="" href="screening-visualizations.html">Screening visualizations</a></li>
<li><a class="" href="demographics-visualizations.html">Demographics visualizations</a></li>
<li><a class="" href="language-visualizations.html">Language visualizations</a></li>
<li><a class="" href="locomotion-visualizations.html">Locomotion visualizations</a></li>
<li><a class="" href="health-visualizations.html">Health visualizations</a></li>
<li><a class="" href="temperament-visualizations.html">Temperament visualizations</a></li>
<li><a class="" href="post-visit-data.html">Post-visit data</a></li>
<li class="book-part">Project Monitoring</li>
</ul>

        <div class="book-extra">
          <p><a id="book-repo" href="https://github.com/PLAY-behaviorome/KoBoToolbox">View book source <i class="fab fa-github"></i></a></p>
        </div>
      </nav>
</div>
  </header><main class="col-sm-12 col-md-9 col-lg-7" id="content"><div id="mb-cdi" class="section level1 unnumbered">
<h1>MB-CDI<a class="anchor" aria-label="anchor" href="#mb-cdi"><i class="fas fa-link"></i></a>
</h1>
<div id="purpose-2" class="section level2" number="0.2">
<h2>
<span class="header-section-number">0.2</span> Purpose<a class="anchor" aria-label="anchor" href="#purpose-2"><i class="fas fa-link"></i></a>
</h2>
<p>This page documents the cleaning and merging procedures related to the MB-CDI data.
The home visit workflow strips these files into their own set of CSVs under <code>data/csv/home_visit/mbcdi</code>.</p>
</div>
<div id="preparation" class="section level2" number="0.3">
<h2>
<span class="header-section-number">0.3</span> Preparation<a class="anchor" aria-label="anchor" href="#preparation"><i class="fas fa-link"></i></a>
</h2>
<div class="sourceCode" id="cb203"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/source.html">source</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/file.path.html">file.path</a></span><span class="op">(</span><span class="fu">here</span><span class="fu">::</span><span class="fu"><a href="https://here.r-lib.org//reference/here.html">here</a></span><span class="op">(</span><span class="op">)</span>, <span class="st">"R"</span>, <span class="st">"_OLD"</span>, <span class="st">"functions.R"</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<p>Let’s investigate the number of files, records, and variables per file.</p>
<div class="sourceCode" id="cb204"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">mbcdi_fns</span> <span class="op">&lt;-</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/base/list.files.html">list.files</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/file.path.html">file.path</a></span><span class="op">(</span><span class="fu">here</span><span class="fu">::</span><span class="fu"><a href="https://here.r-lib.org//reference/here.html">here</a></span><span class="op">(</span><span class="op">)</span>, <span class="st">"data"</span>, <span class="st">"csv"</span>, <span class="st">"home_visit"</span>, <span class="st">"mbcdi"</span><span class="op">)</span>, <span class="st">"\\.csv$"</span>, full.names <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/length.html">length</a></span><span class="op">(</span><span class="va">mbcdi_fns</span><span class="op">)</span></span></code></pre></div>
<pre><code>## [1] 25</code></pre>
<div class="sourceCode" id="cb206"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">make_datafile_summary</span> <span class="op">&lt;-</span> <span class="kw">function</span><span class="op">(</span><span class="va">csv</span><span class="op">)</span> <span class="op">{</span></span>
<span>  <span class="fu">assertthat</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/assertthat/man/scalar.html">is.string</a></span><span class="op">(</span><span class="va">csv</span><span class="op">)</span></span>
<span>  <span class="fu">assertthat</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/assertthat/man/assertions-file.html">is.readable</a></span><span class="op">(</span><span class="va">csv</span><span class="op">)</span></span>
<span>  </span>
<span>  <span class="va">df</span> <span class="op">&lt;-</span></span>
<span>    <span class="fu">readr</span><span class="fu">::</span><span class="fu"><a href="https://readr.tidyverse.org/reference/read_delim.html">read_csv</a></span><span class="op">(</span><span class="va">csv</span>,</span>
<span>                    col_types <span class="op">=</span> <span class="fu">readr</span><span class="fu">::</span><span class="fu"><a href="https://readr.tidyverse.org/reference/cols.html">cols</a></span><span class="op">(</span>.default <span class="op">=</span> <span class="st">'c'</span><span class="op">)</span>,</span>
<span>                    show_col_types <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span>
<span>  </span>
<span>  </span>
<span>  </span>
<span>  <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span>fn <span class="op">=</span> <span class="va">csv</span>,</span>
<span>             age_group <span class="op">=</span> <span class="fu">extract_age_group_from_name</span><span class="op">(</span><span class="va">csv</span><span class="op">)</span>,</span>
<span>             lang_cond <span class="op">=</span> <span class="fu">form_language</span><span class="op">(</span><span class="va">csv</span><span class="op">)</span>,</span>
<span>             n_subs <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/dim.html">dim</a></span><span class="op">(</span><span class="va">df</span><span class="op">)</span><span class="op">[</span><span class="fl">1</span><span class="op">]</span>,</span>
<span>             n_vars <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/dim.html">dim</a></span><span class="op">(</span><span class="va">df</span><span class="op">)</span><span class="op">[</span><span class="fl">2</span><span class="op">]</span><span class="op">)</span></span>
<span><span class="op">}</span></span></code></pre></div>
<div class="sourceCode" id="cb207"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">mbcdi_file_dat</span> <span class="op">&lt;-</span></span>
<span>  <span class="fu">purrr</span><span class="fu">::</span><span class="fu"><a href="https://purrr.tidyverse.org/reference/map.html">map</a></span><span class="op">(</span><span class="va">mbcdi_fns</span>, <span class="va">make_datafile_summary</span><span class="op">)</span> <span class="op">|&gt;</span> <span class="fu">purrr</span><span class="fu">::</span><span class="fu"><a href="https://purrr.tidyverse.org/reference/list_c.html">list_rbind</a></span><span class="op">(</span><span class="op">)</span></span>
<span></span>
<span><span class="va">mbcdi_file_dat</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu">dplyr</span><span class="fu">::</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/arrange.html">arrange</a></span><span class="op">(</span><span class="va">age_group</span>, <span class="va">lang_cond</span>, <span class="va">n_subs</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu">knitr</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/knitr/man/kable.html">kable</a></span><span class="op">(</span>format <span class="op">=</span> <span class="st">'html'</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu">kableExtra</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/kableExtra/man/kable_classic.html">kable_classic</a></span><span class="op">(</span><span class="op">)</span></span></code></pre></div>
<div class="inline-table"><table class=" lightable-classic" style='font-family: "Arial Narrow", "Source Sans Pro", sans-serif; margin-left: auto; margin-right: auto;'>
<thead><tr>
<th style="text-align:left;">
fn
</th>
<th style="text-align:left;">
age_group
</th>
<th style="text-align:left;">
lang_cond
</th>
<th style="text-align:right;">
n_subs
</th>
<th style="text-align:right;">
n_vars
</th>
</tr></thead>
<tbody>
<tr>
<td style="text-align:left;">
/Users/rog1/rrr/KoBoToolbox/data/csv/home_visit/mbcdi/334099_mbcdi_12_bilingual_english.csv
</td>
<td style="text-align:left;">
12
</td>
<td style="text-align:left;">
bilingual_english
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
728
</td>
</tr>
<tr>
<td style="text-align:left;">
/Users/rog1/rrr/KoBoToolbox/data/csv/home_visit/mbcdi/411456_mbcdi_12_bilingual_english.csv
</td>
<td style="text-align:left;">
12
</td>
<td style="text-align:left;">
bilingual_english
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
715
</td>
</tr>
<tr>
<td style="text-align:left;">
/Users/rog1/rrr/KoBoToolbox/data/csv/home_visit/mbcdi/740623_mbcdi_12_bilingual_english.csv
</td>
<td style="text-align:left;">
12
</td>
<td style="text-align:left;">
bilingual_english
</td>
<td style="text-align:right;">
23
</td>
<td style="text-align:right;">
710
</td>
</tr>
<tr>
<td style="text-align:left;">
/Users/rog1/rrr/KoBoToolbox/data/csv/home_visit/mbcdi/740624_mbcdi_12_bilingual_spanish.csv
</td>
<td style="text-align:left;">
12
</td>
<td style="text-align:left;">
bilingual_spanish
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
710
</td>
</tr>
<tr>
<td style="text-align:left;">
/Users/rog1/rrr/KoBoToolbox/data/csv/home_visit/mbcdi/411469_mbcdi_12_bilingual_spanish.csv
</td>
<td style="text-align:left;">
12
</td>
<td style="text-align:left;">
bilingual_spanish
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
715
</td>
</tr>
<tr>
<td style="text-align:left;">
/Users/rog1/rrr/KoBoToolbox/data/csv/home_visit/mbcdi/331848_mbcdi_12_english.csv
</td>
<td style="text-align:left;">
12
</td>
<td style="text-align:left;">
english
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
254
</td>
</tr>
<tr>
<td style="text-align:left;">
/Users/rog1/rrr/KoBoToolbox/data/csv/home_visit/mbcdi/363431_mbcdi_12_english.csv
</td>
<td style="text-align:left;">
12
</td>
<td style="text-align:left;">
english
</td>
<td style="text-align:right;">
10
</td>
<td style="text-align:right;">
253
</td>
</tr>
<tr>
<td style="text-align:left;">
/Users/rog1/rrr/KoBoToolbox/data/csv/home_visit/mbcdi/740625_mbcdi_12_english.csv
</td>
<td style="text-align:left;">
12
</td>
<td style="text-align:left;">
english
</td>
<td style="text-align:right;">
111
</td>
<td style="text-align:right;">
257
</td>
</tr>
<tr>
<td style="text-align:left;">
/Users/rog1/rrr/KoBoToolbox/data/csv/home_visit/mbcdi/363466_mbcdi_18_bilingual_english.csv
</td>
<td style="text-align:left;">
18
</td>
<td style="text-align:left;">
bilingual_english
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
813
</td>
</tr>
<tr>
<td style="text-align:left;">
/Users/rog1/rrr/KoBoToolbox/data/csv/home_visit/mbcdi/740626_mbcdi_18_bilingual_english.csv
</td>
<td style="text-align:left;">
18
</td>
<td style="text-align:left;">
bilingual_english
</td>
<td style="text-align:right;">
30
</td>
<td style="text-align:right;">
830
</td>
</tr>
<tr>
<td style="text-align:left;">
/Users/rog1/rrr/KoBoToolbox/data/csv/home_visit/mbcdi/411388_mbcdi_18_bilingual_spanish.csv
</td>
<td style="text-align:left;">
18
</td>
<td style="text-align:left;">
bilingual_spanish
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
813
</td>
</tr>
<tr>
<td style="text-align:left;">
/Users/rog1/rrr/KoBoToolbox/data/csv/home_visit/mbcdi/740627_mbcdi_18_bilingual_spanish.csv
</td>
<td style="text-align:left;">
18
</td>
<td style="text-align:left;">
bilingual_spanish
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
830
</td>
</tr>
<tr>
<td style="text-align:left;">
/Users/rog1/rrr/KoBoToolbox/data/csv/home_visit/mbcdi/1136694_mbcdi_18_english.csv
</td>
<td style="text-align:left;">
18
</td>
<td style="text-align:left;">
english
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
357
</td>
</tr>
<tr>
<td style="text-align:left;">
/Users/rog1/rrr/KoBoToolbox/data/csv/home_visit/mbcdi/1151489_mbcdi_18_english.csv
</td>
<td style="text-align:left;">
18
</td>
<td style="text-align:left;">
english
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
357
</td>
</tr>
<tr>
<td style="text-align:left;">
/Users/rog1/rrr/KoBoToolbox/data/csv/home_visit/mbcdi/307736_mbcdi_18_english.csv
</td>
<td style="text-align:left;">
18
</td>
<td style="text-align:left;">
english
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
350
</td>
</tr>
<tr>
<td style="text-align:left;">
/Users/rog1/rrr/KoBoToolbox/data/csv/home_visit/mbcdi/363349_mbcdi_18_english.csv
</td>
<td style="text-align:left;">
18
</td>
<td style="text-align:left;">
english
</td>
<td style="text-align:right;">
9
</td>
<td style="text-align:right;">
350
</td>
</tr>
<tr>
<td style="text-align:left;">
/Users/rog1/rrr/KoBoToolbox/data/csv/home_visit/mbcdi/740628_mbcdi_18_english.csv
</td>
<td style="text-align:left;">
18
</td>
<td style="text-align:left;">
english
</td>
<td style="text-align:right;">
103
</td>
<td style="text-align:right;">
357
</td>
</tr>
<tr>
<td style="text-align:left;">
/Users/rog1/rrr/KoBoToolbox/data/csv/home_visit/mbcdi/363465_mbcdi_24_bilingual_english.csv
</td>
<td style="text-align:left;">
24
</td>
<td style="text-align:left;">
bilingual_english
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
813
</td>
</tr>
<tr>
<td style="text-align:left;">
/Users/rog1/rrr/KoBoToolbox/data/csv/home_visit/mbcdi/740631_mbcdi_24_bilingual_english.csv
</td>
<td style="text-align:left;">
24
</td>
<td style="text-align:left;">
bilingual_english
</td>
<td style="text-align:right;">
26
</td>
<td style="text-align:right;">
830
</td>
</tr>
<tr>
<td style="text-align:left;">
/Users/rog1/rrr/KoBoToolbox/data/csv/home_visit/mbcdi/740630_mbcdi_24_bilingual_spanish.csv
</td>
<td style="text-align:left;">
24
</td>
<td style="text-align:left;">
bilingual_spanish
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
830
</td>
</tr>
<tr>
<td style="text-align:left;">
/Users/rog1/rrr/KoBoToolbox/data/csv/home_visit/mbcdi/408149_mbcdi_24_bilingual_spanish.csv
</td>
<td style="text-align:left;">
24
</td>
<td style="text-align:left;">
bilingual_spanish
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
813
</td>
</tr>
<tr>
<td style="text-align:left;">
/Users/rog1/rrr/KoBoToolbox/data/csv/home_visit/mbcdi/740631_mbcdi_24_bilingual_spanish.csv
</td>
<td style="text-align:left;">
24
</td>
<td style="text-align:left;">
bilingual_spanish
</td>
<td style="text-align:right;">
26
</td>
<td style="text-align:right;">
830
</td>
</tr>
<tr>
<td style="text-align:left;">
/Users/rog1/rrr/KoBoToolbox/data/csv/home_visit/mbcdi/331453_mbcdi_24_english.csv
</td>
<td style="text-align:left;">
24
</td>
<td style="text-align:left;">
english
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
350
</td>
</tr>
<tr>
<td style="text-align:left;">
/Users/rog1/rrr/KoBoToolbox/data/csv/home_visit/mbcdi/363381_mbcdi_24_english.csv
</td>
<td style="text-align:left;">
24
</td>
<td style="text-align:left;">
english
</td>
<td style="text-align:right;">
8
</td>
<td style="text-align:right;">
350
</td>
</tr>
<tr>
<td style="text-align:left;">
/Users/rog1/rrr/KoBoToolbox/data/csv/home_visit/mbcdi/740629_mbcdi_24_english.csv
</td>
<td style="text-align:left;">
24
</td>
<td style="text-align:left;">
english
</td>
<td style="text-align:right;">
89
</td>
<td style="text-align:right;">
357
</td>
</tr>
</tbody>
</table></div>
</div>
<div id="mo-old-english-speakers" class="section level2" number="0.4">
<h2>
<span class="header-section-number">0.4</span> 12-mo-old English speakers<a class="anchor" aria-label="anchor" href="#mo-old-english-speakers"><i class="fas fa-link"></i></a>
</h2>
<p>For simplicity, we’ll start with the youngest age group, and with the English speakers.
There are <span class="math inline">\(n=3\)</span> forms, with 4, 10, and 111 participants each, and 254, 253, and 257 variables.
Just for fun, let’s try to bind them.</p>
<div class="sourceCode" id="cb208"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">eng_12_files</span> <span class="op">&lt;-</span> <span class="va">mbcdi_file_dat</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu">dplyr</span><span class="fu">::</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">age_group</span> <span class="op">==</span> <span class="st">'12'</span>, <span class="va">lang_cond</span> <span class="op">==</span> <span class="st">'english'</span>, <span class="va">n_subs</span> <span class="op">&gt;</span> <span class="fl">0</span><span class="op">)</span></span>
<span></span>
<span><span class="va">eng_12_331</span> <span class="op">&lt;-</span> <span class="fu">readr</span><span class="fu">::</span><span class="fu"><a href="https://readr.tidyverse.org/reference/read_delim.html">read_csv</a></span><span class="op">(</span><span class="va">eng_12_files</span><span class="op">$</span><span class="va">fn</span><span class="op">[</span><span class="fl">1</span><span class="op">]</span>,</span>
<span>                    col_types <span class="op">=</span> <span class="fu">readr</span><span class="fu">::</span><span class="fu"><a href="https://readr.tidyverse.org/reference/cols.html">cols</a></span><span class="op">(</span>.default <span class="op">=</span> <span class="st">'c'</span><span class="op">)</span>,</span>
<span>                    show_col_types <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">eng_12_331</span><span class="op">)</span></span></code></pre></div>
<pre><code>##   [1] "group_combinedquestionnaires/participant_id"                                                                                                       
##   [2] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/note_mcdi_permission"                                                        
##   [3] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_instructions/mcdi_instructions1"                    
##   [4] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_instructions/mcdi_instructions2"                    
##   [5] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_instructions/mcdi_instructions3"                    
##   [6] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_instructions/mcdi_instructions4"                    
##   [7] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_instructions/mcdi_instructions5"                    
##   [8] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_instructions/mcdi_instructions6"                    
##   [9] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsf/mcdi_instructions7"    
##  [10] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsf/choochoo"              
##  [11] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsf/meow"                  
##  [12] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsf/ouch"                  
##  [13] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsf/uhoh"                  
##  [14] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsf/bird"                  
##  [15] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsf/dog"                   
##  [16] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsf/duck"                  
##  [17] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsf/kitty"                 
##  [18] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsf/lion"                  
##  [19] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsf/mouse"                 
##  [20] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsf/car"                   
##  [21] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsf/stroller"              
##  [22] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsf/ball"                  
##  [23] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsf/book"                  
##  [24] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsf/doll"                  
##  [25] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsf/bread"                 
##  [26] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsf/candy"                 
##  [27] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsf/cereal"                
##  [28] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsf/cookie"                
##  [29] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsf/juice"                 
##  [30] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsf/toast"                 
##  [31] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsf/hat"                   
##  [32] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsf/pants"                 
##  [33] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsf/shoe"                  
##  [34] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsf/sock"                  
##  [35] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsf/eye"                   
##  [36] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsf/head"                  
##  [37] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsf/leg"                   
##  [38] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsf/nose"                  
##  [39] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsf/tooth"                 
##  [40] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsf/chair"                 
##  [41] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsf/couch"                 
##  [42] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsf/kitchen"               
##  [43] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsf/table"                 
##  [44] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsf/television"            
##  [45] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsf/blanket"               
##  [46] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsf/bottle"                
##  [47] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsf/cup"                   
##  [48] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsf/dish"                  
##  [49] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsf/lamp"                  
##  [50] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsf/radio"                 
##  [51] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsf/spoon"                 
##  [52] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsf/who"                   
##  [53] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsf/away"                  
##  [54] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsf/outside"               
##  [55] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsf/flower"                
##  [56] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsf/home"                  
##  [57] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsf/moon"                  
##  [58] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsf/outside_001"           
##  [59] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsf/plant"                 
##  [60] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsf/rain"                  
##  [61] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsf/rock"                  
##  [62] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsf/water"                 
##  [63] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsf/babysitter"            
##  [64] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsf/girl"                  
##  [65] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsf/grandma"               
##  [66] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsf/mommy"                 
##  [67] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsf/bath"                  
##  [68] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsf/dont"                  
##  [69] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsf/hi"                    
##  [70] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsf/nightnight"            
##  [71] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsf/pattycake"             
##  [72] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsf/please"                
##  [73] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsf/wait"                  
##  [74] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsf/break"                 
##  [75] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsf/feed"                  
##  [76] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsf/finish"                
##  [77] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsf/help"                  
##  [78] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsf/jump"                  
##  [79] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsf/kick"                  
##  [80] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsf/kiss"                  
##  [81] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsf/push"                  
##  [82] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsf/sing"                  
##  [83] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsf/smile"                 
##  [84] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsf/night"                 
##  [85] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsf/today"                 
##  [86] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsf/allgone"               
##  [87] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsf/big"                   
##  [88] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsf/broken"                
##  [89] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsf/dark"                  
##  [90] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsf/fast"                  
##  [91] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsf/hurt"                  
##  [92] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsf/pretty"                
##  [93] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsf/soft"                  
##  [94] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsf/I"                     
##  [95] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsf/me"                    
##  [96] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsf/how"                   
##  [97] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsf/other"                 
##  [98] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsf/some"                  
##  [99] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsf/comments_mcdi_sfm"     
## [100] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsfm/mcdi_instructions8"   
## [101] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsfm/mcdi_instructions9"   
## [102] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsfm/cockadoodledoo"       
## [103] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsfm/woofwoof"             
## [104] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsfm/yumyum"               
## [105] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsfm/cat"                  
## [106] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsfm/chicken"              
## [107] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsfm/cow"                  
## [108] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsfm/frog"                 
## [109] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsfm/monkey"               
## [110] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsfm/teddybear"            
## [111] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsfm/tiger"                
## [112] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsfm/train"                
## [113] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsfm/truck"                
## [114] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsfm/drum"                 
## [115] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsfm/egg"                  
## [116] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsfm/icecream"             
## [117] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsfm/necklace"             
## [118] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsfm/arms"                 
## [119] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsfm/hand"                 
## [120] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsfm/mouth"                
## [121] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsfm/bathroom"             
## [122] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsfm/bed"                  
## [123] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsfm/sink"                 
## [124] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsfm/broom"                
## [125] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsfm/glass"                
## [126] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsfm/keys"                 
## [127] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsfm/money"                
## [128] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsfm/soap"                 
## [129] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsfm/church"               
## [130] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsfm/party"                
## [131] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsfm/sky"                  
## [132] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsfm/street"               
## [133] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsfm/sun"                  
## [134] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsfm/baby"                 
## [135] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsfm/boy"                  
## [136] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsfm/family"               
## [137] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsfm/lady"                 
## [138] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsfm/bye"                  
## [139] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsfm/goodmorning"          
## [140] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsfm/onetwothree"          
## [141] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsfm/shh"                  
## [142] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsfm/yes"                  
## [143] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsfm/eat"                  
## [144] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsfm/fall"                 
## [145] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsfm/have"                 
## [146] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsfm/look"                 
## [147] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsfm/play"                 
## [148] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsfm/put"                  
## [149] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsfm/say"                  
## [150] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsfm/see"                  
## [151] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsfm/sit"                  
## [152] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsfm/sleep"                
## [153] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsfm/take"                 
## [154] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsfm/want"                 
## [155] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsfm/write"                
## [156] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsfm/now"                  
## [157] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsfm/tomorrow"             
## [158] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsfm/hot"                  
## [159] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsfm/new"                  
## [160] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsfm/tired"                
## [161] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsfm/hisher"               
## [162] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsfm/mine"                 
## [163] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsfm/them"                 
## [164] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsfm/this"                 
## [165] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsfm/a"                    
## [166] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsfm/where"                
## [167] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsfm/here"                 
## [168] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsfm/in"                   
## [169] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsfm/on"                   
## [170] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsfm/there"                
## [171] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsfm/also"                 
## [172] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsfm/many"                 
## [173] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsfm/more"                 
## [174] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsfm/none"                 
## [175] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishsfm/comments_mcdi_sfm_001"
## [176] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/continue_mcdi_englishlfm"                   
## [177] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishlfm/mcdi_instructions10"  
## [178] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishlfm/mcdi_instructions11"  
## [179] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishlfm/baabaa"               
## [180] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishlfm/moo"                  
## [181] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishlfm/quackquack"           
## [182] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishlfm/vroom"                
## [183] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishlfm/beepbeep"             
## [184] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishlfm/bear"                 
## [185] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishlfm/bunny"                
## [186] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishlfm/horse"                
## [187] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishlfm/airplane"             
## [188] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishlfm/bicycle"              
## [189] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishlfm/balloon"              
## [190] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishlfm/pen"                  
## [191] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishlfm/toy"                  
## [192] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishlfm/apple"                
## [193] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishlfm/banana"               
## [194] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishlfm/cake"                 
## [195] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishlfm/cheese"               
## [196] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishlfm/bib"                  
## [197] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishlfm/button"               
## [198] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishlfm/diaper"               
## [199] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishlfm/dress"                
## [200] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishlfm/pajamas"              
## [201] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishlfm/shirt"                
## [202] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishlfm/bellybutton"          
## [203] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishlfm/ears"                 
## [204] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishlfm/face"                 
## [205] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishlfm/foot"                 
## [206] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishlfm/finger"               
## [207] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishlfm/hair"                 
## [208] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishlfm/tongue"               
## [209] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishlfm/bathtub"              
## [210] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishlfm/crib"                 
## [211] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishlfm/door"                 
## [212] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishlfm/drawer"               
## [213] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishlfm/refrigerator"         
## [214] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishlfm/stairs"               
## [215] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishlfm/window"               
## [216] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishlfm/box"                  
## [217] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishlfm/brush"                
## [218] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishlfm/clockwatch"           
## [219] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishlfm/comb"                 
## [220] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishlfm/glasses"              
## [221] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishlfm/light"                
## [222] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishlfm/medicine"             
## [223] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishlfm/paper"                
## [224] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishlfm/picture"              
## [225] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishlfm/pillow"               
## [226] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishlfm/purse"                
## [227] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishlfm/telephone"            
## [228] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishlfm/towel"                
## [229] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishlfm/trash"                
## [230] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishlfm/store"                
## [231] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishlfm/swing"                
## [232] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishlfm/tree"                 
## [233] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishlfm/daddy"                
## [234] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishlfm/man"                  
## [235] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishlfm/mommy_001"            
## [236] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishlfm/nap"                  
## [237] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishlfm/please_001"           
## [238] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishlfm/thankyou"             
## [239] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishlfm/bite"                 
## [240] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishlfm/blow"                 
## [241] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishlfm/close"                
## [242] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishlfm/cry"                  
## [243] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishlfm/dance"                
## [244] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishlfm/give"                 
## [245] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishlfm/go"                   
## [246] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishlfm/hit"                  
## [247] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishlfm/open"                 
## [248] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishlfm/stop"                 
## [249] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishlfm/throw"                
## [250] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishlfm/touch"                
## [251] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishlfm/walk"                 
## [252] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishlfm/wash"                 
## [253] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishlfm/dirty"                
## [254] "group_combinedquestionnaires/group_homevisitquestionnaires/group_mcdi/group_mcdi_12/group_mcdi_english/group_mcdi_englishlfm/comments_mcdi_lfm"</code></pre>
<p>Let’s try trimming the metadata labels.</p>
<div class="sourceCode" id="cb210"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">eng_12_331_trim_names</span> <span class="op">&lt;-</span> </span>
<span>  <span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">eng_12_331</span><span class="op">)</span> <span class="op">|&gt;</span> <span class="fu"><a href="https://rdrr.io/r/base/basename.html">basename</a></span><span class="op">(</span><span class="op">)</span></span>
<span><span class="va">eng_12_331_trim_names</span></span></code></pre></div>
<pre><code>##   [1] "participant_id"           "note_mcdi_permission"    
##   [3] "mcdi_instructions1"       "mcdi_instructions2"      
##   [5] "mcdi_instructions3"       "mcdi_instructions4"      
##   [7] "mcdi_instructions5"       "mcdi_instructions6"      
##   [9] "mcdi_instructions7"       "choochoo"                
##  [11] "meow"                     "ouch"                    
##  [13] "uhoh"                     "bird"                    
##  [15] "dog"                      "duck"                    
##  [17] "kitty"                    "lion"                    
##  [19] "mouse"                    "car"                     
##  [21] "stroller"                 "ball"                    
##  [23] "book"                     "doll"                    
##  [25] "bread"                    "candy"                   
##  [27] "cereal"                   "cookie"                  
##  [29] "juice"                    "toast"                   
##  [31] "hat"                      "pants"                   
##  [33] "shoe"                     "sock"                    
##  [35] "eye"                      "head"                    
##  [37] "leg"                      "nose"                    
##  [39] "tooth"                    "chair"                   
##  [41] "couch"                    "kitchen"                 
##  [43] "table"                    "television"              
##  [45] "blanket"                  "bottle"                  
##  [47] "cup"                      "dish"                    
##  [49] "lamp"                     "radio"                   
##  [51] "spoon"                    "who"                     
##  [53] "away"                     "outside"                 
##  [55] "flower"                   "home"                    
##  [57] "moon"                     "outside_001"             
##  [59] "plant"                    "rain"                    
##  [61] "rock"                     "water"                   
##  [63] "babysitter"               "girl"                    
##  [65] "grandma"                  "mommy"                   
##  [67] "bath"                     "dont"                    
##  [69] "hi"                       "nightnight"              
##  [71] "pattycake"                "please"                  
##  [73] "wait"                     "break"                   
##  [75] "feed"                     "finish"                  
##  [77] "help"                     "jump"                    
##  [79] "kick"                     "kiss"                    
##  [81] "push"                     "sing"                    
##  [83] "smile"                    "night"                   
##  [85] "today"                    "allgone"                 
##  [87] "big"                      "broken"                  
##  [89] "dark"                     "fast"                    
##  [91] "hurt"                     "pretty"                  
##  [93] "soft"                     "I"                       
##  [95] "me"                       "how"                     
##  [97] "other"                    "some"                    
##  [99] "comments_mcdi_sfm"        "mcdi_instructions8"      
## [101] "mcdi_instructions9"       "cockadoodledoo"          
## [103] "woofwoof"                 "yumyum"                  
## [105] "cat"                      "chicken"                 
## [107] "cow"                      "frog"                    
## [109] "monkey"                   "teddybear"               
## [111] "tiger"                    "train"                   
## [113] "truck"                    "drum"                    
## [115] "egg"                      "icecream"                
## [117] "necklace"                 "arms"                    
## [119] "hand"                     "mouth"                   
## [121] "bathroom"                 "bed"                     
## [123] "sink"                     "broom"                   
## [125] "glass"                    "keys"                    
## [127] "money"                    "soap"                    
## [129] "church"                   "party"                   
## [131] "sky"                      "street"                  
## [133] "sun"                      "baby"                    
## [135] "boy"                      "family"                  
## [137] "lady"                     "bye"                     
## [139] "goodmorning"              "onetwothree"             
## [141] "shh"                      "yes"                     
## [143] "eat"                      "fall"                    
## [145] "have"                     "look"                    
## [147] "play"                     "put"                     
## [149] "say"                      "see"                     
## [151] "sit"                      "sleep"                   
## [153] "take"                     "want"                    
## [155] "write"                    "now"                     
## [157] "tomorrow"                 "hot"                     
## [159] "new"                      "tired"                   
## [161] "hisher"                   "mine"                    
## [163] "them"                     "this"                    
## [165] "a"                        "where"                   
## [167] "here"                     "in"                      
## [169] "on"                       "there"                   
## [171] "also"                     "many"                    
## [173] "more"                     "none"                    
## [175] "comments_mcdi_sfm_001"    "continue_mcdi_englishlfm"
## [177] "mcdi_instructions10"      "mcdi_instructions11"     
## [179] "baabaa"                   "moo"                     
## [181] "quackquack"               "vroom"                   
## [183] "beepbeep"                 "bear"                    
## [185] "bunny"                    "horse"                   
## [187] "airplane"                 "bicycle"                 
## [189] "balloon"                  "pen"                     
## [191] "toy"                      "apple"                   
## [193] "banana"                   "cake"                    
## [195] "cheese"                   "bib"                     
## [197] "button"                   "diaper"                  
## [199] "dress"                    "pajamas"                 
## [201] "shirt"                    "bellybutton"             
## [203] "ears"                     "face"                    
## [205] "foot"                     "finger"                  
## [207] "hair"                     "tongue"                  
## [209] "bathtub"                  "crib"                    
## [211] "door"                     "drawer"                  
## [213] "refrigerator"             "stairs"                  
## [215] "window"                   "box"                     
## [217] "brush"                    "clockwatch"              
## [219] "comb"                     "glasses"                 
## [221] "light"                    "medicine"                
## [223] "paper"                    "picture"                 
## [225] "pillow"                   "purse"                   
## [227] "telephone"                "towel"                   
## [229] "trash"                    "store"                   
## [231] "swing"                    "tree"                    
## [233] "daddy"                    "man"                     
## [235] "mommy_001"                "nap"                     
## [237] "please_001"               "thankyou"                
## [239] "bite"                     "blow"                    
## [241] "close"                    "cry"                     
## [243] "dance"                    "give"                    
## [245] "go"                       "hit"                     
## [247] "open"                     "stop"                    
## [249] "throw"                    "touch"                   
## [251] "walk"                     "wash"                    
## [253] "dirty"                    "comments_mcdi_lfm"</code></pre>
<p>That looks better.
Let’s look at the second file.</p>
<div class="sourceCode" id="cb212"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">eng_12_363</span> <span class="op">&lt;-</span> <span class="fu">readr</span><span class="fu">::</span><span class="fu"><a href="https://readr.tidyverse.org/reference/read_delim.html">read_csv</a></span><span class="op">(</span><span class="va">eng_12_files</span><span class="op">$</span><span class="va">fn</span><span class="op">[</span><span class="fl">2</span><span class="op">]</span>,</span>
<span>                    col_types <span class="op">=</span> <span class="fu">readr</span><span class="fu">::</span><span class="fu"><a href="https://readr.tidyverse.org/reference/cols.html">cols</a></span><span class="op">(</span>.default <span class="op">=</span> <span class="st">'c'</span><span class="op">)</span>,</span>
<span>                    show_col_types <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">eng_12_363</span><span class="op">)</span> <span class="op">|&gt;</span> <span class="fu"><a href="https://rdrr.io/r/base/basename.html">basename</a></span><span class="op">(</span><span class="op">)</span></span></code></pre></div>
<pre><code>##   [1] "participant_id"       "note_mcdi_permission" "mcdi_instructions1"  
##   [4] "mcdi_instructions2"   "mcdi_instructions3"   "mcdi_instructions4"  
##   [7] "mcdi_instructions5"   "mcdi_instructions6"   "mcdi_instructions7"  
##  [10] "mcdi_instructions8"   "choochoo"             "meow"                
##  [13] "ouch"                 "uhoh"                 "bird"                
##  [16] "dog"                  "duck"                 "kitty"               
##  [19] "lion"                 "mouse"                "car"                 
##  [22] "stroller"             "ball"                 "book"                
##  [25] "doll"                 "bread"                "candy"               
##  [28] "cereal"               "cookie"               "juice"               
##  [31] "toast"                "hat"                  "pants"               
##  [34] "shoe"                 "sock"                 "eye"                 
##  [37] "head"                 "leg"                  "nose"                
##  [40] "tooth"                "chair"                "couch"               
##  [43] "kitchen"              "table"                "television"          
##  [46] "blanket"              "bottle"               "cup"                 
##  [49] "dish"                 "lamp"                 "radio"               
##  [52] "spoon"                "who"                  "away"                
##  [55] "outside"              "flower"               "home"                
##  [58] "moon"                 "outside_001"          "plant"               
##  [61] "rain"                 "rock"                 "water"               
##  [64] "babysitter"           "girl"                 "grandma"             
##  [67] "mommy"                "bath"                 "dont"                
##  [70] "hi"                   "nightnight"           "pattycake"           
##  [73] "please"               "wait"                 "break"               
##  [76] "feed"                 "finish"               "help"                
##  [79] "jump"                 "kick"                 "kiss"                
##  [82] "push"                 "sing"                 "smile"               
##  [85] "night"                "today"                "allgone"             
##  [88] "big"                  "broken"               "dark"                
##  [91] "fast"                 "hurt"                 "pretty"              
##  [94] "soft"                 "I"                    "me"                  
##  [97] "how"                  "other"                "some"                
## [100] "comments_mcdi_sf"     "mcdi_instructions9"   "mcdi_instructions10" 
## [103] "cockadoodledoo"       "woofwoof"             "yumyum"              
## [106] "cat"                  "chicken"              "cow"                 
## [109] "frog"                 "monkey"               "teddybear"           
## [112] "tiger"                "train"                "truck"               
## [115] "drum"                 "egg"                  "icecream"            
## [118] "necklace"             "arms"                 "hand"                
## [121] "mouth"                "bathroom"             "bed"                 
## [124] "sink"                 "broom"                "glass"               
## [127] "keys"                 "money"                "soap"                
## [130] "church"               "party"                "sky"                 
## [133] "street"               "sun"                  "baby"                
## [136] "boy"                  "family"               "lady"                
## [139] "bath_001"             "bye"                  "goodmorning"         
## [142] "onetwothree"          "shh"                  "yes"                 
## [145] "eat"                  "fall"                 "have"                
## [148] "look"                 "play"                 "put"                 
## [151] "say"                  "see"                  "sit"                 
## [154] "sleep"                "take"                 "want"                
## [157] "write"                "now"                  "tomorrow"            
## [160] "hot"                  "new"                  "tired"               
## [163] "hisher"               "mine"                 "them"                
## [166] "this"                 "a"                    "where"               
## [169] "here"                 "in"                   "on"                  
## [172] "there"                "also"                 "many"                
## [175] "more"                 "none"                 "comments_mcdi_sfm"   
## [178] "mcdi_instructions11"  "mcdi_instructions12"  "baabaa"              
## [181] "moo"                  "quackquack"           "vroom"               
## [184] "beepbeep"             "bear"                 "bunny"               
## [187] "horse"                "airplane"             "bicycle"             
## [190] "balloon"              "pen"                  "toy"                 
## [193] "apple"                "banana"               "cake"                
## [196] "cheese"               "bib"                  "button"              
## [199] "diaper"               "dress"                "pajamas"             
## [202] "shirt"                "bellybutton"          "ears"                
## [205] "face"                 "foot"                 "finger"              
## [208] "hair"                 "tongue"               "bathtub"             
## [211] "crib"                 "door"                 "drawer"              
## [214] "refrigerator"         "stairs"               "window"              
## [217] "box"                  "brush"                "clockwatch"          
## [220] "comb"                 "glasses"              "light"               
## [223] "medicine"             "paper"                "picture"             
## [226] "pillow"               "purse"                "telephone"           
## [229] "towel"                "trash"                "store"               
## [232] "swing"                "tree"                 "daddy"               
## [235] "man"                  "nap"                  "thankyou"            
## [238] "bite"                 "blow"                 "close"               
## [241] "cry"                  "dance"                "give"                
## [244] "go"                   "hit"                  "open"                
## [247] "stop"                 "throw"                "touch"               
## [250] "walk"                 "wash"                 "dirty"               
## [253] "comments_mcdi_lfm"</code></pre>
<p>And the third one.</p>
<div class="sourceCode" id="cb214"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">eng_12_740625</span> <span class="op">&lt;-</span> <span class="fu">readr</span><span class="fu">::</span><span class="fu"><a href="https://readr.tidyverse.org/reference/read_delim.html">read_csv</a></span><span class="op">(</span><span class="va">eng_12_files</span><span class="op">$</span><span class="va">fn</span><span class="op">[</span><span class="fl">3</span><span class="op">]</span>,</span>
<span>                    col_types <span class="op">=</span> <span class="fu">readr</span><span class="fu">::</span><span class="fu"><a href="https://readr.tidyverse.org/reference/cols.html">cols</a></span><span class="op">(</span>.default <span class="op">=</span> <span class="st">'c'</span><span class="op">)</span>,</span>
<span>                    show_col_types <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">eng_12_740625</span><span class="op">)</span> <span class="op">|&gt;</span> <span class="fu"><a href="https://rdrr.io/r/base/basename.html">basename</a></span><span class="op">(</span><span class="op">)</span></span></code></pre></div>
<pre><code>##   [1] "participant_id"                      
##   [2] "note_vocab_mbcdipermission"          
##   [3] "vocab_instructions1"                 
##   [4] "vocab_instructions2"                 
##   [5] "vocab_instructions3"                 
##   [6] "vocab_instructions4"                 
##   [7] "vocab_instructions5"                 
##   [8] "vocab_instructions6"                 
##   [9] "vocab_instructions7"                 
##  [10] "vocab_instructions8"                 
##  [11] "choo_choo"                           
##  [12] "meow"                                
##  [13] "ouch"                                
##  [14] "uh_oh"                               
##  [15] "bird"                                
##  [16] "dog"                                 
##  [17] "duck"                                
##  [18] "kitty"                               
##  [19] "lion"                                
##  [20] "mouse"                               
##  [21] "car"                                 
##  [22] "stroller"                            
##  [23] "ball"                                
##  [24] "book"                                
##  [25] "doll"                                
##  [26] "bread"                               
##  [27] "candy"                               
##  [28] "cereal"                              
##  [29] "cookie"                              
##  [30] "juice"                               
##  [31] "toast"                               
##  [32] "water"                               
##  [33] "hat"                                 
##  [34] "pants"                               
##  [35] "shoe"                                
##  [36] "sock"                                
##  [37] "eye"                                 
##  [38] "head"                                
##  [39] "leg"                                 
##  [40] "nose"                                
##  [41] "tooth"                               
##  [42] "chair"                               
##  [43] "couch"                               
##  [44] "kitchen"                             
##  [45] "table"                               
##  [46] "television"                          
##  [47] "blanket"                             
##  [48] "bottle"                              
##  [49] "cup"                                 
##  [50] "dish"                                
##  [51] "lamp"                                
##  [52] "plant"                               
##  [53] "radio"                               
##  [54] "spoon"                               
##  [55] "flower"                              
##  [56] "home"                                
##  [57] "moon"                                
##  [58] "outside"                             
##  [59] "rain"                                
##  [60] "rock"                                
##  [61] "babysitter"                          
##  [62] "girl"                                
##  [63] "grandma"                             
##  [64] "mommy"                               
##  [65] "bath"                                
##  [66] "dont"                                
##  [67] "hi"                                  
##  [68] "pattycake"                           
##  [69] "nightnight"                          
##  [70] "please"                              
##  [71] "wait"                                
##  [72] "break"                               
##  [73] "feed"                                
##  [74] "finish"                              
##  [75] "help"                                
##  [76] "jump"                                
##  [77] "kick"                                
##  [78] "kiss"                                
##  [79] "push"                                
##  [80] "sing"                                
##  [81] "smile"                               
##  [82] "night"                               
##  [83] "today"                               
##  [84] "allgone"                             
##  [85] "big"                                 
##  [86] "broken"                              
##  [87] "dark"                                
##  [88] "fast"                                
##  [89] "hurt"                                
##  [90] "pretty"                              
##  [91] "soft"                                
##  [92] "i"                                   
##  [93] "me"                                  
##  [94] "how"                                 
##  [95] "who"                                 
##  [96] "away"                                
##  [97] "out"                                 
##  [98] "other"                               
##  [99] "some"                                
## [100] "comments_vocab_english_mbcdi"        
## [101] "vocab_instructions9"                 
## [102] "vocab_instructions10"                
## [103] "cockadoodledoo"                      
## [104] "woofwoof"                            
## [105] "yumyum"                              
## [106] "cat"                                 
## [107] "chicken"                             
## [108] "cow"                                 
## [109] "frog"                                
## [110] "monkey"                              
## [111] "teddybear"                           
## [112] "tiger"                               
## [113] "train"                               
## [114] "truck"                               
## [115] "drum"                                
## [116] "egg"                                 
## [117] "icecream"                            
## [118] "meat"                                
## [119] "milk"                                
## [120] "necklace"                            
## [121] "arms"                                
## [122] "hand"                                
## [123] "mouth"                               
## [124] "bathroom"                            
## [125] "bed"                                 
## [126] "sink"                                
## [127] "broom"                               
## [128] "glass"                               
## [129] "keys"                                
## [130] "money"                               
## [131] "soap"                                
## [132] "church"                              
## [133] "party"                               
## [134] "sky"                                 
## [135] "street"                              
## [136] "sun"                                 
## [137] "baby"                                
## [138] "boy"                                 
## [139] "family"                              
## [140] "lady"                                
## [141] "bye"                                 
## [142] "goodmorning"                         
## [143] "onetwothree"                         
## [144] "shh"                                 
## [145] "yes"                                 
## [146] "eat"                                 
## [147] "fall"                                
## [148] "have"                                
## [149] "look"                                
## [150] "play"                                
## [151] "put"                                 
## [152] "see"                                 
## [153] "sit"                                 
## [154] "sleep"                               
## [155] "take"                                
## [156] "want"                                
## [157] "write"                               
## [158] "be"                                  
## [159] "now"                                 
## [160] "tomorrow"                            
## [161] "dirty"                               
## [162] "hot"                                 
## [163] "new"                                 
## [164] "tired"                               
## [165] "hisher"                              
## [166] "mine"                                
## [167] "them"                                
## [168] "this"                                
## [169] "a"                                   
## [170] "where"                               
## [171] "for"                                 
## [172] "here"                                
## [173] "in"                                  
## [174] "on"                                  
## [175] "there"                               
## [176] "also"                                
## [177] "many"                                
## [178] "more"                                
## [179] "none"                                
## [180] "comments_vocab_english_dllesshort"   
## [181] "vocab_instructions11"                
## [182] "vocab_instructions12"                
## [183] "baabaa"                              
## [184] "quackquack"                          
## [185] "vroom"                               
## [186] "vocab_instructions13"                
## [187] "animal"                              
## [188] "bear"                                
## [189] "bunny"                               
## [190] "elephant"                            
## [191] "horse"                               
## [192] "penguin"                             
## [193] "squirrel"                            
## [194] "turtle"                              
## [195] "airplane"                            
## [196] "bicycle"                             
## [197] "balloon"                             
## [198] "firetruck"                           
## [199] "pen"                                 
## [200] "toy"                                 
## [201] "cake"                                
## [202] "bib"                                 
## [203] "button"                              
## [204] "diaper"                              
## [205] "dress"                               
## [206] "pajamas"                             
## [207] "foot"                                
## [208] "finger"                              
## [209] "hair"                                
## [210] "tongue"                              
## [211] "bathtub"                             
## [212] "door"                                
## [213] "refrigerator"                        
## [214] "stairs"                              
## [215] "window"                              
## [216] "box"                                 
## [217] "boots"                               
## [218] "brush"                               
## [219] "clockwatch"                          
## [220] "comb"                                
## [221] "glasses"                             
## [222] "hammer"                              
## [223] "light"                               
## [224] "medicine"                            
## [225] "paper"                               
## [226] "picture"                             
## [227] "pillow"                              
## [228] "purse"                               
## [229] "telelphone"                          
## [230] "towel"                               
## [231] "trash"                               
## [232] "scissors"                            
## [233] "store"                               
## [234] "tree"                                
## [235] "brother"                             
## [236] "daddy"                               
## [237] "grandpa"                             
## [238] "man"                                 
## [239] "sister"                              
## [240] "thankyou"                            
## [241] "tickle"                              
## [242] "bite"                                
## [243] "blow"                                
## [244] "close"                               
## [245] "cry"                                 
## [246] "dance"                               
## [247] "draw"                                
## [248] "go"                                  
## [249] "hit"                                 
## [250] "hurry"                               
## [251] "open"                                
## [252] "say"                                 
## [253] "throw"                               
## [254] "touch"                               
## [255] "walk"                                
## [256] "wash"                                
## [257] "comments_vocab_english_dllesextended"</code></pre>
<p>Now, we’ll create a function to clean the variable names.</p>
<div class="sourceCode" id="cb216"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">select_basename</span> <span class="op">&lt;-</span> <span class="kw">function</span><span class="op">(</span><span class="va">csv_fn</span><span class="op">)</span> <span class="op">{</span></span>
<span>  <span class="fu">assertthat</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/assertthat/man/scalar.html">is.string</a></span><span class="op">(</span><span class="va">csv_fn</span><span class="op">)</span></span>
<span>  <span class="fu">assertthat</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/assertthat/man/assertions-file.html">is.readable</a></span><span class="op">(</span><span class="va">csv_fn</span><span class="op">)</span></span>
<span>  </span>
<span>  <span class="va">df</span> <span class="op">&lt;-</span> <span class="fu">readr</span><span class="fu">::</span><span class="fu"><a href="https://readr.tidyverse.org/reference/read_delim.html">read_csv</a></span><span class="op">(</span><span class="va">csv_fn</span>,</span>
<span>                    col_types <span class="op">=</span> <span class="fu">readr</span><span class="fu">::</span><span class="fu"><a href="https://readr.tidyverse.org/reference/cols.html">cols</a></span><span class="op">(</span>.default <span class="op">=</span> <span class="st">'c'</span><span class="op">)</span>,</span>
<span>                    show_col_types <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span>
<span>  </span>
<span>  <span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">df</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/basename.html">basename</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">df</span><span class="op">)</span><span class="op">)</span></span>
<span>  <span class="va">df</span></span>
<span><span class="op">}</span></span></code></pre></div>
<div class="sourceCode" id="cb217"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu">select_basename</span><span class="op">(</span><span class="va">eng_12_files</span><span class="op">$</span><span class="va">fn</span><span class="op">[</span><span class="fl">3</span><span class="op">]</span><span class="op">)</span></span></code></pre></div>
<pre><code>## # A tibble: 111 × 257
##    participant_id note_vocab_mbcdipermission vocab_instructions1
##    &lt;chr&gt;          &lt;chr&gt;                      &lt;chr&gt;              
##  1 e0N0S0S1A      &lt;NA&gt;                       &lt;NA&gt;               
##  2 e0N6T0S1A      &lt;NA&gt;                       &lt;NA&gt;               
##  3 a9L2M0A2A      &lt;NA&gt;                       &lt;NA&gt;               
##  4 o2C0C1C2A      &lt;NA&gt;                       &lt;NA&gt;               
##  5 o2C0A1C2A      &lt;NA&gt;                       &lt;NA&gt;               
##  6 a3W4N1F0A      &lt;NA&gt;                       &lt;NA&gt;               
##  7 l3S3A1L1A      &lt;NA&gt;                       &lt;NA&gt;               
##  8 o4C9K1M0A      &lt;NA&gt;                       &lt;NA&gt;               
##  9 o4C3O1H0A      &lt;NA&gt;                       &lt;NA&gt;               
## 10 a4S2B1P0A      &lt;NA&gt;                       &lt;NA&gt;               
## # ℹ 101 more rows
## # ℹ 254 more variables: vocab_instructions2 &lt;chr&gt;, vocab_instructions3 &lt;chr&gt;,
## #   vocab_instructions4 &lt;chr&gt;, vocab_instructions5 &lt;chr&gt;,
## #   vocab_instructions6 &lt;chr&gt;, vocab_instructions7 &lt;chr&gt;,
## #   vocab_instructions8 &lt;chr&gt;, choo_choo &lt;chr&gt;, meow &lt;chr&gt;, ouch &lt;chr&gt;,
## #   uh_oh &lt;chr&gt;, bird &lt;chr&gt;, dog &lt;chr&gt;, duck &lt;chr&gt;, kitty &lt;chr&gt;, lion &lt;chr&gt;,
## #   mouse &lt;chr&gt;, car &lt;chr&gt;, stroller &lt;chr&gt;, ball &lt;chr&gt;, book &lt;chr&gt;, …</code></pre>
<p>Let’s trim unneeded fields.</p>
<div class="sourceCode" id="cb219"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">trim_cdi_fields</span> <span class="op">&lt;-</span> <span class="kw">function</span><span class="op">(</span><span class="va">df</span><span class="op">)</span> <span class="op">{</span></span>
<span>  <span class="va">df</span> <span class="op">|&gt;</span></span>
<span>    <span class="fu">dplyr</span><span class="fu">::</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="op">-</span><span class="fu"><a href="https://tidyselect.r-lib.org/reference/starts_with.html">contains</a></span><span class="op">(</span><span class="st">"note"</span><span class="op">)</span>,</span>
<span>                  <span class="op">-</span><span class="fu"><a href="https://tidyselect.r-lib.org/reference/starts_with.html">contains</a></span><span class="op">(</span><span class="st">"instructions"</span><span class="op">)</span>,</span>
<span>                  <span class="op">-</span><span class="fu"><a href="https://tidyselect.r-lib.org/reference/starts_with.html">contains</a></span><span class="op">(</span><span class="st">"comments"</span><span class="op">)</span>,</span>
<span>                  <span class="op">-</span><span class="fu"><a href="https://tidyselect.r-lib.org/reference/starts_with.html">contains</a></span><span class="op">(</span><span class="st">"continue"</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="op">}</span></span>
<span></span>
<span><span class="va">add_particip_index</span> <span class="op">&lt;-</span> <span class="kw">function</span><span class="op">(</span><span class="va">df</span><span class="op">)</span> <span class="op">{</span></span>
<span>  <span class="va">df</span> <span class="op">|&gt;</span> </span>
<span>    <span class="fu">dplyr</span><span class="fu">::</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>play_i <span class="op">=</span> <span class="fl">1</span><span class="op">:</span><span class="fu"><a href="https://rdrr.io/r/base/dim.html">dim</a></span><span class="op">(</span><span class="va">df</span><span class="op">)</span><span class="op">[</span><span class="fl">1</span><span class="op">]</span><span class="op">)</span></span>
<span><span class="op">}</span></span>
<span></span>
<span><span class="va">make_cdi_longer</span> <span class="op">&lt;-</span> <span class="kw">function</span><span class="op">(</span><span class="va">df</span><span class="op">)</span> <span class="op">{</span></span>
<span>  <span class="va">n_vars</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/dim.html">dim</a></span><span class="op">(</span><span class="va">df</span><span class="op">)</span><span class="op">[</span><span class="fl">2</span><span class="op">]</span></span>
<span>  <span class="va">df</span> <span class="op">|&gt;</span></span>
<span>    <span class="fu">tidyr</span><span class="fu">::</span><span class="fu"><a href="https://tidyr.tidyverse.org/reference/pivot_longer.html">pivot_longer</a></span><span class="op">(</span>cols <span class="op">=</span> <span class="fl">2</span><span class="op">:</span><span class="va">n_vars</span>,</span>
<span>                        names_to <span class="op">=</span> <span class="st">"word"</span>,</span>
<span>                        values_to <span class="op">=</span> <span class="st">"understands_or_says"</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>    <span class="fu">dplyr</span><span class="fu">::</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="op">!</span><span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">understands_or_says</span><span class="op">)</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>    <span class="co"># dplyr::mutate(</span></span>
<span>    <span class="co">#   understands_or_says = stringr::str_replace(understands_or_says, "understands[_]+", "says")</span></span>
<span>    <span class="co"># ) |&gt;</span></span>
<span>    <span class="co"># dplyr::mutate(understands_or_says, stringr::str_replace(understands_or_says, "sayssays", "says")) |&gt;</span></span>
<span>    <span class="fu">dplyr</span><span class="fu">::</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>word <span class="op">=</span> <span class="fu">stringr</span><span class="fu">::</span><span class="fu"><a href="https://stringr.tidyverse.org/reference/str_replace.html">str_replace</a></span><span class="op">(</span><span class="va">word</span>, <span class="st">"mommy_001"</span>, <span class="st">"mommy"</span><span class="op">)</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>    <span class="fu">dplyr</span><span class="fu">::</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>word <span class="op">=</span> <span class="fu">stringr</span><span class="fu">::</span><span class="fu"><a href="https://stringr.tidyverse.org/reference/str_replace.html">str_replace</a></span><span class="op">(</span><span class="va">word</span>, <span class="st">"bath_001"</span>, <span class="st">"bath"</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="op">}</span></span></code></pre></div>
<div class="sourceCode" id="cb220"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">clean_cdi</span> <span class="op">&lt;-</span> <span class="kw">function</span><span class="op">(</span><span class="va">csv_fn</span><span class="op">)</span> <span class="op">{</span></span>
<span>  <span class="fu">select_basename</span><span class="op">(</span><span class="va">csv_fn</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>    <span class="fu">trim_cdi_fields</span><span class="op">(</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>    <span class="fu">dplyr</span><span class="fu">::</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/rename.html">rename</a></span><span class="op">(</span><span class="st">"play_id"</span> <span class="op">=</span> <span class="st">"participant_id"</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>    <span class="fu">make_cdi_longer</span><span class="op">(</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>    <span class="fu">add_particip_index</span><span class="op">(</span><span class="op">)</span></span>
<span><span class="op">}</span></span></code></pre></div>
<div class="sourceCode" id="cb221"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">eng_12_1</span> <span class="op">&lt;-</span> <span class="fu">clean_cdi</span><span class="op">(</span><span class="va">eng_12_files</span><span class="op">$</span><span class="va">fn</span><span class="op">[</span><span class="fl">1</span><span class="op">]</span><span class="op">)</span></span></code></pre></div>
<pre><code>## Warning: Using an external vector in selections was deprecated in tidyselect 1.1.0.
## ℹ Please use `all_of()` or `any_of()` instead.
##   # Was:
##   data %&gt;% select(n_vars)
## 
##   # Now:
##   data %&gt;% select(all_of(n_vars))
## 
## See &lt;https://tidyselect.r-lib.org/reference/faq-external-vector.html&gt;.
## This warning is displayed once every 8 hours.
## Call `lifecycle::last_lifecycle_warnings()` to see where this warning was
## generated.</code></pre>
<div class="sourceCode" id="cb223"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/xtabs.html">xtabs</a></span><span class="op">(</span><span class="op">~</span> <span class="va">word</span> <span class="op">+</span> <span class="va">understands_or_says</span>, <span class="va">eng_12_1</span><span class="op">)</span></span></code></pre></div>
<pre><code>##              understands_or_says
## word          understands understands___
##   arms                  1              0
##   baby                  1              0
##   bath                  1              0
##   bathroom              1              0
##   bed                   1              0
##   bellybutton           1              0
##   blanket               1              0
##   blow                  1              0
##   book                  1              0
##   box                   1              0
##   button                1              0
##   bye                   0              1
##   couch                 1              0
##   crib                  1              0
##   daddy                 0              1
##   dance                 1              0
##   diaper                1              0
##   dog                   0              1
##   dont                  1              0
##   door                  1              0
##   drawer                1              0
##   dress                 1              0
##   drum                  1              0
##   eat                   1              0
##   egg                   1              0
##   feed                  1              0
##   finish                0              1
##   foot                  1              0
##   frog                  1              0
##   goodmorning           1              0
##   hand                  1              0
##   have                  1              0
##   here                  1              0
##   hi                    1              0
##   hot                   1              0
##   icecream              1              0
##   in                    1              0
##   keys                  1              0
##   look                  1              0
##   mine                  1              0
##   mommy                 0              2
##   monkey                1              0
##   more                  1              0
##   mouth                 1              0
##   nap                   1              0
##   nose                  1              0
##   now                   1              0
##   onetwothree           1              0
##   open                  1              0
##   pattycake             1              0
##   play                  1              0
##   please                1              0
##   put                   1              0
##   say                   1              0
##   see                   1              0
##   shh                   1              0
##   shirt                 1              0
##   sing                  1              0
##   sink                  1              0
##   sit                   1              0
##   sleep                 1              0
##   stairs                1              0
##   stop                  1              0
##   stroller              1              0
##   take                  1              0
##   teddybear             1              0
##   this                  1              0
##   tiger                 1              0
##   tired                 1              0
##   touch                 1              0
##   uhoh                  1              0
##   wait                  1              0
##   want                  1              0
##   water                 1              0
##   where                 1              0
##   woofwoof              0              1
##   yes                   1              0
##   yumyum                0              1</code></pre>
<div class="sourceCode" id="cb225"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">eng_12_2</span> <span class="op">&lt;-</span> <span class="fu">clean_cdi</span><span class="op">(</span><span class="va">eng_12_files</span><span class="op">$</span><span class="va">fn</span><span class="op">[</span><span class="fl">2</span><span class="op">]</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/xtabs.html">xtabs</a></span><span class="op">(</span><span class="op">~</span> <span class="va">word</span> <span class="op">+</span> <span class="va">understands_or_says</span>, <span class="va">eng_12_2</span><span class="op">)</span></span></code></pre></div>
<pre><code>##               understands_or_says
## word           understands understands_says
##   allgone                3                0
##   apple                  2                0
##   arms                   1                0
##   baby                   4                0
##   ball                   3                2
##   balloon                0                1
##   banana                 2                0
##   bath                   9                0
##   bathroom               2                0
##   bathtub                1                0
##   bed                    1                0
##   bellybutton            1                0
##   bib                    1                0
##   big                    1                0
##   blanket                2                0
##   blow                   2                0
##   book                   8                1
##   bottle                 6                1
##   boy                    1                0
##   brush                  1                0
##   button                 1                0
##   bye                    3                4
##   car                    3                0
##   cereal                 1                0
##   cheese                 1                0
##   choochoo               1                0
##   close                  1                0
##   comb                   1                0
##   cookie                 1                0
##   couch                  1                0
##   crib                   2                0
##   cry                    1                0
##   cup                    3                0
##   daddy                  2                5
##   dance                  2                0
##   diaper                 2                0
##   dirty                  1                0
##   dog                    3                1
##   doll                   1                0
##   dont                   4                0
##   door                   2                0
##   drawer                 1                0
##   dress                  2                0
##   drum                   2                0
##   duck                   1                0
##   eat                    4                0
##   egg                    1                0
##   eye                    2                0
##   face                   1                0
##   fast                   1                0
##   feed                   2                0
##   finish                 2                1
##   flower                 2                0
##   foot                   2                0
##   frog                   1                0
##   give                   1                0
##   go                     1                0
##   goodmorning            1                0
##   grandma                2                0
##   hair                   1                0
##   hand                   1                0
##   hat                    1                0
##   have                   1                0
##   head                   1                0
##   help                   1                0
##   here                   1                0
##   hi                     5                4
##   hisher                 1                0
##   hit                    1                0
##   home                   2                0
##   hot                    1                0
##   hurt                   1                0
##   I                      1                0
##   icecream               1                0
##   in                     2                0
##   jump                   2                0
##   keys                   1                0
##   kick                   1                0
##   kiss                   3                0
##   kitchen                1                0
##   kitty                  3                0
##   look                   1                0
##   man                    0                1
##   meow                   2                0
##   mine                   2                0
##   mommy                  2                8
##   monkey                 2                0
##   moo                    1                0
##   more                   2                1
##   mouth                  1                0
##   nap                    2                0
##   night                  1                0
##   nightnight             1                0
##   nose                   3                0
##   now                    1                0
##   onetwothree            2                0
##   open                   2                0
##   ouch                   2                0
##   outside                1                0
##   pajamas                1                0
##   pants                  1                0
##   pattycake              3                0
##   pen                    1                0
##   picture                1                0
##   play                   2                0
##   please                 1                0
##   purse                  1                0
##   put                    1                0
##   quackquack             1                0
##   refrigerator           1                0
##   say                    2                0
##   see                    2                0
##   shh                    3                0
##   shirt                  2                0
##   shoe                   1                0
##   sing                   2                0
##   sink                   1                0
##   sit                    1                0
##   sleep                  1                0
##   smile                  1                0
##   sock                   3                0
##   soft                   2                0
##   spoon                  5                0
##   stairs                 2                0
##   stop                   3                0
##   stroller               4                0
##   swing                  1                0
##   table                  2                0
##   take                   1                0
##   teddybear              2                0
##   telephone              1                0
##   thankyou               1                0
##   this                   1                0
##   throw                  1                0
##   tiger                  1                0
##   tired                  2                0
##   tongue                 1                0
##   tooth                  1                0
##   toy                    1                0
##   trash                  1                0
##   uhoh                   6                2
##   vroom                  1                0
##   wait                   5                0
##   walk                   1                0
##   want                   1                0
##   wash                   1                0
##   water                  6                0
##   where                  1                0
##   woofwoof               1                2
##   yes                    3                0
##   yumyum                 2                2</code></pre>
<div class="sourceCode" id="cb227"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">eng_12_3</span> <span class="op">&lt;-</span> <span class="fu">clean_cdi</span><span class="op">(</span><span class="va">eng_12_files</span><span class="op">$</span><span class="va">fn</span><span class="op">[</span><span class="fl">3</span><span class="op">]</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/xtabs.html">xtabs</a></span><span class="op">(</span><span class="op">~</span> <span class="va">word</span> <span class="op">+</span> <span class="va">understands_or_says</span>, <span class="va">eng_12_3</span><span class="op">)</span></span></code></pre></div>
<pre><code>##                 understands_or_says
## word             understands understands_says
##   a                        3                0
##   airplane                16                0
##   allgone                 52                5
##   also                     2                0
##   animal                  10                0
##   arms                    18                0
##   away                     5                0
##   baabaa                   8               14
##   baby                    48                4
##   babysitter               2                0
##   ball                    56               10
##   balloon                 18                5
##   bath                    58                2
##   bathroom                16                0
##   bathtub                 42                0
##   bear                    16                1
##   bed                     39                0
##   bib                     38                0
##   bicycle                 11                0
##   big                     14                1
##   bird                    20                0
##   bite                    27                0
##   blanket                 19                0
##   blow                    15                0
##   book                    51                9
##   boots                    4                0
##   bottle                  46               20
##   box                     16                1
##   boy                     10                0
##   bread                   10                0
##   break                    1                0
##   broken                   2                0
##   broom                    8                0
##   brother                 16                3
##   brush                   22                1
##   bunny                   22                0
##   button                   6                1
##   bye                     57               26
##   cake                     7                0
##   candy                    1                0
##   car                     32                3
##   cat                     28               12
##   cereal                   8                1
##   chair                   18                0
##   chicken                 13                1
##   choo_choo                3                2
##   church                   7                0
##   clockwatch              10                0
##   close                   27                0
##   cockadoodledoo           3                2
##   comb                     7                0
##   cookie                   9                0
##   couch                   17                0
##   cow                     15                4
##   cry                     25                0
##   cup                     35                2
##   daddy                   24               58
##   dance                   45                0
##   dark                     6                0
##   diaper                  50                2
##   dirty                   17                0
##   dish                     1                0
##   dog                     35               21
##   doll                    16                0
##   dont                    34                1
##   door                    28                2
##   draw                     6                0
##   dress                    9                0
##   drum                    19                0
##   duck                    17                2
##   eat                     65                2
##   egg                     27                1
##   elephant                17                0
##   eye                     23                2
##   fall                    11                0
##   family                  11                0
##   fast                    10                0
##   feed                    11                0
##   finger                  24                0
##   finish                  13                2
##   firetruck                8                0
##   flower                  14                0
##   foot                    34                0
##   for                      1                0
##   frog                    10                0
##   girl                     6                0
##   glass                    2                0
##   glasses                 25                1
##   go                      27                5
##   goodmorning             39                0
##   grandma                 42                8
##   grandpa                 35               10
##   hair                    35                0
##   hammer                   3                0
##   hand                    35                0
##   hat                     20                3
##   have                     8                0
##   head                    24                0
##   help                    22                0
##   here                    18                0
##   hi                      48               31
##   hisher                   4                0
##   hit                     17                0
##   home                    23                0
##   horse                   12                0
##   hot                     30                2
##   hurry                    1                0
##   hurt                    14                0
##   i                        6                1
##   icecream                 9                0
##   in                      32                1
##   juice                    2                0
##   jump                    16                0
##   keys                    19                0
##   kick                    12                0
##   kiss                    54                1
##   kitchen                 17                0
##   kitty                   28                7
##   lady                     3                0
##   lamp                     2                0
##   leg                     13                0
##   light                   25                3
##   lion                     9                1
##   look                    47                1
##   man                      2                0
##   many                     4                0
##   me                       8                0
##   meat                     6                0
##   medicine                14                0
##   meow                    24                6
##   milk                    51                8
##   mine                    11                0
##   mommy                   31               52
##   money                    3                0
##   monkey                  14                0
##   moon                     6                1
##   more                    40               10
##   mouse                    3                0
##   mouth                   32                2
##   necklace                 5                0
##   new                      1                0
##   night                   23                2
##   nightnight              43                5
##   none                     8                0
##   nose                    29                1
##   now                      7                0
##   on                      25                2
##   onetwothree             23                0
##   open                    41                0
##   other                    3                0
##   ouch                    28                2
##   out                     21                0
##   outside                 48                0
##   pajamas                 26                0
##   pants                   17                1
##   paper                   10                0
##   party                    6                0
##   pattycake               21                0
##   pen                      8                0
##   penguin                  9                0
##   picture                 17                0
##   pillow                  20                0
##   plant                    9                0
##   play                    38                1
##   please                  18                1
##   pretty                   6                0
##   purse                    4                0
##   push                    23                0
##   put                     37                0
##   quackquack              10                7
##   rain                     4                0
##   refrigerator            14                0
##   rock                     6                1
##   say                     11                0
##   scissors                 1                0
##   see                     26                0
##   shh                     46                5
##   shoe                    36                1
##   sing                    16                0
##   sink                     4                0
##   sister                  15                1
##   sit                     35                0
##   sky                     14                0
##   sleep                   45                0
##   smile                   28                1
##   soap                    11                0
##   sock                    28                1
##   soft                    20                0
##   some                     3                0
##   spoon                   30                0
##   squirrel                12                0
##   stairs                  31                0
##   store                    6                0
##   street                   6                0
##   stroller                25                0
##   sun                     14                1
##   table                   15                0
##   take                    18                0
##   teddybear               18                0
##   telelphone              28                0
##   television              10                0
##   thankyou                38                4
##   them                     1                0
##   there                   15                1
##   this                    11                2
##   throw                   31                0
##   tickle                  28                2
##   tiger                    7                2
##   tired                   35                0
##   toast                    5                0
##   today                    2                0
##   tomorrow                 2                0
##   tongue                  21                0
##   tooth                   12                1
##   touch                   28                0
##   towel                   17                0
##   toy                     51                0
##   train                    7                1
##   trash                   14                0
##   tree                    20                2
##   truck                   27                2
##   turtle                  12                1
##   uh_oh                   44               18
##   vroom                   10               16
##   wait                    26                0
##   walk                    38                0
##   want                    17                0
##   wash                    18                0
##   water                   51                7
##   where                   31                0
##   who                     13                0
##   window                  21                0
##   woofwoof                30               13
##   write                    2                0
##   yes                     49                7
##   yumyum                  35                8</code></pre>

</div>
</div>
  <div class="chapter-nav">
<div class="prev"><a href="qa-for-merging.html">QA for merging</a></div>
<div class="next"><a href="post-visit-notes.html">Post-visit notes</a></div>
</div></main><div class="col-md-3 col-lg-2 d-none d-md-block sidebar sidebar-chapter">
    <nav id="toc" data-toggle="toc" aria-label="On this page"><h2>On this page</h2>
      <ul class="nav navbar-nav">
<li><a class="nav-link" href="#mb-cdi">MB-CDI</a></li>
<li><a class="nav-link" href="#purpose-2"><span class="header-section-number">0.2</span> Purpose</a></li>
<li><a class="nav-link" href="#preparation"><span class="header-section-number">0.3</span> Preparation</a></li>
<li><a class="nav-link" href="#mo-old-english-speakers"><span class="header-section-number">0.4</span> 12-mo-old English speakers</a></li>
</ul>

      <div class="book-extra">
        <ul class="list-unstyled">
<li><a id="book-source" href="https://github.com/PLAY-behaviorome/KoBoToolbox/blob/main/15-mb-cdi.Rmd">View source <i class="fab fa-github"></i></a></li>
          <li><a id="book-edit" href="https://github.com/PLAY-behaviorome/KoBoToolbox/edit/main/15-mb-cdi.Rmd">Edit this page <i class="fab fa-github"></i></a></li>
        </ul>
</div>
    </nav>
</div>

</div>
</div> <!-- .container -->

<footer class="bg-primary text-light mt-5"><div class="container"><div class="row">

  <div class="col-12 col-md-6 mt-3">
    <p>"<strong>PLAY Project: Surveys</strong>" was written by Rick Gilmore. It was last built on 2023-10-24.</p>
  </div>

  <div class="col-12 col-md-6 mt-3">
    <p>This book was built by the <a class="text-light" href="https://bookdown.org">bookdown</a> R package.</p>
  </div>

</div></div>
</footer><!-- dynamically load mathjax for compatibility with self-contained --><script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script><script type="text/x-mathjax-config">const popovers = document.querySelectorAll('a.footnote-ref[data-toggle="popover"]');
for (let popover of popovers) {
  const div = document.createElement('div');
  div.setAttribute('style', 'position: absolute; top: 0, left:0; width:0, height:0, overflow: hidden; visibility: hidden;');
  div.innerHTML = popover.getAttribute('data-content');

  var has_math = div.querySelector("span.math");
  if (has_math) {
    document.body.appendChild(div);
    MathJax.Hub.Queue(["Typeset", MathJax.Hub, div]);
    MathJax.Hub.Queue(function() {
      popover.setAttribute('data-content', div.innerHTML);
      document.body.removeChild(div);
    })
  }
}
</script>
</body>
</html>
