<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Screening call | PLAY Project: Survey protocol</title>
<meta name="author" content="Rick Gilmore">
<meta name="generator" content="bookdown 0.29 with bs4_book()">
<meta property="og:title" content="Screening call | PLAY Project: Survey protocol">
<meta property="og:type" content="book">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="Screening call | PLAY Project: Survey protocol">
<!-- JS --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/6.4.6/fuse.js" integrity="sha512-zv6Ywkjyktsohkbp9bb45V6tEMoWhzFzXis+LrMehmJZZSys19Yxf1dopHx7WzIKxr5tK2dVcYmaCk2uqdjF4A==" crossorigin="anonymous"></script><script src="https://kit.fontawesome.com/6ecbd6c532.js" crossorigin="anonymous"></script><script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="libs/bootstrap-4.6.0/bootstrap.min.css" rel="stylesheet">
<script src="libs/bootstrap-4.6.0/bootstrap.bundle.min.js"></script><script src="libs/bs3compat-0.4.0/transition.js"></script><script src="libs/bs3compat-0.4.0/tabs.js"></script><script src="libs/bs3compat-0.4.0/bs3compat.js"></script><link href="libs/bs4_book-1.0.0/bs4_book.css" rel="stylesheet">
<script src="libs/bs4_book-1.0.0/bs4_book.js"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/autocomplete.js/0.38.0/autocomplete.jquery.min.js" integrity="sha512-GU9ayf+66Xx2TmpxqJpliWbT5PiGYxpaG8rfnBEk1LL8l1KGkRShhngwdXK1UgqhAzWpZHSiYPc09/NwDQIGyg==" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/mark.min.js" integrity="sha512-5CYOlHXGh6QpOFA/TeTylKLWfB3ftPsde7AnmhuitiTX4K5SqCLBeKro6sPS8ilsz1Q4NRx3v8Ko2IBiszzdww==" crossorigin="anonymous"></script><!-- CSS --><style type="text/css">
    
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  </style>
<link rel="stylesheet" href="include/css/style.css">
<meta name="description" content="Collection protocol Details about the data collection protocol for participant screening and recruiting can be found on the PLAY Project website.  Retrieve files from KoBoToolbox The relevant...">
<meta property="og:description" content="Collection protocol Details about the data collection protocol for participant screening and recruiting can be found on the PLAY Project website.  Retrieve files from KoBoToolbox The relevant...">
<meta name="twitter:description" content="Collection protocol Details about the data collection protocol for participant screening and recruiting can be found on the PLAY Project website.  Retrieve files from KoBoToolbox The relevant...">
</head>
<body data-spy="scroll" data-target="#toc">

<div class="container-fluid">
<div class="row">
  <header class="col-sm-12 col-lg-3 sidebar sidebar-book"><a class="sr-only sr-only-focusable" href="#content">Skip to main content</a>

    <div class="d-flex align-items-start justify-content-between">
      <h1>
        <a href="index.html" title="">PLAY Project: Survey protocol</a>
      </h1>
      <button class="btn btn-outline-primary d-lg-none ml-2 mt-1" type="button" data-toggle="collapse" data-target="#main-nav" aria-expanded="true" aria-controls="main-nav"><i class="fas fa-bars"></i><span class="sr-only">Show table of contents</span></button>
    </div>

    <div id="main-nav" class="collapse-lg">
      <form role="search">
        <input id="search" class="form-control" type="search" placeholder="Search" aria-label="Search">
</form>

      <nav aria-label="Table of contents"><h2>Table of contents</h2>
        <ul class="book-toc list-unstyled">
<li><a class="" href="index.html">About</a></li>
<li><a class="" href="setup.html"><span class="header-section-number">1</span> Setup</a></li>
<li><a class="active" href="screening-call.html">Screening call</a></li>
<li><a class="" href="home-visit.html">Home visit</a></li>
<li><a class="" href="data-dictionary.html">Data dictionary</a></li>
<li><a class="" href="visualization.html">Visualization</a></li>
</ul>

        <div class="book-extra">
          <p><a id="book-repo" href="https://github.com/PLAY-behaviorome/KoBoToolbox">View book source <i class="fab fa-github"></i></a></p>
        </div>
      </nav>
</div>
  </header><main class="col-sm-12 col-md-9 col-lg-7" id="content"><div id="screening-call" class="section level1 unnumbered">
<h1>Screening call<a class="anchor" aria-label="anchor" href="#screening-call"><i class="fas fa-link"></i></a>
</h1>
<div id="collection-protocol" class="section level2 unnumbered">
<h2>Collection protocol<a class="anchor" aria-label="anchor" href="#collection-protocol"><i class="fas fa-link"></i></a>
</h2>
<p>Details about the data collection <a href="https://www.play-project.org/collection.html#Participant_Recruitment">protocol for participant screening and recruiting</a> can be found on the <a href="https://play-project.org">PLAY Project website</a>.</p>
</div>
<div id="retrieve-files-from-kobotoolbox" class="section level2 unnumbered">
<h2>Retrieve files from KoBoToolbox<a class="anchor" aria-label="anchor" href="#retrieve-files-from-kobotoolbox"><i class="fas fa-link"></i></a>
</h2>
<p>The relevant KoBoToolbox data files have ‘Demographic Questionnaire’ in the title.</p>
<div class="sourceCode" id="cb21"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">kb_df</span> <span class="op">&lt;-</span> <span class="fu">list_kobo_data</span><span class="op">(</span><span class="op">)</span></span>
<span><span class="kw">if</span> <span class="op">(</span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/dim.html">dim</a></span><span class="op">(</span><span class="va">kb_df</span><span class="op">)</span><span class="op">[</span><span class="fl">1</span><span class="op">]</span> <span class="op">&lt;</span> <span class="fl">1</span><span class="op">)</span> <span class="op">||</span> <span class="op">(</span><span class="op">!</span><span class="fu"><a href="https://rdrr.io/r/base/as.data.frame.html">is.data.frame</a></span><span class="op">(</span><span class="va">kb_df</span><span class="op">)</span><span class="op">)</span><span class="op">)</span> <span class="op">{</span></span>
<span>  <span class="kw"><a href="https://rdrr.io/r/base/stop.html">stop</a></span><span class="op">(</span><span class="st">"Error in selecting surveys from KoBoToolbox."</span><span class="op">)</span></span>
<span><span class="op">}</span></span>
<span></span>
<span><span class="co"># Restrict to surveys collected at home</span></span>
<span><span class="va">kb_demog</span> <span class="op">&lt;-</span> <span class="va">kb_df</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu">dplyr</span><span class="fu">::</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">.</span>, <span class="fu">stringr</span><span class="fu">::</span><span class="fu"><a href="https://stringr.tidyverse.org/reference/str_detect.html">str_detect</a></span><span class="op">(</span><span class="va">title</span>, <span class="st">"Demographic"</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="kw">if</span> <span class="op">(</span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/dim.html">dim</a></span><span class="op">(</span><span class="va">kb_demog</span><span class="op">)</span><span class="op">[</span><span class="fl">1</span><span class="op">]</span> <span class="op">&lt;</span> <span class="fl">1</span><span class="op">)</span> <span class="op">||</span> <span class="op">(</span><span class="op">!</span><span class="fu"><a href="https://rdrr.io/r/base/as.data.frame.html">is.data.frame</a></span><span class="op">(</span><span class="va">kb_demog</span><span class="op">)</span><span class="op">)</span><span class="op">)</span> <span class="op">{</span></span>
<span>  <span class="kw"><a href="https://rdrr.io/r/base/stop.html">stop</a></span><span class="op">(</span><span class="st">"Error in selecting demographics surveys from KoBoToolbox."</span><span class="op">)</span></span>
<span><span class="op">}</span></span></code></pre></div>
<div id="save-selected-raw-files-to-local-directory" class="section level3 unnumbered">
<h3>Save selected raw files to local directory<a class="anchor" aria-label="anchor" href="#save-selected-raw-files-to-local-directory"><i class="fas fa-link"></i></a>
</h3>
<p>Prepare to retrieve all demographic data files.</p>
<div class="sourceCode" id="cb22"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="kw">if</span> <span class="op">(</span><span class="op">!</span><span class="fu"><a href="https://rdrr.io/r/base/files2.html">dir.exists</a></span><span class="op">(</span><span class="st">'data/xlsx/screening'</span><span class="op">)</span><span class="op">)</span> <span class="op">{</span></span>
<span>  <span class="kw"><a href="https://rdrr.io/r/base/stop.html">stop</a></span><span class="op">(</span><span class="st">"Directory not found: 'data/xlsx/screening'"</span><span class="op">)</span></span>
<span><span class="op">}</span></span>
<span><span class="va">n_files</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/dim.html">dim</a></span><span class="op">(</span><span class="va">kb_demog</span><span class="op">)</span><span class="op">[</span><span class="fl">1</span><span class="op">]</span></span></code></pre></div>
<div class="sourceCode" id="cb23"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu">purrr</span><span class="fu">::</span><span class="fu"><a href="https://purrr.tidyverse.org/reference/map.html">map</a></span><span class="op">(</span><span class="fl">1</span><span class="op">:</span><span class="va">n_files</span>, <span class="va">retrieve_save_xls_export</span>, kb_df <span class="op">=</span> <span class="va">kb_demog</span>, save_dir <span class="op">=</span> <span class="st">"data/xlsx/screening"</span><span class="op">)</span></span></code></pre></div>
<pre><code>## Loading required package: stringr</code></pre>
<pre><code>## Saved `data/xlsx/screening/334134_PLAY_Demographic_Questionnaire_Spanish.xlsx`</code></pre>
<pre><code>## Saved `data/xlsx/screening/359546_PLAY_Demographic_Questionnaire.xlsx`</code></pre>
<pre><code>## Saved `data/xlsx/screening/275882_PLAY_Demographic_Questionnaire.xlsx`</code></pre>
<pre><code>## [[1]]
## [1] "data/xlsx/screening/334134_PLAY_Demographic_Questionnaire_Spanish.xlsx"
## 
## [[2]]
## [1] "data/xlsx/screening/359546_PLAY_Demographic_Questionnaire.xlsx"
## 
## [[3]]
## [1] "data/xlsx/screening/275882_PLAY_Demographic_Questionnaire.xlsx"</code></pre>
</div>
</div>
<div id="convert-to-csvs" class="section level2 unnumbered">
<h2>Convert to CSVs<a class="anchor" aria-label="anchor" href="#convert-to-csvs"><i class="fas fa-link"></i></a>
</h2>
<p>By default, we presume that we want to convert <strong>all</strong> of the XLSX files in <code>data/xlxs/screening</code> to CSVs.</p>
<div id="open-files-and-process" class="section level3 unnumbered">
<h3>Open file(s) and process<a class="anchor" aria-label="anchor" href="#open-files-and-process"><i class="fas fa-link"></i></a>
</h3>
<p>While not strictly necessary, we filter the downloaded filename to ensure that it includes ‘Demographic_Questionnaire’.
The leading 6-digit integer is a unique ‘form’ identifier, so we extract it.</p>
<div class="sourceCode" id="cb29"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">demog_fns</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/list.files.html">list.files</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/file.path.html">file.path</a></span><span class="op">(</span><span class="st">"data/xlsx/screening"</span><span class="op">)</span>, pattern <span class="op">=</span> <span class="st">"Demographic_Questionnaire"</span>, full.names <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span>
<span></span>
<span><span class="va">demog_fns_trimmed</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/basename.html">basename</a></span><span class="op">(</span><span class="fu">stringr</span><span class="fu">::</span><span class="fu"><a href="https://stringr.tidyverse.org/reference/str_replace.html">str_replace</a></span><span class="op">(</span><span class="va">demog_fns</span>, pattern <span class="op">=</span> <span class="st">"\\.xlsx"</span>, replacement <span class="op">=</span> <span class="st">"\\.csv"</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="va">form_ids</span> <span class="op">&lt;-</span> <span class="fu">stringr</span><span class="fu">::</span><span class="fu"><a href="https://stringr.tidyverse.org/reference/str_extract.html">str_extract</a></span><span class="op">(</span><span class="va">demog_fns_trimmed</span>, pattern <span class="op">=</span> <span class="st">"[0-9]{6}"</span><span class="op">)</span></span></code></pre></div>
<p>Create a helper function to handle import, renaming, and exporting.</p>
<div class="sourceCode" id="cb30"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">load_xlsx_save_csv</span> <span class="op">&lt;-</span> <span class="kw">function</span><span class="op">(</span><span class="va">i</span>, <span class="va">fl</span><span class="op">)</span> <span class="op">{</span></span>
<span>  <span class="va">xl</span> <span class="op">&lt;-</span> <span class="fu">readxl</span><span class="fu">::</span><span class="fu"><a href="https://readxl.tidyverse.org/reference/read_excel.html">read_xlsx</a></span><span class="op">(</span><span class="va">fl</span><span class="op">[</span><span class="va">i</span><span class="op">]</span><span class="op">)</span></span>
<span>  <span class="va">fn_csv</span> <span class="op">&lt;-</span> <span class="fu">stringr</span><span class="fu">::</span><span class="fu"><a href="https://stringr.tidyverse.org/reference/str_replace.html">str_replace</a></span><span class="op">(</span><span class="va">fl</span><span class="op">[</span><span class="va">i</span><span class="op">]</span>, pattern <span class="op">=</span> <span class="st">"\\.xlsx"</span>, replacement <span class="op">=</span> <span class="st">"\\.csv"</span><span class="op">)</span></span>
<span>  <span class="va">fn_csv</span> <span class="op">&lt;-</span> <span class="fu">stringr</span><span class="fu">::</span><span class="fu"><a href="https://stringr.tidyverse.org/reference/str_replace.html">str_replace</a></span><span class="op">(</span><span class="va">fn_csv</span>, pattern <span class="op">=</span> <span class="st">"/xlsx/"</span>, <span class="st">"/csv/"</span><span class="op">)</span></span>
<span>  <span class="kw">if</span> <span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/files2.html">dir.exists</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/basename.html">dirname</a></span><span class="op">(</span><span class="va">fn_csv</span><span class="op">)</span><span class="op">)</span><span class="op">)</span> <span class="op">{</span></span>
<span>    <span class="fu">readr</span><span class="fu">::</span><span class="fu"><a href="https://readr.tidyverse.org/reference/write_delim.html">write_csv</a></span><span class="op">(</span><span class="va">xl</span>, <span class="va">fn_csv</span><span class="op">)</span>    </span>
<span>  <span class="op">}</span> <span class="kw">else</span> <span class="op">{</span></span>
<span>    <span class="kw"><a href="https://rdrr.io/r/base/warning.html">warning</a></span><span class="op">(</span><span class="st">"Directory not found: '"</span>, <span class="fu"><a href="https://rdrr.io/r/base/basename.html">dirname</a></span><span class="op">(</span><span class="va">fn_csv</span><span class="op">)</span>, <span class="st">"'"</span><span class="op">)</span></span>
<span>  <span class="op">}</span></span>
<span><span class="op">}</span></span></code></pre></div>
<p>Import xlsx and save csv version.</p>
<div class="sourceCode" id="cb31"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu">purrr</span><span class="fu">::</span><span class="fu"><a href="https://purrr.tidyverse.org/reference/map.html">map</a></span><span class="op">(</span><span class="fl">1</span><span class="op">:</span><span class="fu"><a href="https://rdrr.io/r/base/length.html">length</a></span><span class="op">(</span><span class="va">demog_fns</span><span class="op">)</span>, <span class="va">load_xlsx_save_csv</span>, <span class="va">demog_fns</span><span class="op">)</span></span></code></pre></div>
<pre><code>## [[1]]
## # A tibble: 20 × 168
##    start        end   c_today play_…¹ play_…² play_…³ play_…⁴ play_…⁵
##    &lt;chr&gt;        &lt;chr&gt; &lt;chr&gt;   &lt;lgl&gt;   &lt;lgl&gt;   &lt;chr&gt;   &lt;chr&gt;   &lt;lgl&gt;  
##  1 2019-10-08T… 2020… 2020-0… NA      NA      (917) … michel… NA     
##  2 2019-04-25T… 2019… &lt;NA&gt;    NA      NA      &lt;NA&gt;    &lt;NA&gt;    NA     
##  3 2019-06-05T… 2019… 2019-0… NA      NA      &lt;NA&gt;    &lt;NA&gt;    NA     
##  4 2019-06-10T… 2019… 2019-0… NA      NA      &lt;NA&gt;    &lt;NA&gt;    NA     
##  5 2019-06-29T… 2019… 2019-0… NA      NA      &lt;NA&gt;    &lt;NA&gt;    NA     
##  6 2019-09-05T… 2019… 2019-0… NA      NA      201-20… mavi75… NA     
##  7 2019-09-11T… 2019… 2019-0… NA      NA      Pilot   Pilot   NA     
##  8 2019-09-13T… 2019… 2019-0… NA      NA      808255… raethe… NA     
##  9 2019-09-16T… 2019… 2019-0… NA      NA      (929) … lisafa… NA     
## 10 2019-10-03T… 2019… 2019-1… NA      NA      202321… donyal… NA     
## 11 2019-10-03T… 2019… 2019-1… NA      NA      917-69… jessic… NA     
## 12 2019-10-04T… 2019… 2019-1… NA      NA      NA      NA      NA     
## 13 2019-10-10T… 2019… 2019-1… NA      NA      917-36… ceped6… NA     
## 14 2019-10-16T… 2020… 2020-0… NA      NA      (646) … akss.s… NA     
## 15 2019-11-05T… 2019… 2019-1… NA      NA      (703) … briane… NA     
## 16 2019-11-08T… 2020… 2020-0… NA      NA      202966… alison… NA     
## 17 2019-11-12T… 2019… 2019-1… NA      NA      (415) … miraco… NA     
## 18 2019-11-26T… 2019… 2019-1… NA      NA      202394… kateco… NA     
## 19 2019-12-02T… 2019… 2019-1… NA      NA      717521… saraha… NA     
## 20 2019-12-10T… 2019… 2019-1… NA      NA      (202) … julie.… NA     
## # … with 160 more variables:
## #   `play_phone_questionnaire/group_contact_info/group_address/parent_address_1` &lt;chr&gt;,
## #   `play_phone_questionnaire/group_contact_info/group_address/parent_address_2` &lt;chr&gt;,
## #   `play_phone_questionnaire/group_contact_info/group_address/city` &lt;chr&gt;,
## #   `play_phone_questionnaire/group_contact_info/group_address/state` &lt;chr&gt;,
## #   `play_phone_questionnaire/group_contact_info/acknowledge_contact_info` &lt;chr&gt;,
## #   `play_phone_questionnaire/instructions_guid` &lt;lgl&gt;, …
## 
## [[2]]
## # A tibble: 1 × 236
##   start end   c_today play_…¹ play_…² play_…³ play_…⁴ play_…⁵ play_…⁶
##   &lt;chr&gt; &lt;chr&gt; &lt;chr&gt;   &lt;lgl&gt;   &lt;lgl&gt;   &lt;chr&gt;   &lt;chr&gt;   &lt;chr&gt;   &lt;lgl&gt;  
## 1 2022… 2022… 2022-1… NA      NA      UTAUS   001     Tamara… NA     
## # … with 227 more variables:
## #   `play_demo_questionnaire/group_contact_info/parent_phone` &lt;chr&gt;,
## #   `play_demo_questionnaire/group_contact_info/parent_email` &lt;chr&gt;,
## #   `play_demo_questionnaire/group_contact_info/group_address/note_parent_address` &lt;lgl&gt;,
## #   `play_demo_questionnaire/group_contact_info/group_address/parent_address_1` &lt;chr&gt;,
## #   `play_demo_questionnaire/group_contact_info/group_address/parent_address_2` &lt;chr&gt;,
## #   `play_demo_questionnaire/group_contact_info/group_address/city` &lt;chr&gt;, …
## 
## [[3]]
## # A tibble: 224 × 239
##    start        end   c_today play_…¹ play_…² play_…³ play_…⁴ play_…⁵
##    &lt;chr&gt;        &lt;chr&gt; &lt;chr&gt;   &lt;lgl&gt;   &lt;lgl&gt;   &lt;chr&gt;   &lt;chr&gt;   &lt;chr&gt;  
##  1 2020-02-27T… 2020… 2020-0… NA      NA      NYUNI   230     &lt;NA&gt;   
##  2 2020-02-27T… 2020… 2020-0… NA      NA      NYUNI   229     &lt;NA&gt;   
##  3 2019-12-18T… 2020… 2020-0… NA      NA      VCOMU   002     &lt;NA&gt;   
##  4 2020-01-01T… 2020… 2020-0… NA      NA      GEORG   010     &lt;NA&gt;   
##  5 2020-01-15T… 2020… 2020-0… NA      NA      NYUNI   008     &lt;NA&gt;   
##  6 2020-01-15T… 2020… 2020-0… NA      NA      NYUNI   009     &lt;NA&gt;   
##  7 2020-01-24T… 2020… 2020-0… NA      NA      GEORG   011     &lt;NA&gt;   
##  8 2020-01-30T… 2020… 2020-0… NA      NA      NYUNI   010     &lt;NA&gt;   
##  9 2020-02-03T… 2020… 2020-0… NA      NA      NYUNI   011     &lt;NA&gt;   
## 10 2020-02-05T… 2020… 2020-0… NA      NA      VCOMU   003     &lt;NA&gt;   
## # … with 214 more rows, 231 more variables:
## #   `play_demo_questionnaire/group_contact_info/instructions_contactinfo` &lt;lgl&gt;,
## #   `play_demo_questionnaire/group_contact_info/parent_phone` &lt;chr&gt;,
## #   `play_demo_questionnaire/group_contact_info/parent_email` &lt;chr&gt;,
## #   `play_demo_questionnaire/group_contact_info/group_address/note_parent_address` &lt;lgl&gt;,
## #   `play_demo_questionnaire/group_contact_info/group_address/parent_address_1` &lt;chr&gt;,
## #   `play_demo_questionnaire/group_contact_info/group_address/parent_address_2` &lt;chr&gt;, …</code></pre>
</div>
</div>
<div id="merge-files" class="section level2 unnumbered">
<h2>Merge files<a class="anchor" aria-label="anchor" href="#merge-files"><i class="fas fa-link"></i></a>
</h2>
<div id="compare-the-files" class="section level3 unnumbered">
<h3>Compare the files<a class="anchor" aria-label="anchor" href="#compare-the-files"><i class="fas fa-link"></i></a>
</h3>
<p>Before merging, we have to examine how the fields compare.</p>
<div class="sourceCode" id="cb33"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">csv_fns</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/list.files.html">list.files</a></span><span class="op">(</span><span class="st">"data/csv/screening"</span>, pattern <span class="op">=</span> <span class="st">"\\.csv"</span>, full.names <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span></code></pre></div>
<p>Open the first file: ‘275882_PLAY_Demographic_Questionnaire.csv’.</p>
<div class="sourceCode" id="cb34"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">demog_1</span> <span class="op">&lt;-</span> <span class="fu">readr</span><span class="fu">::</span><span class="fu"><a href="https://readr.tidyverse.org/reference/read_delim.html">read_csv</a></span><span class="op">(</span><span class="va">csv_fns</span><span class="op">[</span><span class="fl">1</span><span class="op">]</span>, show_col_types <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span></code></pre></div>
<p>There are <span class="math inline">\(n=\)</span> 20 data records and <span class="math inline">\(n=\)</span> 168 fields.</p>
<p>Open the second file: ‘334134_PLAY_Demographic_Questionnaire_Spanish.csv’.</p>
<div class="sourceCode" id="cb35"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">demog_2</span> <span class="op">&lt;-</span> <span class="fu">readr</span><span class="fu">::</span><span class="fu"><a href="https://readr.tidyverse.org/reference/read_delim.html">read_csv</a></span><span class="op">(</span><span class="va">csv_fns</span><span class="op">[</span><span class="fl">2</span><span class="op">]</span>, show_col_types <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span></code></pre></div>
<p>There are <span class="math inline">\(n=\)</span> 1 data records and <span class="math inline">\(n=\)</span> 236 fields.</p>
<p>Open the third file: ‘359546_PLAY_Demographic_Questionnaire.csv’.</p>
<div class="sourceCode" id="cb36"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">demog_3</span> <span class="op">&lt;-</span> <span class="fu">readr</span><span class="fu">::</span><span class="fu"><a href="https://readr.tidyverse.org/reference/read_delim.html">read_csv</a></span><span class="op">(</span><span class="va">csv_fns</span><span class="op">[</span><span class="fl">3</span><span class="op">]</span>, show_col_types <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span></code></pre></div>
<p>There are <span class="math inline">\(n=\)</span> 224 data records and <span class="math inline">\(n=\)</span> 239 fields.</p>
<div class="rmdnote">
<p>These files have different numbers of columns, so we will need to be careful in creating a merged data file.</p>
</div>
</div>
<div id="extract-column-names" class="section level3 unnumbered">
<h3>Extract column names<a class="anchor" aria-label="anchor" href="#extract-column-names"><i class="fas fa-link"></i></a>
</h3>
<div class="sourceCode" id="cb37"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">demog_1_names</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">demog_1</span><span class="op">)</span></span>
<span><span class="va">demog_2_names</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">demog_2</span><span class="op">)</span></span>
<span><span class="va">demog_3_names</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">demog_3</span><span class="op">)</span></span></code></pre></div>
<p>Compare 1 to 2.</p>
<div class="sourceCode" id="cb38"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">demog_1_names</span> <span class="op">==</span> <span class="va">demog_2_names</span><span class="op">)</span></span></code></pre></div>
<pre><code>## Warning in demog_1_names == demog_2_names: longer object length is
## not a multiple of shorter object length</code></pre>
<pre><code>## [1] 3</code></pre>
<p>Compare 1 to 3.</p>
<div class="sourceCode" id="cb41"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">demog_1_names</span> <span class="op">==</span> <span class="va">demog_3_names</span><span class="op">)</span></span></code></pre></div>
<pre><code>## Warning in demog_1_names == demog_3_names: longer object length is
## not a multiple of shorter object length</code></pre>
<pre><code>## [1] 3</code></pre>
<p>Compare 2 to 3.</p>
<div class="sourceCode" id="cb44"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">demog_2_names</span> <span class="op">==</span> <span class="va">demog_3_names</span><span class="op">)</span></span></code></pre></div>
<pre><code>## Warning in demog_2_names == demog_3_names: longer object length is
## not a multiple of shorter object length</code></pre>
<pre><code>## [1] 131</code></pre>
<p>The second and third data files have the most overlap.</p>

</div>
</div>
</div>
  <div class="chapter-nav">
<div class="prev"><a href="setup.html"><span class="header-section-number">1</span> Setup</a></div>
<div class="next"><a href="home-visit.html">Home visit</a></div>
</div></main><div class="col-md-3 col-lg-2 d-none d-md-block sidebar sidebar-chapter">
    <nav id="toc" data-toggle="toc" aria-label="On this page"><h2>On this page</h2>
      <ul class="nav navbar-nav">
<li><a class="nav-link" href="#screening-call">Screening call</a></li>
<li><a class="nav-link" href="#collection-protocol">Collection protocol</a></li>
<li>
<a class="nav-link" href="#retrieve-files-from-kobotoolbox">Retrieve files from KoBoToolbox</a><ul class="nav navbar-nav"><li><a class="nav-link" href="#save-selected-raw-files-to-local-directory">Save selected raw files to local directory</a></li></ul>
</li>
<li>
<a class="nav-link" href="#convert-to-csvs">Convert to CSVs</a><ul class="nav navbar-nav"><li><a class="nav-link" href="#open-files-and-process">Open file(s) and process</a></li></ul>
</li>
<li>
<a class="nav-link" href="#merge-files">Merge files</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#compare-the-files">Compare the files</a></li>
<li><a class="nav-link" href="#extract-column-names">Extract column names</a></li>
</ul>
</li>
</ul>

      <div class="book-extra">
        <ul class="list-unstyled">
<li><a id="book-source" href="https://github.com/PLAY-behaviorome/KoBoToolbox/blob/master/02-screening.Rmd">View source <i class="fab fa-github"></i></a></li>
          <li><a id="book-edit" href="https://github.com/PLAY-behaviorome/KoBoToolbox/edit/master/02-screening.Rmd">Edit this page <i class="fab fa-github"></i></a></li>
        </ul>
</div>
    </nav>
</div>

</div>
</div> <!-- .container -->

<footer class="bg-primary text-light mt-5"><div class="container"><div class="row">

  <div class="col-12 col-md-6 mt-3">
    <p>"<strong>PLAY Project: Survey protocol</strong>" was written by Rick Gilmore. It was last built on 2022-11-29.</p>
  </div>

  <div class="col-12 col-md-6 mt-3">
    <p>This book was built by the <a class="text-light" href="https://bookdown.org">bookdown</a> R package.</p>
  </div>

</div></div>
</footer><!-- dynamically load mathjax for compatibility with self-contained --><script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script><script type="text/x-mathjax-config">const popovers = document.querySelectorAll('a.footnote-ref[data-toggle="popover"]');
for (let popover of popovers) {
  const div = document.createElement('div');
  div.setAttribute('style', 'position: absolute; top: 0, left:0; width:0, height:0, overflow: hidden; visibility: hidden;');
  div.innerHTML = popover.getAttribute('data-content');

  var has_math = div.querySelector("span.math");
  if (has_math) {
    document.body.appendChild(div);
    MathJax.Hub.Queue(["Typeset", MathJax.Hub, div]);
    MathJax.Hub.Queue(function() {
      popover.setAttribute('data-content', div.innerHTML);
      document.body.removeChild(div);
    })
  }
}
</script>
</body>
</html>
