<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <title>12-screening.knit</title>

  
   
   <meta name="generator" content="placeholder" />
  <meta property="og:title" content="12-screening.knit" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="12-screening.knit" />
  
  
  
  <!-- JS -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/6.4.6/fuse.js" integrity="sha512-zv6Ywkjyktsohkbp9bb45V6tEMoWhzFzXis+LrMehmJZZSys19Yxf1dopHx7WzIKxr5tK2dVcYmaCk2uqdjF4A==" crossorigin="anonymous"></script>
  <script src="https://kit.fontawesome.com/6ecbd6c532.js" crossorigin="anonymous"></script>
    <script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <link href="libs/bootstrap-4.6.0/bootstrap.min.css" rel="stylesheet" />
    <script src="libs/bootstrap-4.6.0/bootstrap.bundle.min.js"></script>
    <script src="libs/bs3compat-0.4.2/transition.js"></script>
    <script src="libs/bs3compat-0.4.2/tabs.js"></script>
    <script src="libs/bs3compat-0.4.2/bs3compat.js"></script>
    <link href="libs/bs4_book-1.0.0/bs4_book.css" rel="stylesheet" />
    <script src="libs/bs4_book-1.0.0/bs4_book.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/autocomplete.js/0.38.0/autocomplete.jquery.min.js" integrity="sha512-GU9ayf+66Xx2TmpxqJpliWbT5PiGYxpaG8rfnBEk1LL8l1KGkRShhngwdXK1UgqhAzWpZHSiYPc09/NwDQIGyg==" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/mark.min.js" integrity="sha512-5CYOlHXGh6QpOFA/TeTylKLWfB3ftPsde7AnmhuitiTX4K5SqCLBeKro6sPS8ilsz1Q4NRx3v8Ko2IBiszzdww==" crossorigin="anonymous"></script>

  <!-- CSS -->
  <style type="text/css">
    
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  </style>
      <link rel="stylesheet" href="include/css/style.css" />
  
</head>

<body data-spy="scroll" data-target="#toc">

<div class="container-fluid">
<!--bookdown:title:start-->
<!--bookdown:title:end-->

<!--bookdown:toc:start-->
<div class="row">
  <header class="col-sm-12 col-lg-3 sidebar sidebar-book">
    <a class="sr-only sr-only-focusable" href="#content">Skip to main content</a>

    <div class="d-flex align-items-start justify-content-between">
      <h1>
        <a href="index.html" title=""></a>
      </h1>
      <button class="btn btn-outline-primary d-lg-none ml-2 mt-1" type="button" data-toggle="collapse" data-target="#main-nav" aria-expanded="true" aria-controls="main-nav"><i class="fas fa-bars"></i><span class="sr-only">Show table of contents</span></button>
    </div>

    <div id="main-nav" class="collapse-lg">
      <form role="search">
        <input id="search" class="form-control" type="search" placeholder="Search" aria-label="Search">
      </form>

      <nav aria-label="Table of contents">
        <h2>Table of contents</h2>
        <div id="book-toc"></div>

        <div class="book-extra">
          <p><a id="book-repo" href="#">View book source <i class="fab fa-github"></i></a></li></p>
        </div>
      </nav>
    </div>
  </header>

  <main class="col-sm-12 col-md-9 col-lg-7" id="content">
<!--bookdown:toc:end-->
<!--bookdown:body:start-->
<div id="screening-call" class="section level1 unnumbered">
<h1 class="unnumbered">Screening call</h1>
<div id="collection-protocol" class="section level2 unnumbered">
<h2 class="unnumbered">Collection protocol</h2>
<p>Details about the data collection <a href="https://www.play-project.org/collection.html#Participant_Recruitment">protocol for participant screening and recruiting</a> can be found on the <a href="https://play-project.org">PLAY Project website</a>.</p>
</div>
<div id="retrieve-from-kobotoolbox-kbt" class="section level2 unnumbered">
<h2 class="unnumbered">Retrieve from KoBoToolbox (KBT)</h2>
<p>We make use of the <code>targets</code> package for downloading data files from KoBoToolbox
and for saving local XLSX and CSV copies.
This allows us to download and process those files on a regular basis.</p>
<div id="setup" class="section level3 unnumbered">
<h3 class="unnumbered">Setup</h3>
<p>Load functions needed to download KBT screening/demographic questionnaire files.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" tabindex="-1"></a>fl <span class="ot">&lt;-</span> <span class="fu">list.files</span>(<span class="fu">file.path</span>(here<span class="sc">::</span><span class="fu">here</span>(), <span class="st">&quot;R&quot;</span>), <span class="st">&quot;^kobo_|^file_&quot;</span>, <span class="at">full.names =</span> <span class="cn">TRUE</span>)</span>
<span id="cb1-2"><a href="#cb1-2" tabindex="-1"></a>purrr<span class="sc">::</span><span class="fu">walk</span>(fl, source)</span></code></pre></div>
</div>
<div id="download" class="section level3 unnumbered">
<h3 class="unnumbered">Download</h3>
<p>We have two targets specified in <code>_targets.R</code> that handle the regular downloading of screening data files.</p>
<p>First, we generate a data frame of KoBoToolbox forms that contain the screening (“Demographic”) data.
Here is the target for that process:</p>
<pre><code># Not evaluated
  tar_target(
    kb_screen_df,
    kobo_list_data_filtered(&quot;[Dd]emographic&quot;),
    cue = tarchetypes::tar_cue_age(
      name = kb_screen,
      age = as.difftime(update_interval, units = update_interval_units)
    )
  ),</code></pre>
<p>Then we download and save the raw XLSX files to <code>../data/xlsx/screening</code> using <code>kobo_retrieve_save_many_xlsx(kb_screen_df, save_dir = "../data/xlsx/screening")</code>.
Finally, we convert the XLSX files to CSVs via <code>file_load_xlsx_save_many_csv("../data/xlsx/screening", "../data/csv/screening", "Demographic")</code>.
The latter two steps are handled by the wrapper function <code>screen_download_convert(kb_screen_df, "data/xlsx/screening", "data/csv/screening")</code>.
Here is the accompanying target:</p>
<pre><code># Download screening/demographic survey
  tar_target(
    screen_download,
    screen_download_convert(kb_screen_df, &quot;data/xlsx/screening&quot;, &quot;data/csv/screening&quot;),
    cue = tarchetypes::tar_cue_age(
      name = screen_df,
      age = as.difftime(update_interval, units = update_interval_units)
    )
  ),</code></pre>
</div>
</div>
<div id="clean-and-merge" class="section level2 unnumbered">
<h2 class="unnumbered">Clean and merge</h2>
<p>As of 2023-09-22, the cleaning and merging process for the screening/demographic data is handled here, in this document, not as a target.</p>
<div id="setup-1" class="section level3 unnumbered">
<h3 class="unnumbered">Setup</h3>
<p>A set of cleaning functions have the <code>screen_</code> prefix.</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" tabindex="-1"></a>purrr<span class="sc">::</span><span class="fu">walk</span>(<span class="fu">list.files</span>(<span class="fu">file.path</span>(here<span class="sc">::</span><span class="fu">here</span>(), <span class="st">&quot;R&quot;</span>), </span>
<span id="cb4-2"><a href="#cb4-2" tabindex="-1"></a>                    <span class="st">&quot;^screen_&quot;</span>, <span class="at">full.names =</span> <span class="cn">TRUE</span>), source)</span></code></pre></div>
<p>There are three CSV files to clean:</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" tabindex="-1"></a>(fn <span class="ot">&lt;-</span> <span class="fu">list.files</span>(<span class="st">&quot;../data/csv/screening&quot;</span>, <span class="st">&quot;[Dd]emographic&quot;</span>, <span class="at">full.names =</span> <span class="cn">TRUE</span>))</span></code></pre></div>
<pre><code>## [1] &quot;../data/csv/screening/275882_PLAY_Demographic_Questionnaire.csv&quot;        
## [2] &quot;../data/csv/screening/334134_PLAY_Demographic_Questionnaire_Spanish.csv&quot;
## [3] &quot;../data/csv/screening/359546_PLAY_Demographic_Questionnaire.csv&quot;</code></pre>
<p>We clean them separately, as needed, then merge them.</p>
</div>
<div id="clean-variable-names" class="section level3 unnumbered">
<h3 class="unnumbered">Clean variable names</h3>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" tabindex="-1"></a>df1 <span class="ot">&lt;-</span></span>
<span id="cb7-2"><a href="#cb7-2" tabindex="-1"></a>  readr<span class="sc">::</span><span class="fu">read_csv</span>(fn[<span class="dv">1</span>],</span>
<span id="cb7-3"><a href="#cb7-3" tabindex="-1"></a>                  <span class="at">col_types =</span> readr<span class="sc">::</span><span class="fu">cols</span>(<span class="at">.default =</span> <span class="st">&#39;c&#39;</span>),</span>
<span id="cb7-4"><a href="#cb7-4" tabindex="-1"></a>                  <span class="at">show_col_types =</span> <span class="cn">FALSE</span>)</span>
<span id="cb7-5"><a href="#cb7-5" tabindex="-1"></a>df2 <span class="ot">&lt;-</span></span>
<span id="cb7-6"><a href="#cb7-6" tabindex="-1"></a>  readr<span class="sc">::</span><span class="fu">read_csv</span>(fn[<span class="dv">2</span>],</span>
<span id="cb7-7"><a href="#cb7-7" tabindex="-1"></a>                  <span class="at">col_types =</span> readr<span class="sc">::</span><span class="fu">cols</span>(<span class="at">.default =</span> <span class="st">&#39;c&#39;</span>),</span>
<span id="cb7-8"><a href="#cb7-8" tabindex="-1"></a>                  <span class="at">show_col_types =</span> <span class="cn">FALSE</span>)</span>
<span id="cb7-9"><a href="#cb7-9" tabindex="-1"></a>df3 <span class="ot">&lt;-</span></span>
<span id="cb7-10"><a href="#cb7-10" tabindex="-1"></a>  readr<span class="sc">::</span><span class="fu">read_csv</span>(fn[<span class="dv">3</span>],</span>
<span id="cb7-11"><a href="#cb7-11" tabindex="-1"></a>                  <span class="at">col_types =</span> readr<span class="sc">::</span><span class="fu">cols</span>(<span class="at">.default =</span> <span class="st">&#39;c&#39;</span>),</span>
<span id="cb7-12"><a href="#cb7-12" tabindex="-1"></a>                  <span class="at">show_col_types =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" tabindex="-1"></a><span class="fu">head</span>(<span class="fu">names</span>(df1), <span class="dv">15</span>)</span></code></pre></div>
<pre><code>##  [1] &quot;start&quot;                                                                        
##  [2] &quot;end&quot;                                                                          
##  [3] &quot;c_today&quot;                                                                      
##  [4] &quot;play_phone_questionnaire/update_date&quot;                                         
##  [5] &quot;play_phone_questionnaire/group_contact_info/instructions_contactinfo&quot;         
##  [6] &quot;play_phone_questionnaire/group_contact_info/parent_phone&quot;                     
##  [7] &quot;play_phone_questionnaire/group_contact_info/parent_email&quot;                     
##  [8] &quot;play_phone_questionnaire/group_contact_info/group_address/note_parent_address&quot;
##  [9] &quot;play_phone_questionnaire/group_contact_info/group_address/parent_address_1&quot;   
## [10] &quot;play_phone_questionnaire/group_contact_info/group_address/parent_address_2&quot;   
## [11] &quot;play_phone_questionnaire/group_contact_info/group_address/city&quot;               
## [12] &quot;play_phone_questionnaire/group_contact_info/group_address/state&quot;              
## [13] &quot;play_phone_questionnaire/group_contact_info/acknowledge_contact_info&quot;         
## [14] &quot;play_phone_questionnaire/instructions_guid&quot;                                   
## [15] &quot;play_phone_questionnaire/child_first_name&quot;</code></pre>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" tabindex="-1"></a><span class="fu">head</span>(<span class="fu">names</span>(df2), <span class="dv">15</span>)</span></code></pre></div>
<pre><code>##  [1] &quot;start&quot;                                                                                                                                                                                                                                    
##  [2] &quot;end&quot;                                                                                                                                                                                                                                      
##  [3] &quot;c_today&quot;                                                                                                                                                                                                                                  
##  [4] &quot;play_demo_questionnaire/update_date&quot;                                                                                                                                                                                                      
##  [5] &quot;play_demo_questionnaire/NOTA_El_cuestionario_demogr_fico_debe_ser_completado_por_el_investigador_que_va_a_ir_a_la_visita_al_hogar_con_la_madre_por_tel_fono_La_madre_deber_a_ser_la_madre_que_va_a_participar_en_el_estudio_con_su_ni_o_a&quot;
##  [6] &quot;play_demo_questionnaire/group_siteinfo/site_id&quot;                                                                                                                                                                                           
##  [7] &quot;play_demo_questionnaire/group_siteinfo/subject_number&quot;                                                                                                                                                                                    
##  [8] &quot;play_demo_questionnaire/exp_name&quot;                                                                                                                                                                                                         
##  [9] &quot;play_demo_questionnaire/group_contact_info/instructions_contactinfo&quot;                                                                                                                                                                      
## [10] &quot;play_demo_questionnaire/group_contact_info/parent_phone&quot;                                                                                                                                                                                  
## [11] &quot;play_demo_questionnaire/group_contact_info/parent_email&quot;                                                                                                                                                                                  
## [12] &quot;play_demo_questionnaire/group_contact_info/group_address/note_parent_address&quot;                                                                                                                                                             
## [13] &quot;play_demo_questionnaire/group_contact_info/group_address/parent_address_1&quot;                                                                                                                                                                
## [14] &quot;play_demo_questionnaire/group_contact_info/group_address/parent_address_2&quot;                                                                                                                                                                
## [15] &quot;play_demo_questionnaire/group_contact_info/group_address/city&quot;</code></pre>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" tabindex="-1"></a><span class="fu">head</span>(<span class="fu">names</span>(df3), <span class="dv">15</span>)</span></code></pre></div>
<pre><code>##  [1] &quot;start&quot;                                                                       
##  [2] &quot;end&quot;                                                                         
##  [3] &quot;c_today&quot;                                                                     
##  [4] &quot;play_demo_questionnaire/update_date&quot;                                         
##  [5] &quot;play_demo_questionnaire/note_exp&quot;                                            
##  [6] &quot;play_demo_questionnaire/group_siteinfo/site_id&quot;                              
##  [7] &quot;play_demo_questionnaire/group_siteinfo/subject_number&quot;                       
##  [8] &quot;play_demo_questionnaire/group_siteinfo/exp_name&quot;                             
##  [9] &quot;play_demo_questionnaire/group_contact_info/instructions_contactinfo&quot;         
## [10] &quot;play_demo_questionnaire/group_contact_info/parent_phone&quot;                     
## [11] &quot;play_demo_questionnaire/group_contact_info/parent_email&quot;                     
## [12] &quot;play_demo_questionnaire/group_contact_info/group_address/note_parent_address&quot;
## [13] &quot;play_demo_questionnaire/group_contact_info/group_address/parent_address_1&quot;   
## [14] &quot;play_demo_questionnaire/group_contact_info/group_address/parent_address_2&quot;   
## [15] &quot;play_demo_questionnaire/group_contact_info/group_address/city&quot;</code></pre>
<p>There are a separate set of variable-by-variable cleaning functions in <code>R/screen_clean_utils.R</code>.</p>
<p>We remove the unneeded ’play_demo_*’ and ‘play_phone_questionnaire_’ variable headers using <code>screen_remove_variable_headers()</code>.</p>
<p>We remove fields that contain administrative metadata with <code>screen_remove_metadata_fields()</code>.</p>
<p>We remove fields used only by staff in uploading data to Databrary using <code>screen_remove_databrary_fields()</code>.</p>
<p>We have name and address information in the screening data (e.g., ‘..parent_phone’, ‘..parent_email’, etc.)</p>
<div class="rmdnote">
<p>In a future workflow, we will add Census FIPS IDs for the State and Country
<strong>before</strong> removing the address information.</p>
<p>The Census queries stopped working around 2023-06-16.</p>
<p>For now, we remove identifiers without querying the Census.</p>
</div>
<p>We remove identifiable information using <code>screen_remove_identifiers()</code>.</p>
<p>Then, we use <code>dplyr::full_join()</code> to combine the set of individually
cleaned data files.
The <code>screen_clean_raw_csv()</code> function combines the previous <code>screen_remove*</code> functions.
The <code>screen_clean_raw_join()</code> function cleans each CSV then joins them.</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" tabindex="-1"></a>(scr_df <span class="ot">&lt;-</span> <span class="fu">screen_clean_raw_join</span>())</span></code></pre></div>
<pre><code>## Cleaning &#39;/Users/rog1/rrr/KoBoToolbox/data/csv/screening/275882_PLAY_Demographic_Questionnaire.csv&#39;.</code></pre>
<pre><code>## Removed n = 31 of 168 columns.</code></pre>
<pre><code>## Cleaning &#39;/Users/rog1/rrr/KoBoToolbox/data/csv/screening/334134_PLAY_Demographic_Questionnaire_Spanish.csv&#39;.</code></pre>
<pre><code>## Removed n = 47 of 235 columns.</code></pre>
<pre><code>## Cleaning &#39;/Users/rog1/rrr/KoBoToolbox/data/csv/screening/359546_PLAY_Demographic_Questionnaire.csv&#39;.</code></pre>
<pre><code>## Removed n = 47 of 238 columns.</code></pre>
<pre><code>## Joining with `by = join_by(start, end, c_today, update_date, site_id,
## subject_number, state, check_childage, check_childage_weeks, child_sex, day,
## day2, day1, play_id, language_spoken_mom, `language_spoken_mom/english`,
## `language_spoken_mom/spanish`, `language_spoken_mom/other`,
## language_spoken_mom_other, language_spoken_child,
## `language_spoken_child/english`, `language_spoken_child/spanish`,
## `language_spoken_child/other`, language_spoken_child_other,
## language_spoken_house, `language_spoken_house/english`,
## `language_spoken_house/spanish`, `language_spoken_house/other`,
## language_spoken_house_other, `child_information/child_bornonduedate`,
## `child_information/child_onterm`, `child_information/child_duedate`,
## `child_information/child_birthage`, `child_information/child_weight_pounds`,
## `child_information/child_weight_ounces`,
## `child_information/child_birth_complications`,
## `child_information/specify_birth_complications`,
## `child_information/hearing_disabilities`, `child_information/specify_hearing`,
## `child_information/vision_disabilities`, `child_information/specify_vision`,
## `child_information/major_illnesses_injuries`,
## `child_information/specify_illnesses_injuries`,
## `child_information/other_developmentaldelays`,
## `child_information/specify_developmentaldelays`,
## `child_information/child_race`, `child_information/child_sleep_time`,
## `child_information/child_wake_time`, `child_information/child_nap_hours`,
## `child_information/child_sleep_location`,
## `child_information/specify_child_sleep_location`,
## `child_information/indicate_child`, `child_information/indicate_child_2`,
## `group_family_structure/only_child`,
## `group_family_structure/specify_onlychild`,
## `group_family_structure/household_members`,
## `group_family_structure/household_members/father_biological`,
## `group_family_structure/household_members/male_partner`,
## `group_family_structure/household_members/mother_biological`,
## `group_family_structure/household_members/female_partner`,
## `group_family_structure/household_members/other_partner`,
## `group_family_structure/household_members/sibling_biological`,
## `group_family_structure/household_members/sibling_nonbiological`,
## `group_family_structure/household_members/grandmother`,
## `group_family_structure/household_members/grandfather`,
## `group_family_structure/household_members/great_grandmother`,
## `group_family_structure/household_members/great_grandfather`,
## `group_family_structure/household_members/aunt`,
## `group_family_structure/household_members/uncle`,
## `group_family_structure/household_members/cousin`,
## `group_family_structure/household_members/relative`,
## `group_family_structure/household_members/non_relative`,
## `group_family_structure/household_members/none`,
## `group_family_structure/other_relatives`,
## `group_family_structure/other_non_relatives`,
## `group_family_structure/indicate_familystructure`,
## `group_mominfo/mom_biological`, `group_mominfo/mom_relation`,
## `group_mominfo/mom_datecare`, `group_mominfo/mom_childbirth_age`,
## `group_mominfo/check_mom_childbirth_age`, `group_mominfo/mom_race`,
## `group_mominfo/mom_birth_country`, `group_mominfo/specify_mom_birth_country`,
## `group_mominfo/mom_education`, `group_mominfo/mom_employment`,
## `group_mominfo/mom_occupation`, `group_mominfo/mom_jobs_number`,
## `group_mominfo/mom_training`, `group_mominfo/mom_condition`,
## `group_mominfo/specify_mom_condition`, `group_mominfo/indicate_mom`,
## `group_biodad/biodad_childbirth_age`,
## `group_biodad/check_biodad_childbirth_age`, `group_biodad/biodad_race`,
## `group_biodad/indicate_biodad`, `group_biomom/biomom_childbirth_age`,
## `group_biomom/check_biomom_childbirth_age`, `group_biomom/biomom_race`,
## `group_biomom/indicate_biomom`, `group_nonbiopartner/nonbiopartner_race`,
## `group_nonbiopartner/indicate_nonbiopartner`,
## `group_genpartner_info/partner_education`,
## `group_genpartner_info/partner_employment`,
## `group_genpartner_info/partner_occupation`,
## `group_genpartner_info/partner_jobs_number`,
## `group_genpartner_info/partner_program`,
## `group_genpartner_info/indicate_genpartner`,
## `group_child_care_arrangements/childcare_types`,
## `group_child_care_arrangements/childcare_types/nanny_home`,
## `group_child_care_arrangements/childcare_types/nanny_nothome`,
## `group_child_care_arrangements/childcare_types/relative`,
## `group_child_care_arrangements/childcare_types/childcare`,
## `group_child_care_arrangements/childcare_types/none`,
## `group_child_care_arrangements/childcare_location`,
## `group_child_care_arrangements/childcare_hours`,
## `group_child_care_arrangements/childcare_number`,
## `group_child_care_arrangements/childcare_age`,
## `group_child_care_arrangements/childcare_language`,
## `group_inclusioncheck/inclusionreason`,
## `group_inclusioncheck/indicate_inclusion`, indicate_demoquestionnaire,
## indicate_databrary, `_id`)`
## Joining with `by = join_by(start, end, c_today, update_date, site_id,
## subject_number, state, check_childage, check_childage_weeks, child_sex, day,
## day2, day1, language_spoken_child, `language_spoken_child/english`,
## `language_spoken_child/spanish`, `language_spoken_child/other`,
## language_spoken_child_other, `child_information/child_bornonduedate`,
## `child_information/child_onterm`, `child_information/child_duedate`,
## `child_information/child_birthage`, `child_information/child_weight_pounds`,
## `child_information/child_weight_ounces`,
## `child_information/child_birth_complications`,
## `child_information/specify_birth_complications`,
## `child_information/hearing_disabilities`, `child_information/specify_hearing`,
## `child_information/vision_disabilities`, `child_information/specify_vision`,
## `child_information/major_illnesses_injuries`,
## `child_information/specify_illnesses_injuries`,
## `child_information/child_sleep_time`, `child_information/child_wake_time`,
## `child_information/child_nap_hours`, `child_information/child_sleep_location`,
## `child_information/specify_child_sleep_location`,
## `child_information/indicate_child`, `child_information/indicate_child_2`,
## `group_family_structure/household_members`,
## `group_family_structure/household_members/male_partner`,
## `group_family_structure/household_members/female_partner`,
## `group_family_structure/household_members/other_partner`,
## `group_family_structure/household_members/grandmother`,
## `group_family_structure/household_members/grandfather`,
## `group_family_structure/household_members/great_grandmother`,
## `group_family_structure/household_members/great_grandfather`,
## `group_family_structure/household_members/aunt`,
## `group_family_structure/household_members/uncle`,
## `group_family_structure/household_members/cousin`,
## `group_family_structure/household_members/relative`,
## `group_family_structure/household_members/non_relative`,
## `group_family_structure/other_relatives`,
## `group_family_structure/other_non_relatives`,
## `group_family_structure/indicate_familystructure`,
## `group_child_care_arrangements/childcare_types`,
## `group_child_care_arrangements/childcare_types/relative`,
## `group_child_care_arrangements/childcare_types/childcare`,
## `group_child_care_arrangements/childcare_types/none`,
## `group_child_care_arrangements/childcare_hours`,
## `group_child_care_arrangements/childcare_number`,
## `group_child_care_arrangements/childcare_age`,
## `group_child_care_arrangements/childcare_language`, `_id`)`</code></pre>
<pre><code>## # A tibble: 562 × 162
##    start   end   c_today update_date site_id subject_number state check_childage
##    &lt;chr&gt;   &lt;chr&gt; &lt;chr&gt;   &lt;chr&gt;       &lt;chr&gt;   &lt;chr&gt;          &lt;chr&gt; &lt;chr&gt;         
##  1 2020-0… 2020… 2020-0… &lt;NA&gt;        NYUNI   230            New … 32.6772408503…
##  2 2020-0… 2020… 2020-0… &lt;NA&gt;        NYUNI   229            New … 32.3813828621…
##  3 2019-1… 2020… 2020-0… &lt;NA&gt;        VCOMU   002            VA    26.7258382642…
##  4 2020-0… 2020… 2020-0… &lt;NA&gt;        GEORG   010            Virg… 12.7547666009…
##  5 2020-0… 2020… 2020-0… &lt;NA&gt;        NYUNI   008            New … 13.4122287968…
##  6 2020-0… 2020… 2020-0… &lt;NA&gt;        NYUNI   009            New … 19.3636313828…
##  7 2020-0… 2020… 2020-0… &lt;NA&gt;        GEORG   011            Virg… 17.8514683322…
##  8 2020-0… 2020… 2020-0… &lt;NA&gt;        NYUNI   010            NY    17.8514683322…
##  9 2020-0… 2020… 2020-0… &lt;NA&gt;        NYUNI   011            New … 23.8001314924…
## 10 2020-0… 2020… 2020-0… &lt;NA&gt;        VCOMU   003            VA    17.5884834538…
## # ℹ 552 more rows
## # ℹ 154 more variables: check_childage_weeks &lt;chr&gt;, child_sex &lt;chr&gt;, day &lt;chr&gt;,
## #   day2 &lt;chr&gt;, day1 &lt;chr&gt;, play_id &lt;chr&gt;, language_spoken_mom &lt;chr&gt;,
## #   `language_spoken_mom/english` &lt;chr&gt;, `language_spoken_mom/spanish` &lt;chr&gt;,
## #   `language_spoken_mom/other` &lt;chr&gt;, language_spoken_mom_other &lt;chr&gt;,
## #   language_spoken_child &lt;chr&gt;, `language_spoken_child/english` &lt;chr&gt;,
## #   `language_spoken_child/spanish` &lt;chr&gt;, …</code></pre>
</div>
<div id="clean-individual-fields" class="section level3 unnumbered">
<h3 class="unnumbered">Clean individual fields</h3>
<p>Now, we can proceed to clean-up the merged data frame.
The sequence of functions called below cleans ‘construct-specific’ variables
as indicated by the function names.</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" tabindex="-1"></a>scr_df <span class="ot">&lt;-</span> scr_df <span class="sc">|&gt;</span> </span>
<span id="cb23-2"><a href="#cb23-2" tabindex="-1"></a>    <span class="fu">screen_clean_child_info</span>() <span class="sc">|&gt;</span></span>
<span id="cb23-3"><a href="#cb23-3" tabindex="-1"></a>    <span class="fu">screen_clean_lang_info</span>() <span class="sc">|&gt;</span></span>
<span id="cb23-4"><a href="#cb23-4" tabindex="-1"></a>    <span class="fu">screen_clean_mom_info</span>() <span class="sc">|&gt;</span></span>
<span id="cb23-5"><a href="#cb23-5" tabindex="-1"></a>    <span class="fu">screen_clean_biodad_father_info</span>() <span class="sc">|&gt;</span></span>
<span id="cb23-6"><a href="#cb23-6" tabindex="-1"></a>    <span class="fu">screen_clean_childcare_info</span>() <span class="sc">|&gt;</span></span>
<span id="cb23-7"><a href="#cb23-7" tabindex="-1"></a>    <span class="fu">screen_clean_family_structure</span>() <span class="sc">|&gt;</span></span>
<span id="cb23-8"><a href="#cb23-8" tabindex="-1"></a>    <span class="fu">screen_clean_play_id</span>() <span class="sc">|&gt;</span></span>
<span id="cb23-9"><a href="#cb23-9" tabindex="-1"></a>    <span class="fu">screen_remove_selected_cols</span>() <span class="sc">|&gt;</span></span>
<span id="cb23-10"><a href="#cb23-10" tabindex="-1"></a>    <span class="fu">screen_select_reorder_cols</span>()</span></code></pre></div>
<p>For convenience, we package this sequence in its own function, <code>screen_clean_fields()</code>.</p>
<div class="rmdnote">
<p>Note that all of the variables are considered character strings. The <code>tidyverse</code>
suite does a great job of guessing what variables are what, but sometimes it
guesses wrongly. So, in preliminary stages, it has proved easier to make everything
a character string.</p>
</div>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" tabindex="-1"></a>scr_df <span class="ot">&lt;-</span> <span class="fu">screen_clean_fields</span>(scr_df)</span>
<span id="cb24-2"><a href="#cb24-2" tabindex="-1"></a><span class="fu">str</span>(scr_df)</span></code></pre></div>
<pre><code>## tibble [562 × 51] (S3: tbl_df/tbl/data.frame)
##  $ submit_date                       : chr [1:562] &quot;2020-02-27T08:24:10.551-05:00&quot; &quot;2020-02-27T08:43:34.275-05:00&quot; &quot;2019-12-18T16:37:17.554-05:00&quot; &quot;2020-01-01T12:54:04.550-05:00&quot; ...
##  $ site_id                           : chr [1:562] &quot;NYUNI&quot; &quot;NYUNI&quot; &quot;VCOMU&quot; &quot;GEORG&quot; ...
##  $ participant_ID                    : chr [1:562] &quot;230&quot; &quot;229&quot; &quot;002&quot; &quot;010&quot; ...
##  $ play_id                           : chr [1:562] NA NA NA NA ...
##  $ child_age_mos                     : chr [1:562] &quot;32.677240850317695&quot; &quot;32.38138286215201&quot; &quot;26.725838264299803&quot; &quot;12.754766600920446&quot; ...
##  $ child_sex                         : chr [1:562] &quot;male&quot; &quot;female&quot; &quot;female&quot; &quot;male&quot; ...
##  $ child_bornonduedate               : chr [1:562] &quot;yes&quot; &quot;yes&quot; &quot;yes&quot; &quot;yes&quot; ...
##  $ child_onterm                      : chr [1:562] NA NA NA NA ...
##  $ child_birthage                    : chr [1:562] &quot;-7&quot; &quot;-10&quot; &quot;0&quot; &quot;1&quot; ...
##  $ child_weight_pounds               : chr [1:562] &quot;8&quot; &quot;7&quot; &quot;6&quot; &quot;7&quot; ...
##  $ child_weight_ounces               : chr [1:562] &quot;12&quot; &quot;10&quot; &quot;12&quot; &quot;15&quot; ...
##  $ child_birth_complications         : chr [1:562] &quot;no&quot; &quot;no&quot; &quot;no&quot; &quot;no&quot; ...
##  $ child_birth_complications_specify : chr [1:562] NA NA NA NA ...
##  $ child_hearing_disabilities        : chr [1:562] &quot;yes&quot; &quot;no&quot; &quot;no&quot; &quot;no&quot; ...
##  $ child_hearing_disabilities_specify: chr [1:562] &quot;Temporary hearing loss so tubes in his ears, one still remaining&quot; NA NA NA ...
##  $ child_vision_disabilities         : chr [1:562] &quot;no&quot; &quot;no&quot; &quot;no&quot; &quot;no&quot; ...
##  $ child_vision_disabilities_specify : chr [1:562] NA NA NA NA ...
##  $ child_major_illnesses_injuries    : chr [1:562] &quot;yes&quot; &quot;no&quot; &quot;no&quot; &quot;no&quot; ...
##  $ child_illnesses_injuries_specify  : chr [1:562] &quot;Pneumonia at 5 months&quot; &quot;&quot; &quot;&quot; &quot;&quot; ...
##  $ child_developmentaldelays         : chr [1:562] NA NA NA NA ...
##  $ child_developmentaldelays_specify : chr [1:562] NA NA NA NA ...
##  $ child_sleep_time                  : chr [1:562] &quot;20:15:00.000-05:00&quot; &quot;20:15:00.000-05:00&quot; &quot;19:00:00.000-05:00&quot; &quot;19:00:00.000-05:00&quot; ...
##  $ child_wake_time                   : chr [1:562] &quot;07:15:00.000-05:00&quot; &quot;06:45:00.000-05:00&quot; &quot;07:30:00.000-05:00&quot; &quot;06:15:00.000-05:00&quot; ...
##  $ child_nap_hours                   : chr [1:562] &quot;2&quot; &quot;3&quot; &quot;1.5&quot; &quot;2&quot; ...
##  $ child_sleep_location              : chr [1:562] &quot;crib_separate&quot; &quot;crib_separate&quot; &quot;crib_separate&quot; &quot;crib_separate&quot; ...
##  $ mom_bio                           : chr [1:562] &quot;yes&quot; &quot;yes&quot; &quot;yes&quot; &quot;yes&quot; ...
##  $ mom_childbirth_age                : chr [1:562] &quot;33.41&quot; &quot;38.84&quot; &quot;32.2&quot; &quot;30.38&quot; ...
##  $ mom_race                          : chr [1:562] &quot;white&quot; &quot;white&quot; &quot;white&quot; &quot;white&quot; ...
##  $ mom_birth_country                 : chr [1:562] &quot;unitedstates&quot; &quot;unitedstates&quot; &quot;unitedstates&quot; &quot;unitedstates&quot; ...
##  $ mom_birth_country_specify         : chr [1:562] &quot;&quot; &quot;&quot; &quot;&quot; &quot;&quot; ...
##  $ mom_education                     : chr [1:562] &quot;masters&quot; &quot;doctorate&quot; &quot;doctorate&quot; &quot;masters&quot; ...
##  $ mom_employment                    : chr [1:562] &quot;full_time&quot; &quot;full_time&quot; &quot;full_time&quot; &quot;full_time&quot; ...
##  $ mom_occupation                    : chr [1:562] &quot;Architect&quot; &quot;Spanish teacher&quot; &quot;Nurse instructor&quot; &quot;School Psychologist&quot; ...
##  $ mom_jobs_number                   : chr [1:562] &quot;1&quot; &quot;1&quot; &quot;1&quot; &quot;1&quot; ...
##  $ mom_training                      : chr [1:562] &quot;no&quot; &quot;no&quot; &quot;no&quot; &quot;no&quot; ...
##  $ biodad_childbirth_age             : chr [1:562] &quot;33.85_NA&quot; &quot;30.42_NA&quot; &quot;37.32_NA&quot; &quot;30.53_NA&quot; ...
##  $ biodad_race                       : chr [1:562] &quot;white_NA&quot; &quot;white_NA&quot; &quot;NA_NA&quot; &quot;NA_NA&quot; ...
##  $ language_spoken_mom               : chr [1:562] &quot;english&quot; &quot;english spanish&quot; &quot;english&quot; &quot;english&quot; ...
##  $ language_spoken_mom_comments      : chr [1:562] NA NA NA NA ...
##  $ language_spoken_child             : chr [1:562] &quot;english&quot; &quot;spanish&quot; &quot;english&quot; &quot;english&quot; ...
##  $ language_spoken_home_comments     : chr [1:562] &quot;FALSE_47706996&quot; &quot;TRUE_47707423&quot; &quot;FALSE_43397823&quot; &quot;FALSE_44074192&quot; ...
##  $ language_spoken_child_comments    : chr [1:562] NA NA NA NA ...
##  $ language_spoken_home              : chr [1:562] &quot;english&quot; &quot;english spanish&quot; &quot;english&quot; &quot;english&quot; ...
##  $ language_spoken_house_other       : chr [1:562] NA NA NA NA ...
##  $ language_spoken_home_other        : chr [1:562] NA NA NA NA ...
##  $ childcare_types                   : chr [1:562] NA NA NA NA ...
##  $ childcare_location                : chr [1:562] NA NA NA NA ...
##  $ childcare_hours                   : chr [1:562] NA NA NA NA ...
##  $ childcare_number                  : chr [1:562] NA NA NA NA ...
##  $ childcare_age                     : chr [1:562] NA NA NA NA ...
##  $ childcare_language                : chr [1:562] NA NA NA NA ...</code></pre>
<p>There is more work to do, but we have a version worth exporting.</p>
<p>Let’s add the Databrary volume ID info.</p>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" tabindex="-1"></a>scr_df <span class="ot">&lt;-</span> scr_df <span class="sc">|&gt;</span></span>
<span id="cb26-2"><a href="#cb26-2" tabindex="-1"></a>  <span class="fu">screen_add_db_vol_id</span>()</span></code></pre></div>
<p>Then filter out rows that do not have valid volume IDs.</p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" tabindex="-1"></a>valid_db_vol <span class="ot">&lt;-</span> <span class="sc">!</span><span class="fu">is.na</span>(scr_df<span class="sc">$</span>vol_id)</span>
<span id="cb27-2"><a href="#cb27-2" tabindex="-1"></a></span>
<span id="cb27-3"><a href="#cb27-3" tabindex="-1"></a>scr_df <span class="ot">&lt;-</span> scr_df[valid_db_vol,]</span></code></pre></div>
<p>There are <span class="math inline">\(n=\)</span> 552 valid Databrary volume IDs out of a total of <span class="math inline">\(n=\)</span> 562 screening records.</p>
<p>Next, we add a <code>play_status</code> field based on the <code>group-name</code> field from Databrary.
We use <code>group-name</code> for indicating “Gold”, “Silver”, or “Not run.”</p>
<p>Two targets in <code>_targets.R</code> are relevant for this operation:</p>
<pre><code>  tar_target(
    play_vols_df,
    readr::read_csv(&quot;data/csv/_meta/play_site_vols.csv&quot;,
                    show_col_types = FALSE)
  ),
  tar_target(
    databrary_session_csvs,
    purrr::map(play_vols_df$site_id, databrary_get_save_session_csv),
    cue = tarchetypes::tar_cue_age(
      name = databrary_session_csvs,
      age = as.difftime(update_interval, units = update_interval_units)
    )
  )
</code></pre>
<p>These targets generate site-specific CSVs in <code>data/csv/site_sessions</code> based on the database of PLAY sites contained in <code>data/csv/_meta/play_site_vols.csv</code>.
We load these CSVs into a data frame.</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" tabindex="-1"></a>session_fns <span class="ot">&lt;-</span></span>
<span id="cb29-2"><a href="#cb29-2" tabindex="-1"></a>  <span class="fu">list.files</span>(<span class="st">&quot;../data/csv/site_sessions&quot;</span>, <span class="st">&quot;</span><span class="sc">\\</span><span class="st">.csv$&quot;</span>, <span class="at">full.names =</span> <span class="cn">TRUE</span>)</span>
<span id="cb29-3"><a href="#cb29-3" tabindex="-1"></a></span>
<span id="cb29-4"><a href="#cb29-4" tabindex="-1"></a>df_sessions <span class="ot">&lt;-</span></span>
<span id="cb29-5"><a href="#cb29-5" tabindex="-1"></a>  purrr<span class="sc">::</span><span class="fu">map</span>(</span>
<span id="cb29-6"><a href="#cb29-6" tabindex="-1"></a>    session_fns,</span>
<span id="cb29-7"><a href="#cb29-7" tabindex="-1"></a>    readr<span class="sc">::</span>read_csv,</span>
<span id="cb29-8"><a href="#cb29-8" tabindex="-1"></a>    <span class="at">col_types =</span> readr<span class="sc">::</span><span class="fu">cols</span>(<span class="at">.default =</span> <span class="st">&#39;c&#39;</span>),</span>
<span id="cb29-9"><a href="#cb29-9" tabindex="-1"></a>    <span class="at">show_col_types =</span> <span class="cn">FALSE</span></span>
<span id="cb29-10"><a href="#cb29-10" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb29-11"><a href="#cb29-11" tabindex="-1"></a>  purrr<span class="sc">::</span><span class="fu">list_rbind</span>()</span></code></pre></div>
<p>The <code>group_name</code> variable contains status information about the sessions.</p>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" tabindex="-1"></a><span class="fu">xtabs</span>(<span class="sc">~</span> group_name, <span class="at">data=</span>df_sessions)</span></code></pre></div>
<pre><code>## group_name
##    No visit    No_visit    No_Visit   PLAY_Gold PLAY_Silver 
##           1          12          61         329          76</code></pre>
<p>We note that there are three different versions of no visit: “No visit”, “No_visit”, and “No_Visit”.
In addition, there are <span class="math inline">\(n=\)</span> <code>sum(is.na(df_sessions$group_name))</code> sessions with NA in the <code>group_name</code>.
These could be sessions that are still in QA or which are scheduled, or there could be some other anomaly.
Here, we want to select only those sessions that occurred and which have passed QA–those sessions for which <code>group_name</code> is either ‘PLAY_Gold’ or ‘PLAY_Silver’.</p>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" tabindex="-1"></a>df_sessions <span class="ot">&lt;-</span> df_sessions <span class="sc">|&gt;</span></span>
<span id="cb32-2"><a href="#cb32-2" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">filter</span>(stringr<span class="sc">::</span><span class="fu">str_detect</span>(group_name, <span class="st">&quot;PLAY_&quot;</span>))</span></code></pre></div>
<p>Here is information about the sharing status.</p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" tabindex="-1"></a><span class="fu">xtabs</span>(<span class="sc">~</span> group_name <span class="sc">+</span> session_release, df_sessions)</span></code></pre></div>
<pre><code>##              session_release
## group_name    EXCERPTS PRIVATE SHARED
##   PLAY_Gold        254       0     75
##   PLAY_Silver       60       1     15</code></pre>
<p>There was one session marked <code>PRIVATE</code>.</p>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" tabindex="-1"></a>df_sessions <span class="sc">|&gt;</span></span>
<span id="cb35-2"><a href="#cb35-2" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">filter</span>(session_release <span class="sc">==</span> <span class="st">&quot;PRIVATE&quot;</span>) <span class="sc">|&gt;</span></span>
<span id="cb35-3"><a href="#cb35-3" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(vol_id, session_id, session_name, group_name)</span></code></pre></div>
<pre><code>## # A tibble: 1 × 4
##   vol_id session_id session_name   group_name 
##   &lt;chr&gt;  &lt;chr&gt;      &lt;chr&gt;          &lt;chr&gt;      
## 1 979    66932      PLAY_PRINU_024 PLAY_Silver</code></pre>
<p>Now, we join the screening data with the Databrary session data.</p>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" tabindex="-1"></a>screen_datab_df <span class="ot">&lt;-</span> dplyr<span class="sc">::</span><span class="fu">left_join</span>(df_sessions, scr_df, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">&#39;vol_id&#39;</span>, <span class="st">&#39;participant_ID&#39;</span>))</span></code></pre></div>
</div>
</div>
<div id="export-cleaned-file" class="section level2 unnumbered">
<h2 class="unnumbered">Export cleaned file</h2>
<p>We date-stamp the exported file so we can monitor progress as this workflow develops.</p>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" tabindex="-1"></a>sfn <span class="ot">&lt;-</span> <span class="fu">paste0</span>(<span class="st">&quot;PLAY-screening-datab&quot;</span>, <span class="fu">Sys.Date</span>(), <span class="st">&quot;.csv&quot;</span>)</span>
<span id="cb38-2"><a href="#cb38-2" tabindex="-1"></a>readr<span class="sc">::</span><span class="fu">write_csv</span>(screen_datab_df, <span class="fu">file.path</span>(here<span class="sc">::</span><span class="fu">here</span>(), <span class="st">&quot;data/csv/screening/agg/&quot;</span>, sfn))</span></code></pre></div>
<p>We also save a copy with “latest”.</p>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" tabindex="-1"></a>sfn <span class="ot">&lt;-</span> <span class="st">&quot;PLAY-screening-datab-latest.csv&quot;</span></span>
<span id="cb39-2"><a href="#cb39-2" tabindex="-1"></a>readr<span class="sc">::</span><span class="fu">write_csv</span>(screen_datab_df, <span class="fu">file.path</span>(here<span class="sc">::</span><span class="fu">here</span>(), <span class="st">&quot;data/csv/screening/agg/&quot;</span>, sfn))</span></code></pre></div>
</div>
</div>
<!--bookdown:body:end-->
  </main>

  <div class="col-md-3 col-lg-2 d-none d-md-block sidebar sidebar-chapter">
    <nav id="toc" data-toggle="toc" aria-label="On this page">
      <h2>On this page</h2>
      <div id="book-on-this-page"></div>

      <div class="book-extra">
        <ul class="list-unstyled">
          <li><a id="book-source" href="#">View source <i class="fab fa-github"></i></a></li>
          <li><a id="book-edit" href="#">Edit this page <i class="fab fa-github"></i></a></li>
        </ul>
      </div>
    </nav>
  </div>

</div>
</div> <!-- .container -->

<footer class="bg-primary text-light mt-5">
  <div class="container"><div class="row">

  <div class="col-12 col-md-6 mt-3">
    <p>"<strong></strong>" was written by . </p>
  </div>

  <div class="col-12 col-md-6 mt-3">
    <p>This book was built by the <a class="text-light" href="https://bookdown.org">bookdown</a> R package.</p>
  </div>

</div></div>
</footer>


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
<script type="text/x-mathjax-config">const popovers = document.querySelectorAll('a.footnote-ref[data-toggle="popover"]');
for (let popover of popovers) {
  const div = document.createElement('div');
  div.setAttribute('style', 'position: absolute; top: 0, left:0; width:0, height:0, overflow: hidden; visibility: hidden;');
  div.innerHTML = popover.getAttribute('data-content');

  var has_math = div.querySelector("span.math");
  if (has_math) {
    document.body.appendChild(div);
    MathJax.Hub.Queue(["Typeset", MathJax.Hub, div]);
    MathJax.Hub.Queue(function() {
      popover.setAttribute('data-content', div.innerHTML);
      document.body.removeChild(div);
    })
  }
}
</script>
</body>

</html>
