# Health {-}

```{r health-load-home-visit-df}
# Load home_visit_df if not in environment
if (!("home_visit_df" %in% ls())) {
 targets::tar_load(home_visit_df, store="../_targets") 
}
```

## Feeding {-}

```{r make-feeding-df}
feeding <- home_visit_df %>%
  dplyr::select(
    .,
    age_group,
    child_sex,
    site_id,
    subject_number,
    language_child,
    health.feeding_nutrition.breastfeed,
    health.feeding_nutrition.solidfood_age
  ) %>%
  dplyr::rename(., breastfeed = health.feeding_nutrition.breastfeed,
                solid_food_mos = health.feeding_nutrition.solidfood_age) %>%
  dplyr::mutate(., solid_food_mos = as.numeric(solid_food_mos))
```

```{r}
xtabs(formula = ~ child_sex + breastfeed, data = feeding)
```

```{r fig-solid-food-mos, fig.cap="Age at introduction of solid foods"}
feeding %>%
  ggplot(.) +
  aes(x = solid_food_mos, color = child_sex, fill = child_sex) +
  geom_histogram(bins = 15) +
  theme(legend.title = element_blank())
```

Clearly, there are some impossible values here.

```{r anomalous-feeding}
feeding |>
  dplyr::select(site_id, subject_number, solid_food_mos) %>%
  dplyr::filter(., solid_food_mos > 12) %>%
  knitr::kable(format = 'html')
```

## Smoking/drinking {-}

```{r xtabs-smoking-drinking}
smoking_drinking <- home_visit_df %>%
  dplyr::select(
    .,
    age_group,
    child_sex,
    language_child,
    health.smoking.pregnant_smoking,
    health.drinking.pregnant_drinking
  ) %>%
  dplyr::rename(., preg_smoking = health.smoking.pregnant_smoking,
                preg_drinking = health.drinking.pregnant_drinking)

xtabs(formula = ~ preg_smoking + preg_drinking, smoking_drinking)
```

## Sleeping position {-}

```{r xtabs-sleeping}
sleeping_pos <- home_visit_df %>%
  dplyr::select(
    .,
    age_group,
    child_sex,
    language_child,
    health.general_health.child_sleeping_position
  ) %>%
  dplyr::rename(., child_sleeping_position = health.general_health.child_sleeping_position)

xtabs(formula = ~ child_sleeping_position, data = sleeping_pos)
```
