project:
  type: website
  render:
    - "*.qmd"
  output-dir: "../docs"
website:
  title: "PLAY Survey Data"
  comments: 
    hypothesis:
      theme: clean
  navbar:
    left:
      - href: index.qmd
        text: home
      - href: setup.qmd
        text: background
      - text: screening
        menu: 
          - href: screening-gather.qmd
          - href: screening-clean.qmd
          - href: screening-viz.qmd
      # - text: home-visit
      #   menu:
      #     - href: home-visit-gather.qmd
      # - text: post-visit
      #   menu:
      #     - href: post-visit-gather.qmd
  repo-url: https://github.com/PLAY-behaviorome/KoBoToolbox
  repo-actions: [edit, issue]
  repo-subdir: src
format:
  html:
    theme: default
    css: include/css/style.css
    csl: include/bib/apa.csl
    bibliography: [include/bib/book.bib, include/bib/packages.bib]
    citations-hover: true
    code_folding: hide
    toc: true
    toc_depth: 2
    toc_float: true
editor: source
