# Testing the multi-figure ECBQ workflow

```{r}
library(tidyverse)

hv <- readr::read_csv(file.path(here::here(), "data/csv/home_visit/agg/PLAY-non-mcdi-kobo-latest.csv"), show_col_types = FALSE)
```

```{r ecbq-setup-data}
#| label: select-rothbart-vars
ecbq <- hv |>
  dplyr::select(child_sex, age_group, contains("rothbart"))

ecbq_complete <- ecbq |>
  tidyr::complete() |>
  dplyr::select(-comments_rothbart)

ecbq_vars <- names(ecbq)[stringr::str_detect(names(ecbq_complete),"rothbart_")]
# Drop comments
ecbq_vars <- ecbq_vars[!stringr::str_detect(ecbq_vars, "comments_rothbart")]

# Read questions CSV
ecbq_qs_all <- readr::read_csv(file = file.path(here::here(), "data/csv/_meta", "ecbq_questions.csv"), show_col_types = FALSE)

# Make questions data frame
ecbq_qs_df <- ecbq_qs_all |>
  dplyr::mutate(var_name = ecbq_vars)

# Helper function to retrieve long question given short variable name
retrieve_long_q <- function(this_var= "rothbart_unfamiliarperson", data_dict = ecbq_qs_df) {
  assertthat::is.string(this_var)
  data_dict |>
    filter(var_name == this_var) |>
    select(question) |>
    as.character()
}
```

```{r ecbq-plot-helper-functions}
# Helper plot function
my_ecbq_plot <- function(var_lbl = "rothbart_unfamiliarperson", df) {
  stopifnot(is.data.frame(df))
  stopifnot(is.character(var_lbl))
  
  df <- df |> dplyr::select(child_sex, age_group, {{ var_lbl }})
  
  df <- df |>
    dplyr::filter(!is.na(.data[[var_lbl]])) |>
    dplyr::mutate(rating = factor(
      .data[[var_lbl]],
      c(
        "never",
        "veryrarely",
        "lessthanhalf",
        "abouthalf",
        "morethanhalf",
        "almostalways",
        "always"
      ),
      ordered = TRUE
    ))
  
  ggplot(df) +
    aes(x = rating, fill = child_sex) +
    geom_bar() +
    facet_grid(cols = vars(age_group), rows = vars(child_sex)) +
    # https://stackoverflow.com/questions/1330989/rotating-and-spacing-axis-labels-in-ggplot2
    scale_x_discrete(guide = guide_axis(angle = 90)) +
    theme(legend.position = "none") +
    ggtitle(paste0("Ratings of '", {{var_lbl}}, "'")) +
    xlab("")
}

return_section <- function(var, data) {
  chunk_hdr <- knitr::knit_expand(text = c("### Responses for: `{{this_var}}`", "\n"),
                                  this_var = var)
  
  # Build fig.cap from ground up
  fig_name <- paste0("fig-dist-", var)
  fig_cap <- paste0("'Distribution of responses to `", var, "`'")
  fig_caption <- paste0("fig.cap = ", fig_cap)
  
  plot_chunk_hdr <- paste0("```{r ",
                           fig_name,
                           ", echo = FALSE, warning = FALSE, ",
                           fig_caption,
                           "}")
  
  plot_chunk <- c(plot_chunk_hdr, "print(my_ecbq_plot(var, data))", "```")
  
  question_long <-
    paste0("\n**Q**: '", retrieve_long_q(var), "'", "\n")
  
  knitr::knit_child(
    text = c(chunk_hdr, question_long, plot_chunk),
    envir = environment(),
    quiet = TRUE
  )
}
```

```{r many-tables-lapply, results = "asis", warning=FALSE}
these_vars <- names(df)

res <- invisible(lapply(ecbq_vars, return_section, data = ecbq_complete))
cat(unlist(res), sep = "\n")
```

