PLAY_VOLS <- tibble::tibble(
  play_site_id = c(
    'PLAYProject_GEORG',
    'PLAYProject_CHOPH',
    'PLAYProject_CSULB',
    'PLAYProject_CUNYS',
    'PLAYProject_NYUNI',
    'PLAYProject_INDNA',
    'PLAYProject_OHIOS',
    'PLAYProject_PRINU',
    'PLAYProject_PURDU',
    'PLAYProject_STANF',
    'PLAYProject_UCRIV',
    'PLAYProject_UCSCR',
    'PLAYProject_UHOUS',
    'PLAYProject_VBLTU',
    'PLAYProject_VCOMU',
    'PLAYProject_UIOWA',
    'PLAYProject_BOSTU',
    'PLAYProject_CSUFL',
    'PLAYProject_UGEOR',
    'PLAYProject_UTAUS',
    'PLAYProject_RUTGU',
    'PLAYProject_UMIAM',
    'PLAYProject_UOREG',
    'PLAYProject_CORNL',
    'PLAYProject_MICHS',
    'PLAYProject_PENNS',
    'PLAYProject_UPITT',
    'PLAYProject_UCDAV',
    'PLAYProject_ASUNI',
    'PLAYProject_OHUNI'
  ),
  play_vol_id = c(
    954,
    1370,
    1376,
    1023,
    899,
    1400,
    1103,
    979,
    1363,
    1362,
    966,
    1066,
    1397,
    1391,
    982,
    1422,
    1008,
    1481,
    1515,
    1517,
    1546,
    996,
    1459,
    1576,
    1590,
    1657,
    1663,
    1624,
    1656,
    1596
  ),
  site_name = c(
    "Georgetown University",
    "Children's Hospital of Philadelphia",
    "Cal State Long Beach",
    "CUNY Staten Is",
    "New York University",
    "Indiana University",
    "Ohio State University",
    "Princeton University",
    "Purdue University",
    "Stanford University",
    "UC Riverside",
    "UC Santa Cruz",
    "University of Houston",
    "Vanderbilt University",
    "Virginia Commonwealth University",
    "University of Iowa",
    "Boston University",
    "Cal State Fullerton",
    "University of Georgia",
    "University of Texas at Austin",
    "Rutgers University",
    "University of Miami",
    "University of Oregon",
    "Cornell University",
    "Michigan State University",
    "Penn State University",
    "University of Pittsburgh",
    "UC Davis",
    "Arizona State University",
    "Ohio University"
  )
)